Repository CodeForAfrica/ui, pull requests merged in 2022-05, with the labels that each got.

#66 @/codeforafrica/components/RelatedStories
  apps/codeforafrica/src/components/ArticleCardList/ArticleCardList.js
  apps/codeforafrica/src/components/RelatedStories/RelatedStories.js
  apps/codeforafrica/src/components/RelatedStories/RelatedStories.snap.js
  apps/codeforafrica/src/components/RelatedStories/RelatedStories.test.js
  apps/codeforafrica/src/components/RelatedStories/index.js
  apps/codeforafrica/src/lib/index.js
  apps/codeforafrica/src/pages/stories/[slug].js
Labels: enhancement

#65 @/codeforafrica/components/NewsAndStories
  apps/codeforafrica/src/components/ArticleCardList/ArticleCardList.js
  apps/codeforafrica/src/components/FeaturedArticle/FeaturedArticle.js
  apps/codeforafrica/src/components/FeaturedArticle/FeaturedArticle.snap.js
  apps/codeforafrica/src/components/NewsAndStories/NewsAndStories.js
  apps/codeforafrica/src/components/NewsAndStories/NewsAndStories.snap.js
  apps/codeforafrica/src/components/NewsAndStories/NewsAndStories.test.js
  apps/codeforafrica/src/components/NewsAndStories/index.js
  apps/codeforafrica/src/components/RelatedStories/RelatedStories.js
  apps/codeforafrica/src/components/RelatedStories/RelatedStories.snap.js
  apps/codeforafrica/src/components/RelatedStories/RelatedStories.test.js
  apps/codeforafrica/src/components/RelatedStories/index.js
  apps/codeforafrica/src/lib/index.js
  apps/codeforafrica/src/pages/index.js
  apps/codeforafrica/src/pages/stories/[slug].js
  apps/codeforafrica/src/theme/index.js
Labels: enhancement

#67 @/codeforafrica/components/ChoiceChips
  apps/codeforafrica/src/components/ArticleCardList/ArticleCardList.js
  apps/codeforafrica/src/components/ArticleGrid/ArticleGrid.js
  apps/codeforafrica/src/components/ArticleGrid/ArticleGrid.snap.js
  apps/codeforafrica/src/components/ArticleGrid/ArticleGrid.test.js
  apps/codeforafrica/src/components/ArticleGrid/index.js
  apps/codeforafrica/src/components/ChoiceChip/ChoiceChip.js
  apps/codeforafrica/src/components/ChoiceChip/ChoiceChip.snap.js
  apps/codeforafrica/src/components/ChoiceChip/ChoiceChip.test.js
  apps/codeforafrica/src/components/ChoiceChip/index.js
  apps/codeforafrica/src/components/ChoiceChipGroup/ChoiceChipGroup.js
  apps/codeforafrica/src/components/ChoiceChipGroup/ChoiceChipGroup.snap.js
  apps/codeforafrica/src/components/ChoiceChipGroup/ChoiceChipGroup.test.js
  apps/codeforafrica/src/components/ChoiceChipGroup/index.js
  apps/codeforafrica/src/components/NewsAndStories/NewsAndStories.js
  apps/codeforafrica/src/lib/index.js
  apps/codeforafrica/src/pages/stories/index.js
  apps/codeforafrica/src/theme/index.js
Labels: enhancement

#72 @/codeforafrica/components/NextPreviousPagination
  apps/codeforafrica/next.config.js
  apps/codeforafrica/package.json
  apps/codeforafrica/src/assets/icons/Type=arrow-left, Size=32, Color=White.svg
  apps/codeforafrica/src/assets/icons/Type=arrow-right, Size=32, Color=White.svg
  apps/codeforafrica/src/assets/images/1920x668px bg - 2 2.png
  apps/codeforafrica/src/components/ArticleGrid/ArticleGrid.js
  apps/codeforafrica/src/components/ArticleGrid/ArticleGrid.snap.js
  apps/codeforafrica/src/components/Articles/Articles.js
  apps/codeforafrica/src/components/Articles/Articles.test.js
  apps/codeforafrica/src/components/Articles/index.js
  apps/codeforafrica/src/components/ChoiceChip/ChoiceChip.snap.js
  apps/codeforafrica/src/components/FeaturedArticle/FeaturedArticle.snap.js
  apps/codeforafrica/src/components/Footer/Footer.snap.js
  apps/codeforafrica/src/components/FooterNavList/index.snap.js
  apps/codeforafrica/src/components/NavListItem/index.js
  apps/codeforafrica/src/components/NextPreviousPagination/NextPreviousPagination.js
  apps/codeforafrica/src/components/NextPreviousPagination/NextPreviousPagination.snap.js
  apps/codeforafrica/src/components/NextPreviousPagination/NextPreviousPagination.test.js
  apps/codeforafrica/src/components/NextPreviousPagination/index.js
  apps/codeforafrica/src/pages/stories/index.page.js
  apps/codeforafrica/src/theme/index.js
  packages/jest-config-commons-ui/index.js
  pnpm-lock.yaml
Labels: enhancement

#78 Fix project setup
  .gitignore
  apps/codeforafrica/package.json
  apps/pesayetu/package.json
  apps/promisetracker/package.json
  pnpm-lock.yaml
Labels: chore

#82 @/codeforafrica/components/ProjectTileList
  apps/codeforafrica/src/components/ChoiceChip/ChoiceChip.js
  apps/codeforafrica/src/components/NewsletterSubscription/NewsletterSubscription.test.js
  apps/codeforafrica/src/components/ProjectTile/ProjectTile.js
  apps/codeforafrica/src/components/ProjectTile/ProjectTile.snap.js
  apps/codeforafrica/src/components/ProjectTile/ProjectTile.test.js
  apps/codeforafrica/src/components/ProjectTile/index.js
  apps/codeforafrica/src/components/ProjectTileList/ProjectTileList.js
  apps/codeforafrica/src/components/ProjectTileList/ProjectTileList.snap.js
  apps/codeforafrica/src/components/ProjectTileList/ProjectTileList.test.js
  apps/codeforafrica/src/components/ProjectTileList/index.js
  apps/codeforafrica/src/lib/index.js
  apps/codeforafrica/src/pages/index.page.js
  apps/codeforafrica/src/theme/index.js
Labels: enhancement

#52 [Feature]Add Navigation
  apps/codeforafrica/next.config.js
  apps/codeforafrica/package.json
  apps/codeforafrica/src/assets/CfA logo.svg
  apps/codeforafrica/src/assets/close-button.svg
  apps/codeforafrica/src/assets/menu-icon.svg
  apps/codeforafrica/src/assets/twitterDesktop.svg
  apps/codeforafrica/src/assets/twitterMobile.svg
  apps/codeforafrica/src/components/NavBar/DesktopNavBar/index.js
  apps/codeforafrica/src/components/NavBar/DesktopNavBar/index.test.js
  apps/codeforafrica/src/components/NavBar/MobileNavBar/index.js
  apps/codeforafrica/src/components/NavBar/MobileNavBar/index.test.js
  apps/codeforafrica/src/components/NavBar/index.js
  apps/codeforafrica/src/components/NavBarNavList/index.js
  apps/codeforafrica/src/components/NavBarNavList/index.test.js
  apps/codeforafrica/src/components/NextImageButton/index.js
  apps/codeforafrica/src/components/Page/Page.js
  apps/codeforafrica/src/lib/index.js
  packages/commons-ui-core/src/ImageButton/ImageButton.js
  pnpm-lock.yaml
Labels: enhancement

#94 [Fix] Navigation
  apps/codeforafrica/src/assets/icons/Type=twitter, Size=24, Color=CurrentColor.svg
  apps/codeforafrica/src/assets/twitterDesktop.svg
  apps/codeforafrica/src/assets/twitterMobile.svg
  apps/codeforafrica/src/components/DesktopNavBar/DesktopNavBar.js
  apps/codeforafrica/src/components/DesktopNavBar/DesktopNavBar.snap.js
  apps/codeforafrica/src/components/DesktopNavBar/DesktopNavBar.test.js
  apps/codeforafrica/src/components/DesktopNavBar/index.js
  apps/codeforafrica/src/components/MobileNavBar/MobileNavBar.js
  apps/codeforafrica/src/components/MobileNavBar/MobileNavBar.snap.js
  apps/codeforafrica/src/components/MobileNavBar/MobileNavBar.test.js
  apps/codeforafrica/src/components/MobileNavBar/index.js
  apps/codeforafrica/src/components/NavBar/NavBar.js
  apps/codeforafrica/src/components/NavBar/NavBar.snap.js
  apps/codeforafrica/src/components/NavBar/NavBar.test.js
  apps/codeforafrica/src/components/NavBar/index.js
  apps/codeforafrica/src/components/NavBarNavList/NavBarNavList.js
  apps/codeforafrica/src/components/NavBarNavList/NavBarNavList.snap.js
  apps/codeforafrica/src/components/NavBarNavList/NavBarNavList.test.js
  apps/codeforafrica/src/components/NavBarNavList/index.js
  apps/codeforafrica/src/components/NextImageButton/NextImageButton.js
  apps/codeforafrica/src/components/NextImageButton/NextImageButton.test.js
  apps/codeforafrica/src/components/NextImageButton/index.js
Labels: enhancement

#95 @/codeforafrica/components/TeamMemberCard
  apps/codeforafrica/src/components/TeamMemberCard/TeamMemberCard.js
  apps/codeforafrica/src/components/TeamMemberCard/TeamMemberCard.snap.js
  apps/codeforafrica/src/components/TeamMemberCard/TeamMemberCard.test.js
  apps/codeforafrica/src/components/TeamMemberCard/index.js
  apps/codeforafrica/src/lib/index.js
  apps/codeforafrica/src/pages/projects/[slug].page.js
Labels: enhancement

#96 @/codeforafrica/components/TeamMemberCard/List
  apps/codeforafrica/src/components/TeamMemberCardList/TeamMemberCardList.js
  apps/codeforafrica/src/components/TeamMemberCardList/TeamMemberCardList.snap.js
  apps/codeforafrica/src/components/TeamMemberCardList/TeamMemberCardList.test.js
  apps/codeforafrica/src/components/TeamMemberCardList/index.js
  apps/codeforafrica/src/lib/index.js
  apps/codeforafrica/src/pages/projects/[slug].page.js
Labels: enhancement

#99 [Fix] @svgr/webpack support for eslint
  .lintstagedrc.json
  apps/codeforafrica/.eslintrc.js
  apps/codeforafrica/eslint.webpack.config.js
  apps/codeforafrica/jsconfig.json
  apps/codeforafrica/next.config.js
  apps/codeforafrica/package.json
  apps/codeforafrica/src/components/TeamMemberCard/TeamMemberCard.js
  apps/codeforafrica/src/components/TeamMemberCardList/TeamMemberCardList.js
  package.json
  packages/commons-ui-core/.lintstagedrc.js
  packages/commons-ui-core/src/ImageButton/ImageButton.js
  packages/commons-ui-next/.lintstagedrc.js
  packages/commons-ui-testing-library/.lintstagedrc.js
  packages/eslint-config-commons-ui/.lintstagedrc.js
  pnpm-lock.yaml
Labels: bug, chore
