Repository CodeForAfrica/ui, pull requests merged in 2022-03, with the labels that each got.

#8 [Feature] Monorepo Setup
  .eslintrc.js
  .github/ISSUE_TEMPLATE/bug_template.md
  .github/ISSUE_TEMPLATE/feature_template.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  README.md
  apps/docs/README.md
  apps/docs/next.config.js
  apps/docs/package.json
  apps/docs/pages/index.js
  apps/web/README.md
  apps/web/next.config.js
  apps/web/package.json
  apps/web/pages/index.js
  package.json
  packages/config/eslint-preset.js
  packages/config/package.json
  packages/ui/Button.js
  packages/ui/index.js
  packages/ui/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  turbo.json
Labels: enhancement

#17 Set up Lint, Husky, Prettier
  .editorconfig
  .estlintignore
  .husky/pre-commit
  .prettierignore
  package.json
  packages/config/eslint-preset.js
  pnpm-lock.yaml
Labels: chore

#16 [Chore] Add MUI
  apps/web/package.json
  packages/ui/Button.js
  packages/ui/package.json
  pnpm-lock.yaml
Labels: chore

#21 [Fix] Project config
  .eslintrc.js
  .husky/pre-commit
  .lintstagedrc.json
  README.md
  apps/docs/.eslintrc.js
  apps/docs/.lintstagedrc.js
  apps/docs/jsconfig.json
  apps/docs/package.json
  apps/docs/pages/index.js
  apps/web/.eslintrc.js
  apps/web/.lintstagedrc.js
  apps/web/jsconfig.json
  apps/web/package.json
  apps/web/pages/index.js
  package.json
  packages/config/eslint-preset.js
  packages/config/index.js
  packages/config/jsconfig.json
  packages/config/package.json
  packages/eslint-config-commons-ui/.eslintrc.js
  packages/eslint-config-commons-ui/.lintstagedrc.js
  packages/eslint-config-commons-ui/index.js
  packages/eslint-config-commons-ui/jsconfig.json
  packages/eslint-config-commons-ui/next.js
  packages/eslint-config-commons-ui/package.json
  packages/ui/.eslintrc.js
  packages/ui/.lintstagedrc.js
  packages/ui/Button.js
  packages/ui/index.js
  packages/ui/jsconfig.json
  packages/ui/package.json
  pnpm-lock.yaml
  turbo.json
Labels: bug, chore

#20 [Chore]Add storybook
  apps/docs/src/pages/index.js
  apps/web/src/pages/index.js
  packages/ui/.storybook/main.js
  packages/ui/Button.stories.js
  packages/ui/dist/favicon.ico
  packages/ui/package.json
  pnpm-lock.yaml
Labels: enhancement

#23 [Chore]Add changeset
  .changeset/README.md
  .changeset/config.json
  README.md
  package.json
  pnpm-lock.yaml
Labels: enhancement

#19 [Chore] Setup playwright
  apps/docs/package.json
  apps/docs/playwright.config.js
  apps/docs/src/pages/index.spec.js
  apps/web/package.json
  apps/web/playwright.config.js
  apps/web/src/pages/index.js
  apps/web/src/pages/index.spec.js
  apps/web/src/pages/index.test.js
  packages/config/__mocks__/fileMock.js
  packages/config/jest/presets/jest-preset.js
  packages/playwright-config-commons-ui/.eslintrc.js
  packages/playwright-config-commons-ui/.lintstagedrc.js
  packages/playwright-config-commons-ui/index.js
  packages/playwright-config-commons-ui/jsconfig.json
  packages/playwright-config-commons-ui/package.json
  packages/ui/.storybook/main.js
  packages/ui/package.json
  pnpm-lock.yaml
Labels: chore
