Repository CodeForAfrica/ui, pull requests merged in 2022-08, with the labels that each got.

#186 Fix collections folder location
  apps/codeforafrica/.env
  apps/codeforafrica/contrib/dokku/Dockerfile
  apps/codeforafrica/package.json
  apps/codeforafrica/src/pages/api/admin/config.js
Labels: bug

#168 ft pulled ghost cms data
  .github/workflows/ci.yml
  apps/codeforafrica/env.template
  apps/codeforafrica/jest.config.js
  apps/codeforafrica/next.config.js
  apps/codeforafrica/package.json
  apps/codeforafrica/public/data/posts.json
  apps/codeforafrica/src/components/ArticleCardList/ArticleCardList.js
  apps/codeforafrica/src/components/ArticlePage/ArticlePage.js
  apps/codeforafrica/src/components/ArticlePage/ArticlePage.test.js
  apps/codeforafrica/src/components/Author/Author.js
  apps/codeforafrica/src/components/FeaturedArticle/FeaturedArticle.js
  apps/codeforafrica/src/components/FeaturedArticle/FeaturedArticle.snap.js
  apps/codeforafrica/src/components/FeaturedArticle/FeaturedArticle.test.js
  apps/codeforafrica/src/components/Figure/Figure.js
  apps/codeforafrica/src/components/Opportunities/Opportunities.js
  apps/codeforafrica/src/components/OpportunityCard/OpportunityCard.js
  apps/codeforafrica/src/components/OpportunityCardList/OpportunityCardList.js
  apps/codeforafrica/src/lib/api.ghost/index.js
  apps/codeforafrica/src/lib/api.ghost/posts.js
  apps/codeforafrica/src/lib/index.js
  apps/codeforafrica/src/pages/api/opportunities/index.page.js
  apps/codeforafrica/src/pages/api/stories/index.page.js
  apps/codeforafrica/src/pages/opportunities/[slug].page.js
  apps/codeforafrica/src/pages/stories/[slug].page.js
  pnpm-lock.yaml
Labels: enhancement

#165 CMS footer page
  apps/codeforafrica/content/pages/imprint.md
  apps/codeforafrica/content/pages/privacy-policy.md
  apps/codeforafrica/content/settings/footer.md
  apps/codeforafrica/content/settings/header.md
  apps/codeforafrica/contrib/dokku/Dockerfile
  apps/codeforafrica/package.json
  apps/codeforafrica/public/images/cfa-logo.png
  apps/codeforafrica/public/images/type-facebook-size-32-color-white.svg
  apps/codeforafrica/public/images/type-github-size-32-color-white.svg
  apps/codeforafrica/public/images/type-instagram-size-32-color-white.svg
  apps/codeforafrica/public/images/type-linkedin-size-32-color-white.svg
  apps/codeforafrica/public/images/type-twitter-size-32-color-white.svg
  apps/codeforafrica/public/images/vector.png
  apps/codeforafrica/src/pages/api/admin/config.js
Labels: enhancement

#188 Fix single story page header
  apps/codeforafrica/src/components/ArticleHeader/ArticleHeader.js
  apps/codeforafrica/src/components/ArticleHeader/ArticleHeader.snap.js
  apps/codeforafrica/src/components/ArticlePage/ArticlePage.js
  apps/codeforafrica/src/components/ArticlePage/ArticlePage.snap.js
  apps/codeforafrica/src/components/OpportunityCardList/OpportunityCardList.test.js
  apps/codeforafrica/src/components/ProjectDetails/ProjectStakeholders.js
  apps/codeforafrica/src/components/ShareThisPage/ShareThisPage.js
  apps/codeforafrica/src/components/ShareThisPage/ShareThisPage.snap.js
  apps/codeforafrica/src/pages/about/[unit]/[slug]/index.page.js
Labels: bug

#192 Added Ghost CMS API Key for docker deployment
  .github/workflows/codeforafrica-build-deploy.yml
  Dockerfile
Labels: chore

#194 homepage fixes
  apps/codeforafrica/content/settings/footer.md
  apps/codeforafrica/src/components/MeetOurTeam/MeetOurTeam.js
  apps/codeforafrica/src/components/MeetOurTeam/MeetOurTeam.snap.js
  apps/codeforafrica/src/lib/index.js
Labels: bug

#193 Match ghost post structure
  .gitignore
  apps/codeforafrica/content/settings/footer.md
  apps/codeforafrica/public/data/README.md
  apps/codeforafrica/public/data/posts.json
  apps/codeforafrica/src/components/ArticleGrid/ArticleGrid.js
  apps/codeforafrica/src/components/Articles/Articles.js
  apps/codeforafrica/src/components/Author/Author.js
  apps/codeforafrica/src/components/FeaturedArticle/FeaturedArticle.js
  apps/codeforafrica/src/components/MeetOurTeam/MeetOurTeam.js
  apps/codeforafrica/src/components/MeetOurTeam/MeetOurTeam.snap.js
  apps/codeforafrica/src/components/OpportunityCard/OpportunityCard.js
  apps/codeforafrica/src/components/OpportunityCard/OpportunityCard.snap.js
  apps/codeforafrica/src/components/OpportunityCard/OpportunityCard.test.js
  apps/codeforafrica/src/components/OpportunityCardList/OpportunityCardList.js
  apps/codeforafrica/src/components/OpportunityCardList/OpportunityCardList.snap.js
  apps/codeforafrica/src/components/OpportunityCardList/OpportunityCardList.test.js
  apps/codeforafrica/src/lib/api.fuse.js
  apps/codeforafrica/src/lib/index.js
  apps/promisetracker/public/data/README.md
Labels: bug

#196 Fix html content
  apps/codeforafrica/contrib/dokku/Dockerfile
  apps/codeforafrica/package.json
  apps/codeforafrica/src/components/CMSContent/CMSContent.js
  apps/codeforafrica/src/components/CMSContent/CMSContent.snap.js
  apps/codeforafrica/src/components/GetInTouch/GetInTouch.js
  apps/codeforafrica/src/components/GetInTouch/GetInTouch.snap.js
  apps/codeforafrica/src/components/OurMission/OurMission.js
  apps/codeforafrica/src/components/OurMission/OurMission.snap.js
  apps/codeforafrica/src/pages/about/[unit]/index.snap.js
  apps/codeforafrica/src/pages/imprint/index.page.js
  apps/codeforafrica/src/pages/imprint/index.snap.js
  apps/codeforafrica/src/pages/privacy/index.page.js
  apps/codeforafrica/src/pages/privacy/index.snap.js
  apps/codeforafrica/src/theme/index.js
Labels: bug

#197 Fix image build
  .github/workflows/codeforafrica-build-deploy.yml
  Dockerfile
  apps/codeforafrica/contrib/dokku/Dockerfile
  apps/codeforafrica/package.json
Labels: bug

#198 Fix server error due to missing environment variable.
  apps/codeforafrica/src/lib/api.ghost/posts.js
Labels: bug

#200 Fix missing children prop in CMSContent
  apps/codeforafrica/contrib/dokku/Dockerfile
  apps/codeforafrica/package.json
  apps/codeforafrica/src/components/CMSContent/CMSContent.js
  apps/codeforafrica/src/components/CMSContent/CMSContent.snap.js
  apps/codeforafrica/src/pages/imprint/index.snap.js
  apps/codeforafrica/src/pages/privacy/index.snap.js
Labels: bug

#201 Update Settings “header”
  apps/codeforafrica/content/settings/header.md
Labels: netlify-cms/pending_publish

#195 Ft pull header and footer data from cms backend.
  apps/codeforafrica/content/settings/footer.md
  apps/codeforafrica/content/settings/header.md
  apps/codeforafrica/contrib/dokku/Dockerfile
  apps/codeforafrica/package.json
  apps/codeforafrica/public/images/cfalogobw.png
  apps/codeforafrica/public/images/type-slack-size-32-color-white.svg
  apps/codeforafrica/src/assets/CfA logo.svg
  apps/codeforafrica/src/components/DesktopNavBar/DesktopNavBar.js
  apps/codeforafrica/src/components/DesktopNavBar/DesktopNavBar.snap.js
  apps/codeforafrica/src/components/Footer/Footer.js
  apps/codeforafrica/src/components/Footer/Footer.snap.js
  apps/codeforafrica/src/components/Footer/Footer.test.js
  apps/codeforafrica/src/components/Footer/FooterDescription.js
  apps/codeforafrica/src/components/FooterLinks/FooterLinks.js
  apps/codeforafrica/src/components/FooterNavList/index.js
  apps/codeforafrica/src/components/FooterNavList/index.snap.js
  apps/codeforafrica/src/components/FooterNavList/index.test.js
  apps/codeforafrica/src/components/MobileNavBar/MobileNavBar.js
  apps/codeforafrica/src/components/MobileNavBar/MobileNavBar.snap.js
  apps/codeforafrica/src/components/NavBar/NavBar.js
  apps/codeforafrica/src/components/NavBar/NavBar.snap.js
  apps/codeforafrica/src/components/NavBarNavList/NavBarNavList.js
  apps/codeforafrica/src/components/NavBarNavList/NavBarNavList.test.js
  apps/codeforafrica/src/components/NewsletterSubscription/NewsletterSubscription.js
  apps/codeforafrica/src/components/NewsletterSubscription/NewsletterSubscription.snap.js
  apps/codeforafrica/src/components/StayInTouch/StayInTouch.js
  apps/codeforafrica/src/components/StayInTouchTitle/Title.js
  apps/codeforafrica/src/components/StayInTouchTitle/Title.snap.js
  apps/codeforafrica/src/components/StayInTouchTitle/Title.test.js
  apps/codeforafrica/src/components/StayInTouchTitle/index.js
  apps/codeforafrica/src/lib/api.netlify-cms/index.js
  apps/codeforafrica/src/lib/api.netlify-cms/sections/getFooter.js
  apps/codeforafrica/src/lib/api.netlify-cms/sections/getHeader.js
  apps/codeforafrica/src/lib/api.netlify-cms/sections/getSettings.js
  apps/codeforafrica/src/lib/index.js
  apps/codeforafrica/src/pages/api/admin/config.js
  apps/codeforafrica/src/theme/index.js
Labels: enhancement

#204 Fix input vertical alignment
  apps/codeforafrica/contrib/dokku/Dockerfile
  apps/codeforafrica/package.json
  apps/codeforafrica/src/components/ArticleGrid/ArticleGrid.snap.js
  apps/codeforafrica/src/components/Articles/Articles.snap.js
  apps/codeforafrica/src/components/FilterBar/FilterBar.snap.js
  apps/codeforafrica/src/components/Input/Input.snap.js
  apps/codeforafrica/src/components/Opportunities/Opportunities.snap.js
  apps/codeforafrica/src/components/OurTeam/OurTeam.snap.js
  apps/codeforafrica/src/components/Projects/Projects.snap.js
  apps/codeforafrica/src/components/SearchInput/SearchInput.snap.js
  apps/codeforafrica/src/pages/about/[unit]/index.snap.js
  apps/codeforafrica/src/theme/index.js
Labels: bug

#203 Improve stories page
  apps/codeforafrica/contrib/dokku/Dockerfile
  apps/codeforafrica/package.json
  apps/codeforafrica/src/components/ArticleGrid/ArticleGrid.js
  apps/codeforafrica/src/components/ArticleGrid/ArticleGrid.snap.js
  apps/codeforafrica/src/components/Articles/Articles.js
  apps/codeforafrica/src/components/Articles/Articles.snap.js
  apps/codeforafrica/src/components/FilterBar/FilterBar.snap.js
  apps/codeforafrica/src/components/Footer/FooterDescription.js
  apps/codeforafrica/src/components/Input/Input.snap.js
  apps/codeforafrica/src/components/NavBarNavList/NavBarNavList.snap.js
  apps/codeforafrica/src/components/Opportunities/Opportunities.snap.js
  apps/codeforafrica/src/components/OurMission/OurMission.snap.js
  apps/codeforafrica/src/components/OurTeam/OurTeam.snap.js
  apps/codeforafrica/src/components/ProjectCard/ProjectCard.snap.js
  apps/codeforafrica/src/components/ProjectPageHeader/ProjectPageHeader.snap.js
  apps/codeforafrica/src/components/ProjectTile/ProjectTile.snap.js
  apps/codeforafrica/src/components/ProjectTileList/ProjectTileList.snap.js
  apps/codeforafrica/src/components/Projects/Projects.snap.js
  apps/codeforafrica/src/components/SearchInput/SearchInput.snap.js
  apps/codeforafrica/src/lib/api.ghost/index.js
  apps/codeforafrica/src/lib/index.js
  apps/codeforafrica/src/pages/about/[unit]/index.snap.js
  apps/codeforafrica/src/pages/projects/[slug]/index.snap.js
  apps/codeforafrica/src/pages/stories/index.page.js
  apps/codeforafrica/src/theme/index.js
Labels: bug, enhancement

#206 Dynamically get stories related to a Project
  apps/codeforafrica/contrib/dokku/Dockerfile
  apps/codeforafrica/package.json
  apps/codeforafrica/src/lib/api.ghost/index.js
  apps/codeforafrica/src/lib/index.js
Labels: enhancement

#205 Project setup update
  Dockerfile
  apps/codeforafrica/package.json
  apps/codeforafrica/src/components/ArticleGrid/ArticleGrid.snap.js
  apps/codeforafrica/src/components/ArticlePage/ArticlePage.snap.js
  apps/codeforafrica/src/components/Articles/Articles.snap.js
  apps/codeforafrica/src/components/Author/Author.snap.js
  apps/codeforafrica/src/components/FeaturedArticle/FeaturedArticle.snap.js
  apps/codeforafrica/src/components/FilterBar/FilterBar.snap.js
  apps/codeforafrica/src/components/GetInTouch/GetInTouch.snap.js
  apps/codeforafrica/src/components/Hero/Hero.snap.js
  apps/codeforafrica/src/components/Input/Input.snap.js
  apps/codeforafrica/src/components/MeetOurTeam/MeetOurTeam.snap.js
  apps/codeforafrica/src/components/NextPreviousPagination/PaginationButton.snap.js
  apps/codeforafrica/src/components/Opportunities/Opportunities.snap.js
  apps/codeforafrica/src/components/OpportunityCard/OpportunityCard.snap.js
  apps/codeforafrica/src/components/OpportunityCardList/OpportunityCardList.snap.js
  apps/codeforafrica/src/components/OurTeam/OurTeam.snap.js
  apps/codeforafrica/src/components/ProjectCard/ProjectCard.snap.js
  apps/codeforafrica/src/components/ProjectDetails/ProjectDescription.snap.js
  apps/codeforafrica/src/components/ProjectDetails/ProjectDescriptionButton.snap.js
  apps/codeforafrica/src/components/ProjectDetails/ProjectDetails.snap.js
  apps/codeforafrica/src/components/ProjectDetails/ProjectStakeholders.snap.js
  apps/codeforafrica/src/components/ProjectPageHeader/ProjectPageHeader.snap.js
  apps/codeforafrica/src/components/ProjectTile/ProjectTile.snap.js
  apps/codeforafrica/src/components/ProjectTileList/ProjectTileList.snap.js
  apps/codeforafrica/src/components/Projects/Projects.snap.js
  apps/codeforafrica/src/components/SearchInput/SearchInput.snap.js
  apps/codeforafrica/src/pages/about/[unit]/index.snap.js
  apps/codeforafrica/src/pages/projects/[slug]/index.snap.js
  apps/pesayetu/package.json
  apps/promisetracker/package.json
  package.json
  packages/commons-ui-core/package.json
  packages/commons-ui-next/package.json
  packages/commons-ui-testing-library/package.json
  packages/config/package.json
  packages/eslint-config-commons-ui/index.js
  packages/eslint-config-commons-ui/package.json
  packages/jest-config-commons-ui/index.js
  packages/jest-config-commons-ui/package.json
  packages/playwright-config-commons-ui/package.json
  pnpm-lock.yaml
  turbo.json
Labels: chore, dependencies

#207 Ft load offices from CMS
  apps/codeforafrica/content/offices/abuja.md
  apps/codeforafrica/content/offices/cape-town.md
  apps/codeforafrica/content/offices/dar-es-salaam.md
  apps/codeforafrica/content/offices/lagos.md
  apps/codeforafrica/content/offices/nairobi.md
  apps/codeforafrica/contrib/dokku/Dockerfile
  apps/codeforafrica/package.json
  apps/codeforafrica/src/assets/icons/Type=map-pin, Size=64, Color=Primary.svg
  apps/codeforafrica/src/components/AddressCard/AddressCard.js
  apps/codeforafrica/src/components/GoogleMap/GoogleMap.js
  apps/codeforafrica/src/lib/api.netlify-cms/getOffices.js
  apps/codeforafrica/src/lib/api.netlify-cms/index.js
  apps/codeforafrica/src/lib/index.js
  apps/codeforafrica/src/pages/api/admin/config.js
Labels: enhancement

#216 Fix /about pages
  apps/codeforafrica/content/pages/about.md
  apps/codeforafrica/src/components/GetInTouch/GetInTouch.js
  apps/codeforafrica/src/components/GetInTouch/GetInTouch.snap.js
  apps/codeforafrica/src/components/GuidingPrinciplesCardList/GuidingPrinciplesCardList.js
  apps/codeforafrica/src/components/OurPartners/OurPartners.js
  apps/codeforafrica/src/components/TeamMemberCard/TeamMemberCard.js
  apps/codeforafrica/src/components/TeamMemberCard/TeamMemberCard.snap.js
  apps/codeforafrica/src/components/TeamMemberCardList/TeamMemberCardList.js
  apps/codeforafrica/src/components/TeamMembers/TeamMembers.snap.js
  apps/codeforafrica/src/lib/api.netlify-cms/getGetInTouch.js
  apps/codeforafrica/src/lib/api.netlify-cms/getOurGuidingPrinciples.js
  apps/codeforafrica/src/lib/api.netlify-cms/getOurTeam.js
  apps/codeforafrica/src/lib/api.netlify-cms/getPartners.js
  apps/codeforafrica/src/lib/api.netlify-cms/getTeam.js
  apps/codeforafrica/src/lib/api.netlify-cms/index.js
  apps/codeforafrica/src/lib/index.js
  apps/codeforafrica/src/pages/about/[unit]/index.page.js
  apps/codeforafrica/src/pages/about/[unit]/index.snap.js
  apps/codeforafrica/src/pages/api/admin/config.js
Labels: bug, enhancement

#219 Small fixes
  apps/codeforafrica/content/settings/footer.md
  apps/codeforafrica/content/settings/header.md
  apps/codeforafrica/public/images/cfa-logo.png
  apps/codeforafrica/public/images/cfa-logo.svg
  apps/codeforafrica/public/images/cfalogobw.png
  apps/codeforafrica/public/images/cfalogobw.svg
  apps/codeforafrica/public/images/property-1-action.svg
  apps/codeforafrica/public/images/property-1-ecosystem.svg
  apps/codeforafrica/public/images/property-1-empower.svg
  apps/codeforafrica/public/images/property-1-excellence.svg
  apps/codeforafrica/public/images/property-1-public.svg
  apps/codeforafrica/public/images/property-1-show.svg
  apps/codeforafrica/src/components/ArticleHeader/ArticleHeader.snap.js
  apps/codeforafrica/src/components/ArticlePage/ArticlePage.snap.js
  apps/codeforafrica/src/components/CMSContent/CMSContent.js
  apps/codeforafrica/src/components/CMSContent/CMSContent.snap.js
  apps/codeforafrica/src/components/ConnectBar/ConnectBar.js
  apps/codeforafrica/src/components/ConnectBar/ConnectBar.snap.js
  apps/codeforafrica/src/components/Hero/Hero.js
  apps/codeforafrica/src/components/Hero/Hero.snap.js
  apps/codeforafrica/src/components/Hero/HeroText.js
  apps/codeforafrica/src/components/OurMission/OurMission.js
  apps/codeforafrica/src/components/ProjectDetails/ProjectDetails.snap.js
  apps/codeforafrica/src/components/ProjectDetails/ProjectStakeholders.snap.js
  apps/codeforafrica/src/components/ProjectPageHeader/ProjectPageHeader.js
  apps/codeforafrica/src/components/ProjectPageHeader/ProjectPageHeader.test.js
  apps/codeforafrica/src/components/ProjectTile/ProjectTile.js
  apps/codeforafrica/src/components/ProjectTile/ProjectTile.snap.js
  apps/codeforafrica/src/components/ProjectTile/ProjectTile.test.js
  apps/codeforafrica/src/components/ProjectTileList/ProjectTileList.snap.js
  apps/codeforafrica/src/components/ProjectTileList/ProjectTileList.test.js
  apps/codeforafrica/src/components/ShareButton/ShareButton.snap.js
  apps/codeforafrica/src/components/ShareThisPage/ShareThisPage.snap.js
  apps/codeforafrica/src/components/SocialMediaBar/SocialMediaBar.js
  apps/codeforafrica/src/components/SocialMediaBar/SocialMediaBar.snap.js
  apps/codeforafrica/src/components/SocialMediaButton/SocialMediaButton.js
  apps/codeforafrica/src/components/SocialMediaButton/SocialMediaButton.snap.js
  apps/codeforafrica/src/components/TooltipButton/TooltipButton.js
  apps/codeforafrica/src/components/TooltipButton/TooltipButton.snap.js
  apps/codeforafrica/src/pages/about/[unit]/[slug]/index.page.js
  apps/codeforafrica/src/pages/imprint/index.snap.js
  apps/codeforafrica/src/pages/privacy/index.snap.js
  apps/codeforafrica/src/pages/projects/[slug]/index.snap.js
  apps/codeforafrica/src/pages/projects/[slug]/index.test.js
Labels: bug, enhancement

#222 Load hero content from CMS
  apps/codeforafrica/content/pages/contact.md
  apps/codeforafrica/content/pages/imprint.md
  apps/codeforafrica/content/pages/opportunities.md
  apps/codeforafrica/content/pages/our-work.md
  apps/codeforafrica/content/pages/privacy-policy.md
  apps/codeforafrica/src/lib/api.netlify-cms/sections/getHero.js
  apps/codeforafrica/src/lib/index.js
  apps/codeforafrica/src/pages/api/admin/config.js
Labels: enhancement

#228 Removed font-size from ErrorHero
  apps/codeforafrica/src/components/ErrorHero/ErrorHero.js
Labels: bug

#225 Add meet partners button
  apps/codeforafrica/content/pages/index.md
  apps/codeforafrica/src/components/OurPartners/OurPartners.js
  apps/codeforafrica/src/lib/api.netlify-cms/getOurPartners.js
  apps/codeforafrica/src/lib/index.js
  apps/codeforafrica/src/pages/api/admin/config.js
Labels: enhancement

#236 Ensure there is get in touch section in /about/impact
  apps/codeforafrica/contrib/dokku/Dockerfile
  apps/codeforafrica/package.json
  apps/codeforafrica/src/lib/index.js
Labels: bug

#235 Pull legal pages content from CMS
  apps/codeforafrica/contrib/dokku/Dockerfile
  apps/codeforafrica/package.json
  apps/codeforafrica/src/lib/api.netlify-cms/getBody.js
  apps/codeforafrica/src/lib/api.netlify-cms/index.js
  apps/codeforafrica/src/lib/index.js
Labels: bug

#234 Fix news and stories
  apps/codeforafrica/content/pages/404.md
  apps/codeforafrica/content/pages/error.md
  apps/codeforafrica/content/pages/index.md
  apps/codeforafrica/contrib/dokku/Dockerfile
  apps/codeforafrica/package.json
  apps/codeforafrica/src/components/ErrorPage/ErrorPage.js
  apps/codeforafrica/src/lib/api.netlify-cms/getBody.js
  apps/codeforafrica/src/lib/api.netlify-cms/getNewsAndStories.js
  apps/codeforafrica/src/lib/api.netlify-cms/index.js
  apps/codeforafrica/src/lib/index.js
  apps/codeforafrica/src/pages/api/admin/config.js
Labels: bug, enhancement

#232 Chore use changeset
  .changeset/config.json
  .changeset/light-lions-hug.md
  .github/workflows/release.yml
  .gitignore
  apps/pesayetu/contrib/dokku/Dockerfile
  apps/promisetracker/contrib/dokku/Dockerfile
  apps/promisetracker/package.json
  package.json
  pnpm-lock.yaml
  scripts/bump.js
Labels: enhancement

#240 Release a Patch instead of a Manor release.
  .changeset/light-lions-hug.md
Labels: chore
