Repository CodeForAfrica/ui, pull requests merged in 2022-07, with the labels that each got.

#154 @/codeforafrica/components/input
  apps/codeforafrica/src/assets/icons/Type=search, Size=16, Color=CurrentColor.svg
  apps/codeforafrica/src/components/Articles/Articles.snap.js
  apps/codeforafrica/src/components/ChoiceChip/ChoiceChip.snap.js
  apps/codeforafrica/src/components/ChoiceChipGroup/ChoiceChipGroup.js
  apps/codeforafrica/src/components/ChoiceChipGroup/ChoiceChipGroup.snap.js
  apps/codeforafrica/src/components/FeaturedProjects/FeaturedProjects.js
  apps/codeforafrica/src/components/Input/Input.js
  apps/codeforafrica/src/components/Input/Input.snap.js
  apps/codeforafrica/src/components/Input/Input.test.js
  apps/codeforafrica/src/components/Input/index.js
  apps/codeforafrica/src/components/Opportunities/Opportunities.js
  apps/codeforafrica/src/components/ProjectDetails/ProjectStakeholders.snap.js
  apps/codeforafrica/src/components/Projects/Projects.js
  apps/codeforafrica/src/components/Projects/Projects.snap.js
  apps/codeforafrica/src/components/SearchInput/SearchInput.js
  apps/codeforafrica/src/components/SearchInput/SearchInput.snap.js
  apps/codeforafrica/src/components/SearchInput/SearchInput.test.js
  apps/codeforafrica/src/components/SearchInput/index.js
  apps/codeforafrica/src/lib/index.js
  apps/codeforafrica/src/theme/index.js
  packages/eslint-config-commons-ui/index.js
Labels: enhancement

#156 Fix office addresses
  apps/codeforafrica/src/components/AddressCard/AddressCard.js
  apps/codeforafrica/src/components/OfficeAddresses/OfficeAddresses.js
Labels: bug

#153 Adds Projects collection and their relation to other pages
  apps/codeforafrica/content/donors/drone-deployed.md
  apps/codeforafrica/content/donors/innovateafrica.md
  apps/codeforafrica/content/donors/world-bank.md
  apps/codeforafrica/content/pages/index.md
  apps/codeforafrica/content/partners/afd.md
  apps/codeforafrica/content/partners/code-for-all.md
  apps/codeforafrica/content/partners/deutsche-welle.md
  apps/codeforafrica/content/partners/giz.md
  apps/codeforafrica/content/partners/google-news-initiatives.md
  apps/codeforafrica/content/partners/icjf.md
  apps/codeforafrica/content/partners/meta.md
  apps/codeforafrica/content/partners/pulitzer-center.md
  apps/codeforafrica/content/partners/the-world-bank.md
  apps/codeforafrica/content/partners/unesco.md
  apps/codeforafrica/content/projects/africandrone.md
  apps/codeforafrica/content/projects/civicsignal.md
  apps/codeforafrica/content/projects/pesacheck.md
  apps/codeforafrica/content/projects/sourceafrica.md
  apps/codeforafrica/content/projects/wanadata.md
  apps/codeforafrica/src/pages/admin/index.page.js
  apps/codeforafrica/src/pages/api/admin/config.js
  apps/codeforafrica/src/pages/api/admin/config.json
  apps/codeforafrica/src/pages/api/admin/config.yml.page.js
  pnpm-lock.yaml
Labels: enhancement

#157 Split members into a stand-alone page
  apps/codeforafrica/src/components/AboutPageHeader/AboutPageHeader.js
  apps/codeforafrica/src/components/AboutPageHeader/AboutPageHeader.snap.js
  apps/codeforafrica/src/components/Breadcrumbs/Breadcrumbs.js
  apps/codeforafrica/src/components/Breadcrumbs/Breadcrumbs.snap.js
  apps/codeforafrica/src/components/Breadcrumbs/Breadcrumbs.test.js
  apps/codeforafrica/src/components/Breadcrumbs/index.js
  apps/codeforafrica/src/components/OurTeam/OurTeam.js
  apps/codeforafrica/src/components/ProjectPageHeader/ProjectPageHeader.js
  apps/codeforafrica/src/components/ProjectPageHeader/ProjectPageHeader.snap.js
  apps/codeforafrica/src/lib/index.js
  apps/codeforafrica/src/pages/about/members/index.page.js
  apps/codeforafrica/src/pages/about/members/index.snap.js
  apps/codeforafrica/src/pages/about/members/index.spec.js
  apps/codeforafrica/src/pages/about/members/index.test.js
  apps/codeforafrica/src/pages/projects/[slug].snap.js
Labels: bug, enhancement

#158 Ft about page
  apps/codeforafrica/content/badges/the-best-award.md
  apps/codeforafrica/content/badges/the-news-award.md
  apps/codeforafrica/content/badges/the-press-award.md
  apps/codeforafrica/content/donors/drone-deployed.md
  apps/codeforafrica/content/guiding_principles/partnering-for-excellence.md
  apps/codeforafrica/content/guiding_principles/we-are-action-oriented.md
  apps/codeforafrica/content/guiding_principles/we-empower-citizens.md
  apps/codeforafrica/content/guiding_principles/we-help-build-ecosystems.md
  apps/codeforafrica/content/guiding_principles/we-operate-in-public.md
  apps/codeforafrica/content/guiding_principles/we-show-what’s-possible.md
  apps/codeforafrica/content/our_impact/countries-we-operate-in.md
  apps/codeforafrica/content/our_impact/initiatives.md
  apps/codeforafrica/content/our_impact/staff-members.md
  apps/codeforafrica/content/pages/about.md
  apps/codeforafrica/content/pages/index.md
  apps/codeforafrica/content/projects/africandrone.md
  apps/codeforafrica/content/projects/civicsignal.md
  apps/codeforafrica/content/projects/pesacheck.md
  apps/codeforafrica/content/projects/sourceafrica.md
  apps/codeforafrica/content/projects/wanadata.md
  apps/codeforafrica/content/team/jacobo-ottaviani.md
  apps/codeforafrica/content/team/johnny-miller.md
  apps/codeforafrica/src/pages/api/admin/config.js
Labels: enhancement

#161 @/codeforafrica/pages/about/partners
  apps/codeforafrica/src/components/AboutChildPageHeader/AboutChildPageHeader.js
  apps/codeforafrica/src/components/AboutChildPageHeader/AboutChildPageHeader.snap.js
  apps/codeforafrica/src/components/AboutChildPageHeader/AboutChildPageHeader.test.js
  apps/codeforafrica/src/components/AboutChildPageHeader/index.js
  apps/codeforafrica/src/components/AboutMemberPageHeader/index.js
  apps/codeforafrica/src/components/AboutPageHeader/AboutPageHeader.js
  apps/codeforafrica/src/components/AboutPageHeader/AboutPageHeader.snap.js
  apps/codeforafrica/src/components/GetInTouch/GetInTouch.snap.js
  apps/codeforafrica/src/components/MeetOurTeam/MeetOurTeam.snap.js
  apps/codeforafrica/src/components/OurMission/OurMission.snap.js
  apps/codeforafrica/src/components/OurPartners/OurPartners.js
  apps/codeforafrica/src/components/PageHeader/PageHeader.snap.js
  apps/codeforafrica/src/lib/index.js
  apps/codeforafrica/src/pages/about/[unit]/[slug]/index.page.js
  apps/codeforafrica/src/pages/about/[unit]/[slug]/index.snap.js
  apps/codeforafrica/src/pages/about/[unit]/[slug]/index.spec.js
  apps/codeforafrica/src/pages/about/[unit]/[slug]/index.test.js
  apps/codeforafrica/src/pages/about/[unit]/index.page.js
  apps/codeforafrica/src/pages/about/[unit]/index.snap.js
  apps/codeforafrica/src/pages/about/[unit]/index.spec.js
  apps/codeforafrica/src/pages/about/[unit]/index.test.js
  apps/codeforafrica/src/pages/about/members/[slug].snap.js
  apps/codeforafrica/src/pages/about/members/[slug].spec.js
  apps/codeforafrica/src/pages/about/members/index.spec.js
  apps/codeforafrica/src/pages/imprint/index.snap.js
  apps/codeforafrica/src/pages/opportunities/index.snap.js
  apps/codeforafrica/src/pages/privacy/index.snap.js
  apps/codeforafrica/src/pages/projects/[slug].snap.js
  apps/codeforafrica/src/theme/index.js
Labels: enhancement

#160 Remove outdated note
  README.md
Labels: documentation

#162 Ft contact us page
  apps/codeforafrica/content/offices/abuja.md
  apps/codeforafrica/content/offices/cape-town.md
  apps/codeforafrica/content/offices/dar-es-salaam.md
  apps/codeforafrica/content/offices/lagos.md
  apps/codeforafrica/content/offices/nairobi.md
  apps/codeforafrica/content/pages/contact.md
  apps/codeforafrica/public/images/type-slack-size-64-color-currentcolor.svg
  apps/codeforafrica/src/pages/api/admin/config.js
Labels: enhancement

#166 Adds imprint and privacy policy pages
  apps/codeforafrica/content/pages/imprint.md
  apps/codeforafrica/content/pages/privacy-policy.md
  apps/codeforafrica/src/pages/api/admin/config.js
Labels: enhancement

#170 Prevent robots indexing the site while still in development
  apps/codeforafrica/.env
  apps/codeforafrica/public/image.jpg
  apps/codeforafrica/public/images/image 12.png
  apps/codeforafrica/src/components/Page/Page.js
  apps/codeforafrica/src/lib/index.js
  apps/codeforafrica/src/next-seo.config.js
  apps/codeforafrica/src/pages/_app.page.js
  apps/codeforafrica/src/pages/admin/index.page.js
Labels: enhancement

#173 API driven filtering (for Team)
  apps/codeforafrica/src/components/FilterBar/FilterBar.js
  apps/codeforafrica/src/components/NextPreviousPagination/NextPreviousPagination.js
  apps/codeforafrica/src/components/Opportunities/Opportunities.js
  apps/codeforafrica/src/components/OurMission/OurMission.js
  apps/codeforafrica/src/components/OurTeam/OurTeam.js
  apps/codeforafrica/src/components/OurTeam/OurTeam.snap.js
  apps/codeforafrica/src/components/OurTeam/OurTeam.test.js
  apps/codeforafrica/src/components/OurTeam/useMembers.js
  apps/codeforafrica/src/components/Projects/Projects.js
  apps/codeforafrica/src/components/TeamMemberCard/TeamMemberCard.js
  apps/codeforafrica/src/components/TeamMemberCard/TeamMemberCard.snap.js
  apps/codeforafrica/src/components/TeamMemberCardList/TeamMemberCardList.js
  apps/codeforafrica/src/components/TeamMembers/TeamMembers.snap.js
  apps/codeforafrica/src/components/useFilterQuery/useFilterQuery.js
  apps/codeforafrica/src/lib/index.js
  apps/codeforafrica/src/pages/about/[unit]/index.snap.js
  apps/codeforafrica/src/pages/about/[unit]/index.test.js
  apps/codeforafrica/src/pages/api/members/index.page.js
Labels: enhancement

#174 @/codeforafrica client side search
  apps/codeforafrica/package.json
  apps/codeforafrica/src/components/ArticleGrid/ArticleGrid.js
  apps/codeforafrica/src/components/ArticleGrid/ArticleGrid.snap.js
  apps/codeforafrica/src/components/ArticleGrid/ArticleGrid.test.js
  apps/codeforafrica/src/components/Articles/Articles.js
  apps/codeforafrica/src/components/Articles/Articles.snap.js
  apps/codeforafrica/src/components/Articles/Articles.test.js
  apps/codeforafrica/src/components/Articles/useArticles.js
  apps/codeforafrica/src/lib/api.fuse.js
  apps/codeforafrica/src/lib/index.js
  apps/codeforafrica/src/pages/api/stories/index.page.js
  pnpm-lock.yaml
Labels: enhancement

#175 Update @codeforafrica homepage content
  apps/codeforafrica/content/impact/countries-we-operate-in.md
  apps/codeforafrica/content/impact/initiatives.md
  apps/codeforafrica/content/impact/staff-members.md
  apps/codeforafrica/content/our-impact/countries-we-operate-in.md
  apps/codeforafrica/content/our-impact/initiatives.md
  apps/codeforafrica/content/our-impact/staff-members.md
  apps/codeforafrica/content/pages/about.md
  apps/codeforafrica/content/pages/index.md
  apps/codeforafrica/public/images/initiatives.svg
  apps/codeforafrica/public/images/international.svg
  apps/codeforafrica/public/images/staff.svg
  apps/codeforafrica/src/components/Hero/HeroText.js
  apps/codeforafrica/src/components/ImpactCard/ImpactCard.js
  apps/codeforafrica/src/components/ImpactCardList/ImpactCardList.js
  apps/codeforafrica/src/components/OurPartners/OurPartners.js
  apps/codeforafrica/src/lib/api.netlify-cms/getImpactList.js
  apps/codeforafrica/src/lib/api.netlify-cms/getOurImpact.js
  apps/codeforafrica/src/lib/api.netlify-cms/getOurPartners.js
  apps/codeforafrica/src/lib/api.netlify-cms/index.js
  apps/codeforafrica/src/lib/api.netlify-cms/sections/getHero.js
  apps/codeforafrica/src/lib/index.js
  apps/codeforafrica/src/pages/about/index.page.js
  apps/codeforafrica/src/pages/api/admin/config.js
  apps/codeforafrica/src/pages/index.page.js
Labels: enhancement

#177 Update @codeforafrica about us page content
  apps/codeforafrica/content/impact/beneficiaries-trained.md
  apps/codeforafrica/content/impact/countries-we-operate-in.md
  apps/codeforafrica/content/impact/datasets-produced.md
  apps/codeforafrica/content/impact/initiatives.md
  apps/codeforafrica/content/impact/international-partners.md
  apps/codeforafrica/content/impact/media-partners.md
  apps/codeforafrica/content/impact/staff-members.md
  apps/codeforafrica/content/impact/university-partners.md
  apps/codeforafrica/content/impact/years-in-operation.md
  apps/codeforafrica/content/pages/about.md
  apps/codeforafrica/public/images/Type=book, Size=32, Color=1020E1.svg
  apps/codeforafrica/public/images/Type=calendar, Size=32, Color=1020E1.svg
  apps/codeforafrica/public/images/Type=file, Size=32, Color=1020E1.svg
  apps/codeforafrica/public/images/Type=globe, Size=32, Color=1020E1.svg
  apps/codeforafrica/public/images/Type=layers, Size=32, Color=1020E1.svg
  apps/codeforafrica/public/images/Type=layout, Size=32, Color=1020E1.svg
  apps/codeforafrica/public/images/Type=map-pin, Size=32, Color=1020E1.svg
  apps/codeforafrica/public/images/Type=package, Size=32, Color=1020E1.svg
  apps/codeforafrica/public/images/Type=user, Size=32, Color=1020E1.svg
  apps/codeforafrica/src/components/OurMission/OurMission.js
  apps/codeforafrica/src/components/OurMission/OurMission.snap.js
  apps/codeforafrica/src/components/OurMission/OurMission.test.js
  apps/codeforafrica/src/lib/api.netlify-cms/getOurMission.js
  apps/codeforafrica/src/lib/api.netlify-cms/index.js
  apps/codeforafrica/src/lib/index.js
  apps/codeforafrica/src/pages/api/admin/config.js
Labels: enhancement

#178 Redirect /longform to Ghost Admin dashboard
  apps/codeforafrica/.env
  apps/codeforafrica/env.template
  apps/codeforafrica/next.config.js
Labels: enhancement

#179 Format articles to match ghost post content
  .github/workflows/codeforafrica-build-deploy.yml
  apps/codeforafrica/.env
  apps/codeforafrica/src/components/CMSContent/CMSContent.js
  apps/codeforafrica/src/components/CMSContent/CMSContent.snap.js
  apps/codeforafrica/src/lib/index.js
  apps/codeforafrica/src/pages/imprint/index.snap.js
  apps/codeforafrica/src/pages/privacy/index.snap.js
Labels: enhancement

#180 Fix missing hero props & team member title mixed casing
  apps/codeforafrica/src/components/TeamMemberCard/TeamMemberCard.js
  apps/codeforafrica/src/components/TeamMembers/TeamMembers.snap.js
  apps/codeforafrica/src/lib/index.js
Labels: bug

#181 Remove required env
  .github/workflows/codeforafrica-build-deploy.yml
  Dockerfile
  apps/codeforafrica/package.json
Labels: bug

#184 Enable GitHub auth on Netlify CMS
  apps/codeforafrica/.env
  apps/codeforafrica/contrib/dokku/Dockerfile
  apps/codeforafrica/env.template
  apps/codeforafrica/package.json
  apps/codeforafrica/src/pages/api/admin/config.js
  apps/codeforafrica/src/pages/api/admin/config.yml.page.js
  apps/codeforafrica/src/pages/api/oauth/auth.js
  apps/codeforafrica/src/pages/api/oauth/auth.page.js
  apps/codeforafrica/src/pages/api/oauth/callback.js
  apps/codeforafrica/src/pages/api/oauth/callback.page.js
  pnpm-lock.yaml
Labels: enhancement

#185 Fix image quality
  apps/codeforafrica/.env
  apps/codeforafrica/content/guiding-principles/partnering-for-excellence.md
  apps/codeforafrica/content/guiding-principles/we-are-action-oriented.md
  apps/codeforafrica/content/guiding-principles/we-empower-citizens.md
  apps/codeforafrica/content/guiding-principles/we-help-build-ecosystems.md
  apps/codeforafrica/content/guiding-principles/we-operate-in-public.md
  apps/codeforafrica/content/guiding-principles/we-show-what’s-possible.md
  apps/codeforafrica/content/pages/about.md
  apps/codeforafrica/content/pages/index.md
  apps/codeforafrica/env.template
  apps/codeforafrica/next.config.js
  apps/codeforafrica/public/icons/About icon.png
  apps/codeforafrica/public/icons/About icon2.png
  apps/codeforafrica/public/icons/About icon3.png
  apps/codeforafrica/public/icons/About icon4.png
  apps/codeforafrica/public/icons/About icon5.png
  apps/codeforafrica/public/icons/About icon6.png
  apps/codeforafrica/public/images/Africa@2400x 1.png
  apps/codeforafrica/public/images/Africa@2400x 1lg.png
  apps/codeforafrica/public/images/group-4429.png
  apps/codeforafrica/public/images/property-1-action.svg
  apps/codeforafrica/public/images/property-1-ecosystem.svg
  apps/codeforafrica/public/images/property-1-empower.svg
  apps/codeforafrica/public/images/property-1-excellence.svg
  apps/codeforafrica/public/images/property-1-public.svg
  apps/codeforafrica/public/images/property-1-show.svg
  apps/codeforafrica/src/components/AboutChildPageHeader/AboutChildPageHeader.snap.js
  apps/codeforafrica/src/components/FeaturedArticle/FeaturedArticle.snap.js
  apps/codeforafrica/src/components/GuidingPrinciplesCard/GuidingPrinciplesCard.js
  apps/codeforafrica/src/components/GuidingPrinciplesCard/GuidingPrinciplesCard.snap.js
  apps/codeforafrica/src/components/GuidingPrinciplesCardList/GuidingPrinciplesCardList.js
  apps/codeforafrica/src/components/MeetOurTeam/MeetOurTeam.test.js
  apps/codeforafrica/src/lib/api.netlify-cms/getGuidingPrinciples.js
  apps/codeforafrica/src/lib/api.netlify-cms/getOurGuidingPrinciples.js
  apps/codeforafrica/src/lib/api.netlify-cms/index.js
  apps/codeforafrica/src/lib/index.js
  apps/codeforafrica/src/pages/about/[unit]/[slug]/index.snap.js
  apps/codeforafrica/src/pages/api/admin/config.js
  apps/codeforafrica/src/theme/index.js
Labels: bug
