Repository CodeForAfrica/ui, pull requests merged in 2022-06, with the labels that each got.

#91 [Feature] Article content
  apps/codeforafrica/public/header-image.png
  apps/codeforafrica/public/image 12.png
  apps/codeforafrica/src/components/ArticleCardList/ArticleCardList.js
  apps/codeforafrica/src/components/ArticleHeader/ArticleHeader.js
  apps/codeforafrica/src/components/ArticleHeader/ArticleHeader.snap.js
  apps/codeforafrica/src/components/ArticleHeader/ArticleHeader.test.js
  apps/codeforafrica/src/components/ArticleHeader/index.js
  apps/codeforafrica/src/components/ArticlePage/index.js
  apps/codeforafrica/src/components/ArticlePage/index.snap.js
  apps/codeforafrica/src/components/ArticlePage/index.test.js
  apps/codeforafrica/src/components/Author/Author.js
  apps/codeforafrica/src/components/Author/Author.snap.js
  apps/codeforafrica/src/components/Author/Author.test.js
  apps/codeforafrica/src/components/Author/index.js
  apps/codeforafrica/src/components/FeaturedArticle/FeaturedArticle.js
  apps/codeforafrica/src/components/NavBarNavList/NavBarNavList.snap.js
  apps/codeforafrica/src/components/NewsAndStories/NewsAndStories.js
  apps/codeforafrica/src/lib/index.js
  apps/codeforafrica/src/pages/stories/[slug].page.js
Labels: enhancement

#92 Automate Image building and deployment to Dokku
  .dockerignore
  .github/workflows/codeforafrica-build-deploy.yml
  .gitignore
  Dockerfile
  apps/codeforafrica/next.config.js
  apps/codeforafrica/package.json
  apps/codeforafrica/src/lib/index.js
  pnpm-lock.yaml
Labels: chore

#107 Add Dockerfile to be used for ui deployment
  apps/codeforafrica/contrib/dokku/Dockerfile
Labels: chore

#114 Fix image domains
  .github/workflows/codeforafrica-build-deploy.yml
  apps/codeforafrica/contrib/dokku/Dockerfile
  apps/codeforafrica/package.json
Labels: bug

#124 @/codeforafrica/components/JoinOurSlack
  apps/codeforafrica/src/assets/icons/Type=slack, Size=64, Color=CurrentColor.svg
  apps/codeforafrica/src/components/JoinOurSlack/JoinOurSlack.js
  apps/codeforafrica/src/components/JoinOurSlack/JoinOurSlack.snap.js
  apps/codeforafrica/src/components/JoinOurSlack/JoinOurSlack.test.js
  apps/codeforafrica/src/components/JoinOurSlack/index.js
  apps/codeforafrica/src/components/OfficeAddresses/OfficeAddresses.js
  apps/codeforafrica/src/lib/index.js
  apps/codeforafrica/src/pages/contact.page.js
Labels: enhancement

#118 [Feature] Page Header
  apps/codeforafrica/src/components/ImpactCardList/ImpactCardList.snap.js
  apps/codeforafrica/src/components/PageHeader/PageHeader.js
  apps/codeforafrica/src/components/PageHeader/PageHeader.snap.js
  apps/codeforafrica/src/components/PageHeader/PageHeader.test.js
  apps/codeforafrica/src/components/PageHeader/index.js
  apps/codeforafrica/src/lib/index.js
  apps/codeforafrica/src/pages/contact/index.page.js
  apps/codeforafrica/src/pages/imprint/index.page.js
  apps/codeforafrica/src/pages/opportunities/index.page.js
  apps/codeforafrica/src/pages/projects/index.page.js
  apps/codeforafrica/src/theme/index.js
Labels: enhancement

#121 @/codeforafrica/components/OfficeAddresses
  .github/workflows/codeforafrica-build-deploy.yml
  Dockerfile
  apps/codeforafrica/env.template
  apps/codeforafrica/package.json
  apps/codeforafrica/public/icons/Type=map-pin, Size=64, Color=Primary.svg
  apps/codeforafrica/src/assets/icons/Type=slack, Size=64, Color=CurrentColor.svg
  apps/codeforafrica/src/components/AddressCard/AddressCard.js
  apps/codeforafrica/src/components/AddressCard/AddressCard.snap.js
  apps/codeforafrica/src/components/AddressCard/AddressCard.test.js
  apps/codeforafrica/src/components/AddressCard/index.js
  apps/codeforafrica/src/components/GoogleMap/GoogleMap.js
  apps/codeforafrica/src/components/GoogleMap/GoogleMap.snap.js
  apps/codeforafrica/src/components/GoogleMap/GoogleMap.test.js
  apps/codeforafrica/src/components/GoogleMap/Map.js
  apps/codeforafrica/src/components/GoogleMap/Marker.js
  apps/codeforafrica/src/components/GoogleMap/deep-compare.js
  apps/codeforafrica/src/components/GoogleMap/index.js
  apps/codeforafrica/src/components/ImpactCardList/ImpactCardList.js
  apps/codeforafrica/src/components/JoinOurSlack/JoinOurSlack.js
  apps/codeforafrica/src/components/JoinOurSlack/JoinOurSlack.snap.js
  apps/codeforafrica/src/components/JoinOurSlack/JoinOurSlack.test.js
  apps/codeforafrica/src/components/JoinOurSlack/index.js
  apps/codeforafrica/src/components/OfficeAddresses/OfficeAddresses.js
  apps/codeforafrica/src/components/OfficeAddresses/OfficeAddresses.snap.js
  apps/codeforafrica/src/components/OfficeAddresses/OfficeAddresses.test.js
  apps/codeforafrica/src/components/OfficeAddresses/index.js
  apps/codeforafrica/src/lib/index.js
  apps/codeforafrica/src/pages/contact.page.js
  apps/codeforafrica/src/pages/contact.snap.js
  apps/codeforafrica/src/pages/contact.spec.js
  apps/codeforafrica/src/pages/contact.test.js
  apps/codeforafrica/src/theme/index.js
  pnpm-lock.yaml
Labels: enhancement

#129 @/codeforafrica/components/AboutMemberPageHeader
  apps/codeforafrica/src/components/AboutMemberPageHeader/AboutMemberPageHeader.js
  apps/codeforafrica/src/components/AboutMemberPageHeader/AboutMemberPageHeader.snap.js
  apps/codeforafrica/src/components/AboutMemberPageHeader/AboutMemberPageHeader.test.js
  apps/codeforafrica/src/components/AboutMemberPageHeader/index.js
  apps/codeforafrica/src/components/AccoladeBadge/AccoladeBadge.js
  apps/codeforafrica/src/components/AccoladeBadge/AccoladeBadge.snap.js
  apps/codeforafrica/src/components/AccoladeBadge/AccoladeBadge.test.js
  apps/codeforafrica/src/components/AccoladeBadgeList/AccoladeBadgeList.js
  apps/codeforafrica/src/components/FeaturedArticle/FeaturedArticle.snap.js
  apps/codeforafrica/src/components/GetInTouch/GetInTouch.snap.js
  apps/codeforafrica/src/components/Hero/Hero.snap.js
  apps/codeforafrica/src/components/NavBarNavList/NavBarNavList.snap.js
  apps/codeforafrica/src/components/PageHeader/PageHeader.js
  apps/codeforafrica/src/components/ProjectCard/ProjectCard.snap.js
  apps/codeforafrica/src/components/ProjectPageHeader/ProjectPageHeader.snap.js
  apps/codeforafrica/src/components/ProjectTile/ProjectTile.snap.js
  apps/codeforafrica/src/components/ProjectTileList/ProjectTileList.snap.js
  apps/codeforafrica/src/components/TeamMemberCard/TeamMemberCard.js
  apps/codeforafrica/src/components/TeamMemberCard/TeamMemberCard.snap.js
  apps/codeforafrica/src/components/TwoToneBackground/TwoToneBackground.js
  apps/codeforafrica/src/components/TwoToneBackground/TwoToneBackground.snap.js
  apps/codeforafrica/src/lib/index.js
  apps/codeforafrica/src/pages/about/members/[slug].page.js
  apps/codeforafrica/src/pages/about/members/[slug].snap.js
  apps/codeforafrica/src/pages/projects/[slug].page.js
  apps/codeforafrica/src/pages/projects/[slug].snap.js
  apps/codeforafrica/src/theme/index.js
Labels: enhancement

#130 @/codeforafrica/components/NextPagination
  apps/codeforafrica/contrib/dokku/Dockerfile
  apps/codeforafrica/package.json
  apps/codeforafrica/src/components/Articles/Articles.js
  apps/codeforafrica/src/components/GuidingPrinciplesCard/GuidingPrinciplesCard.snap.js
  apps/codeforafrica/src/components/NextPreviousPagination/NextPreviousPagination.js
  apps/codeforafrica/src/components/NextPreviousPagination/PaginationButton.js
  apps/codeforafrica/src/components/NextPreviousPagination/PaginationButton.snap.js
  apps/codeforafrica/src/components/NextPreviousPagination/PaginationButton.test.js
  apps/codeforafrica/src/components/Projects/Projects.js
  apps/codeforafrica/src/components/Projects/Projects.snap.js
  apps/codeforafrica/src/components/Projects/Projects.test.js
  apps/codeforafrica/src/components/Projects/index.js
  apps/codeforafrica/src/pages/projects/index.page.js
Labels: enhancement

#136 @/codeforafrica/components/ProjectDetails
  apps/codeforafrica/src/assets/icons/Type=database, Size=24, Color=CurrentColor.svg
  apps/codeforafrica/src/assets/icons/Type=github, Size=24, Color=CurrentColor.svg
  apps/codeforafrica/src/components/FeaturedArticle/FeaturedArticle.snap.js
  apps/codeforafrica/src/components/GetInTouch/GetInTouch.snap.js
  apps/codeforafrica/src/components/OpportunityCard/OpportunityCard.snap.js
  apps/codeforafrica/src/components/OpportunityCard/OpportunityCard.test.js
  apps/codeforafrica/src/components/ProjectDetails/ProjectDescription.js
  apps/codeforafrica/src/components/ProjectDetails/ProjectDescription.snap.js
  apps/codeforafrica/src/components/ProjectDetails/ProjectDescription.test.js
  apps/codeforafrica/src/components/ProjectDetails/ProjectDescriptionButton.js
  apps/codeforafrica/src/components/ProjectDetails/ProjectDescriptionButton.snap.js
  apps/codeforafrica/src/components/ProjectDetails/ProjectDescriptionButton.test.js
  apps/codeforafrica/src/components/ProjectDetails/ProjectDetails.js
  apps/codeforafrica/src/components/ProjectDetails/ProjectDetails.snap.js
  apps/codeforafrica/src/components/ProjectDetails/ProjectDetails.test.js
  apps/codeforafrica/src/components/ProjectDetails/ProjectStakeholders.js
  apps/codeforafrica/src/components/ProjectDetails/ProjectStakeholders.snap.js
  apps/codeforafrica/src/components/ProjectDetails/ProjectStakeholders.test.js
  apps/codeforafrica/src/components/ProjectDetails/index.js
  apps/codeforafrica/src/components/ProjectPageHeader/ProjectPageHeader.js
  apps/codeforafrica/src/components/RelatedStories/RelatedStories.js
  apps/codeforafrica/src/components/SectionDivider/SectionDivider.js
  apps/codeforafrica/src/components/SectionDivider/SectionDivider.snap.js
  apps/codeforafrica/src/components/SectionDivider/SectionDivider.test.js
  apps/codeforafrica/src/components/SectionDivider/index.js
  apps/codeforafrica/src/components/TeamMembers/TeamMembers.js
  apps/codeforafrica/src/components/TeamMembers/TeamMembers.snap.js
  apps/codeforafrica/src/components/TeamMembers/TeamMembers.test.js
  apps/codeforafrica/src/components/TeamMembers/index.js
  apps/codeforafrica/src/lib/index.js
  apps/codeforafrica/src/pages/projects/[slug].page.js
  apps/codeforafrica/src/pages/projects/[slug].snap.js
  apps/codeforafrica/src/theme/index.js
Labels: bug, enhancement

#138 @/codeforafrica/components/OurMission
  apps/codeforafrica/src/components/GuidingPrinciplesCardList/GuidingPrinciplesCardList.js
  apps/codeforafrica/src/components/NextPreviousPagination/NextPreviousPagination.js
  apps/codeforafrica/src/components/OurMission/OurMission.js
  apps/codeforafrica/src/components/OurMission/OurMission.snap.js
  apps/codeforafrica/src/components/OurMission/OurMission.test.js
  apps/codeforafrica/src/components/OurMission/index.js
  apps/codeforafrica/src/lib/index.js
  apps/codeforafrica/src/pages/about/index.page.js
Labels: bug, enhancement

#137 [Feature] About Page Header
  apps/codeforafrica/src/components/AboutPageHeader/AboutPageHeader.js
  apps/codeforafrica/src/components/AboutPageHeader/AboutPageHeader.snap.js
  apps/codeforafrica/src/components/AboutPageHeader/AboutPageHeader.test.js
  apps/codeforafrica/src/components/AboutPageHeader/index.js
  apps/codeforafrica/src/components/OpportunityCard/OpportunityCard.test.js
  apps/codeforafrica/src/components/OpportunityCardList/OpportunityCardList.js
  apps/codeforafrica/src/components/OpportunityCardList/OpportunityCardList.snap.js
  apps/codeforafrica/src/components/OpportunityCardList/OpportunityCardList.test.js
  apps/codeforafrica/src/components/PageHeader/PageHeader.js
  apps/codeforafrica/src/components/PageHeader/PageHeader.snap.js
  apps/codeforafrica/src/components/PageHeader/PageHeader.test.js
  apps/codeforafrica/src/lib/index.js
  apps/codeforafrica/src/pages/about/index.page.js
  apps/codeforafrica/src/pages/imprint/index.snap.js
  apps/codeforafrica/src/pages/opportunities/index.snap.js
  apps/codeforafrica/src/pages/privacy/index.snap.js
  apps/codeforafrica/src/theme/index.js
Labels: enhancement

#147 Update pnpm-lock.yaml file
  package.json
  pnpm-lock.yaml
Labels: chore

#148 Remove standalone task from pipeline
  apps/codeforafrica/package.json
  apps/pesayetu/package.json
  apps/promisetracker/package.json
  package.json
  turbo.json
Labels: chore

#149 Ensure Docker image is updated
  Dockerfile
Labels: chore
