Repository CodeForAfrica/ui, pull requests merged in 2023-01, with the labels that each got.

#277 @/charterafrica/LanguageButton
  apps/charterafrica/.env
  apps/charterafrica/.env.template
  apps/charterafrica/env.template
  apps/charterafrica/jest.setup.js
  apps/charterafrica/next.config.js
  apps/charterafrica/payload.config.js
  apps/charterafrica/src/assets/icons/Type=chevron-down, Size=16, Color=CurrentColor.svg
  apps/charterafrica/src/assets/icons/Type=chevron-down, Size=16, Color=White.svg
  apps/charterafrica/src/assets/icons/Type=chevron-up, Size=16, Color=CurrentColor.svg
  apps/charterafrica/src/assets/icons/Type=chevron-up, Size=16, Color=White.svg
  apps/charterafrica/src/assets/icons/Type=globe, Size=24, Color=CurrentColor.svg
  apps/charterafrica/src/components/DesktopNavBar/DesktopNavBar.js
  apps/charterafrica/src/components/DesktopNavBar/DesktopNavBar.snap.js
  apps/charterafrica/src/components/DesktopNavBar/DesktopNavBar.test.js
  apps/charterafrica/src/components/DropdownMenu/DropdownMenu.js
  apps/charterafrica/src/components/DropdownMenu/DropdownMenu.snap.js
  apps/charterafrica/src/components/DropdownMenu/DropdownMenu.test.js
  apps/charterafrica/src/components/DropdownMenu/index.js
  apps/charterafrica/src/components/LanguageButton/LanguageButton.js
  apps/charterafrica/src/components/LanguageButton/LanguageButton.snap.js
  apps/charterafrica/src/components/LanguageButton/LanguageButton.test.js
  apps/charterafrica/src/components/LanguageButton/index.js
  apps/charterafrica/src/components/Layout/Layout.snap.js
  apps/charterafrica/src/components/Layout/Layout.test.js
  apps/charterafrica/src/components/NavBar/NavBar.js
  apps/charterafrica/src/components/NavBar/NavBar.snap.js
  apps/charterafrica/src/components/NavBar/NavBar.test.js
  apps/charterafrica/src/components/NavBarDropdown/NavBarDropdown.js
  apps/charterafrica/src/components/NavBarDropdown/NavBarDropdown.snap.js
  apps/charterafrica/src/components/NavBarDropdown/NavBarDropdown.test.js
  apps/charterafrica/src/components/NavBarNavList/NavBarNavList.snap.js
  apps/charterafrica/src/components/NavBarNavList/NavBarNavList.test.js
  apps/charterafrica/src/components/OpenCloseIcon/OpenCloseIcon.js
  apps/charterafrica/src/components/OpenCloseIcon/OpenCloseIcon.snap.js
  apps/charterafrica/src/components/OpenCloseIcon/OpenCloseIcon.test.js
  apps/charterafrica/src/components/OpenCloseIcon/index.js
  apps/charterafrica/src/components/Popper/Popper.js
  apps/charterafrica/src/components/Popper/Popper.snap.js
  apps/charterafrica/src/components/Popper/Popper.test.js
  apps/charterafrica/src/components/Popper/index.js
  apps/charterafrica/src/pages/index.page.js
  apps/charterafrica/src/payload/globals/Settings.js
  apps/charterafrica/src/payload/utils/locales.js
  packages/commons-ui-next/src/Link/Link.js
  turbo.json
Labels: bug, enhancement, dependencies

#293 Feat @/charterafrica/cms Focal Countries support
  apps/charterafrica/package.json
  apps/charterafrica/payload.config.js
  apps/charterafrica/src/components/FocalCountries/FocalCountries.js
  apps/charterafrica/src/components/FocalCountries/FocalCountries.snap.js
  apps/charterafrica/src/components/FocalCountries/FocalCountries.test.js
  apps/charterafrica/src/components/RichText/RichText.js
  apps/charterafrica/src/components/RichText/RichText.snap.js
  apps/charterafrica/src/components/RichText/RichText.test.js
  apps/charterafrica/src/components/RichText/index.js
  apps/charterafrica/src/pages/index.page.js
  apps/charterafrica/src/payload/fields/link.js
  apps/charterafrica/src/payload/globals/FocalCountries.js
  apps/charterafrica/src/payload/globals/Navigation.js
  apps/charterafrica/src/payload/utils/expandDoc.js
  apps/charterafrica/src/payload/utils/mapLinkTypeToHref.js
  pnpm-lock.yaml
Labels: enhancement

#294 @/charterafrica Mobile NavBar
  apps/charterafrica/src/assets/icons/Type=x, Size=32, Color=White.svg
  apps/charterafrica/src/components/DesktopNavBar/DesktopNavBar.js
  apps/charterafrica/src/components/Layout/Layout.snap.js
  apps/charterafrica/src/components/MobileNavBar/MobileDrawer.js
  apps/charterafrica/src/components/MobileNavBar/MobileNavBar.js
  apps/charterafrica/src/components/MobileNavBar/MobileNavBar.snap.js
  apps/charterafrica/src/components/NavBar/NavBar.js
  apps/charterafrica/src/components/NavBar/NavBar.snap.js
  apps/charterafrica/src/components/NavBarNavList/NavBarNavList.js
  apps/charterafrica/src/components/NavBarNavList/NavBarNavList.snap.js
  apps/charterafrica/src/components/NavBarNavMenu/NavBarNavMenu.js
  apps/charterafrica/src/components/NavBarNavMenu/NavBarNavMenu.snap.js
  apps/charterafrica/src/components/NavBarNavMenu/NavBarNavMenu.test.js
  apps/charterafrica/src/components/NavBarNavMenu/index.js
  packages/commons-ui-core/src/NavBar/NavBar.js
Labels: enhancement

#295 Feat/charterafrica cms democracy helpdesk 284
  apps/charterafrica/payload.config.js
  apps/charterafrica/src/components/Helpdesk/Helpdesk.js
  apps/charterafrica/src/components/Helpdesk/Helpdesk.snap.js
  apps/charterafrica/src/components/Helpdesk/Helpdesk.test.js
  apps/charterafrica/src/components/RichText/RichText.js
  apps/charterafrica/src/pages/index.page.js
  apps/charterafrica/src/payload/globals/Helpdesk.js
Labels: enhancement

#298 @/charterafrica cms resources
  apps/charterafrica/payload.config.js
  apps/charterafrica/src/components/Resources/Resource.js
  apps/charterafrica/src/components/Resources/Resources.snap.js
  apps/charterafrica/src/components/Resources/Resources.test.js
  apps/charterafrica/src/pages/index.page.js
  apps/charterafrica/src/payload/blocks/Resources.js
  apps/charterafrica/src/payload/collections/Pages.js
  apps/charterafrica/src/payload/collections/Resources.js
  apps/charterafrica/src/payload/fields/link.js
  apps/charterafrica/src/payload/fields/linkArray.js
  apps/charterafrica/src/payload/fields/linkGroup.js
  apps/charterafrica/src/payload/globals/FocalCountries.js
  apps/charterafrica/src/payload/globals/Navigation.js
  apps/charterafrica/src/payload/globals/Settings.js
  apps/charterafrica/src/payload/utils/expandDoc.js
  apps/charterafrica/src/payload/utils/mapLinkTypeToHref.js
Labels: enhancement

#305 @/charterafrica Build
  Dockerfile.charterafrica
  apps/charterafrica/package.json
  apps/charterafrica/payload.config.js
  apps/charterafrica/server.js
  apps/charterafrica/src/pages/index.page.js
  apps/charterafrica/src/payload/globals/Settings.js
  apps/charterafrica/src/payload/utils/locales.js
  pnpm-lock.yaml
  turbo.json
Labels: bug

#274 CI/CD
  .dockerignore
  .github/workflows/charterafrica-deploy-dev.yml
  .github/workflows/charterafrica-deploy-prod.yml
  .github/workflows/ci.yml
  .github/workflows/codeforafrica-deploy-prod.yml
  .github/workflows/release-prod.yml
  Dockerfile.charterafrica
  apps/charterafrica/.env
  apps/charterafrica/contrib/dokku/Dockerfile
  apps/charterafrica/package.json
Labels: chore

#311 @charterafrica configurable nav actions
  apps/charterafrica/src/components/DesktopNavBar/DesktopNavBar.js
  apps/charterafrica/src/components/DesktopNavBar/DesktopNavBar.snap.js
  apps/charterafrica/src/components/Ecosystem/Ecosystem.snap.js
  apps/charterafrica/src/components/Layout/Layout.snap.js
  apps/charterafrica/src/components/LineClampedRichTypography/LineClampedRichTypography.js
  apps/charterafrica/src/components/MobileNavBar/MobileDrawer.js
  apps/charterafrica/src/components/MobileNavBar/MobileNavBar.js
  apps/charterafrica/src/components/NavBar/NavBar.js
  apps/charterafrica/src/components/NavBar/NavBar.snap.js
  apps/charterafrica/src/components/NavBarDropdown/NavBarDropdown.js
  apps/charterafrica/src/components/SearchInput/SearchInput.js
  apps/charterafrica/src/components/SearchInput/SearchInput.snap.js
  apps/charterafrica/src/components/Spotlight/Spotlight.js
  apps/charterafrica/src/pages/index.page.js
  apps/charterafrica/src/pages/opportunities/[slug].page.js
  apps/charterafrica/src/payload/blocks/Spotlight.js
  apps/charterafrica/src/payload/globals/Navigation.js
Labels: enhancement

#312 Bump version: 0.0.6 → 0.0.7
  apps/charterafrica/contrib/dokku/Dockerfile
  apps/charterafrica/package.json
Labels: chore

#313 Bump version: 0.0.7 → 0.0.8
  apps/charterafrica/contrib/dokku/Dockerfile
  apps/charterafrica/package.json
Labels: chore
