Repository CodeForAfrica/ui, pull requests merged in 2023-03, with the labels that each got.

#339 Add posts news
  apps/charterafrica/payload.config.ts
  apps/charterafrica/src/components/Accordion/Accordion.snap.js
  apps/charterafrica/src/components/CommunityPlatforms/CommunityPlatforms.snap.js
  apps/charterafrica/src/components/Error/Error.snap.js
  apps/charterafrica/src/components/ErrorPage/ErrorPage.snap.js
  apps/charterafrica/src/components/Explainers/Explainers.snap.js
  apps/charterafrica/src/components/FAQ/FAQ.snap.js
  apps/charterafrica/src/components/FeaturedPostCard/FeaturedPostCard.js
  apps/charterafrica/src/components/FeaturedPostCard/FeaturedPostCard.snap.js
  apps/charterafrica/src/components/FeaturedPostCard/FeaturedPostCard.test.js
  apps/charterafrica/src/components/FocalCountries/FocalCountries.snap.js
  apps/charterafrica/src/components/Footer/Footer.snap.js
  apps/charterafrica/src/components/Grantees/Grantees.snap.js
  apps/charterafrica/src/components/GuidingPrinciples/GuidingPrinciples.snap.js
  apps/charterafrica/src/components/Helpdesk/Helpdesk.snap.js
  apps/charterafrica/src/components/HelpdeskPageContent/HelpdeskPageContent.snap.js
  apps/charterafrica/src/components/Hero/Hero.snap.js
  apps/charterafrica/src/components/Impressum/Impressum.snap.js
  apps/charterafrica/src/components/Layout/Layout.snap.js
  apps/charterafrica/src/components/PageDescription/PageDescription.snap.js
  apps/charterafrica/src/components/PageHeader/PageHeader.snap.js
  apps/charterafrica/src/components/PostCard/PostCard.js
  apps/charterafrica/src/components/RichText/RichText.js
  apps/charterafrica/src/components/RichText/RichText.snap.js
  apps/charterafrica/src/lib/data/common/index.js
  apps/charterafrica/src/lib/payload/index.js
  apps/charterafrica/src/pages/[...slugs].page.js
  apps/charterafrica/src/payload/blocks/ExternalEmbed.js
  apps/charterafrica/src/payload/blocks/FeaturedPost.js
  apps/charterafrica/src/payload/blocks/MediaBlock.js
  apps/charterafrica/src/payload/blocks/RichText.js
  apps/charterafrica/src/payload/collections/Authors.js
  apps/charterafrica/src/payload/collections/News.js
  apps/charterafrica/src/payload/collections/Pages.js
  apps/charterafrica/src/payload/collections/Tags.js
  apps/charterafrica/src/payload/fields/blockFields.js
  apps/charterafrica/src/payload/fields/post.js
Labels: enhancement

#356 chaterafrica define CSRF config
  apps/charterafrica/.env.template
  apps/charterafrica/payload.config.ts
  turbo.json
Labels: chore

#357 Close charterafrica mobile drawer after click
  apps/charterafrica/src/components/LanguageButton/LanguageButton.js
  apps/charterafrica/src/components/MobileNavBar/MobileNavBar.js
  apps/charterafrica/src/components/NavBarDropdown/NavBarDropdown.js
Labels: bug

#359 Handle undefined CSRF and CORS
  apps/charterafrica/payload.config.ts
Labels: bug

#355 Fix charterafrica footer
  apps/charterafrica/src/components/Footer/Footer.js
  apps/charterafrica/src/components/Footer/Footer.snap.js
  apps/charterafrica/src/components/Layout/Layout.snap.js
  apps/charterafrica/src/components/NewsletterSubscription/NewsletterSubscription.js
  apps/charterafrica/src/components/StayInTouch/StayInTouch.js
  apps/charterafrica/src/payload/globals/Footer.js
Labels: bug

#361 Fix main branch
  apps/charterafrica/payload.config.ts
Labels: chore

#362 charterafrica Privacy Policy page
  apps/charterafrica/.env.template
  apps/charterafrica/src/components/Articles/Articles.js
  apps/charterafrica/src/components/Articles/Articles.snap.js
  apps/charterafrica/src/components/Explainers/Explainer.js
  apps/charterafrica/src/components/FeaturedPostCard/FeaturedPostCard.js
  apps/charterafrica/src/components/FeaturedPostCard/FeaturedPostCard.snap.js
  apps/charterafrica/src/components/Hero/Hero.snap.js
  apps/charterafrica/src/components/Hero/Slide.js
  apps/charterafrica/src/components/LongForm/LongForm.js
  apps/charterafrica/src/components/LongForm/LongForm.snap.js
  apps/charterafrica/src/components/LongForm/LongForm.test.js
  apps/charterafrica/src/components/LongForm/index.js
  apps/charterafrica/src/components/LongFormRichText/LongFormRichText.js
  apps/charterafrica/src/components/LongFormRichText/LongFormRichText.snap.js
  apps/charterafrica/src/components/LongFormRichText/LongFormRichText.test.js
  apps/charterafrica/src/components/LongFormRichText/index.js
  apps/charterafrica/src/components/Mooc/Mooc.js
  apps/charterafrica/src/components/PageHeader/ImagePageHeader.js
  apps/charterafrica/src/components/PageHeader/LogoPageHeader.js
  apps/charterafrica/src/components/PageHeader/PageHeader.snap.js
  apps/charterafrica/src/lib/data/common/index.js
  apps/charterafrica/src/pages/[...slugs].page.js
  apps/charterafrica/src/payload/blocks/LongForm.js
  apps/charterafrica/src/payload/blocks/RichText.js
  apps/charterafrica/src/payload/collections/Pages.js
Labels: enhancement

#365 charterafrica single post pages
  apps/charterafrica/payload.config.ts
  apps/charterafrica/src/components/Articles/Articles.js
  apps/charterafrica/src/components/FeaturedPostCard/FeaturedPostCard.js
  apps/charterafrica/src/components/FeaturedPostCard/FeaturedPostCard.snap.js
  apps/charterafrica/src/components/Post/Post.js
  apps/charterafrica/src/components/Post/Post.snap.js
  apps/charterafrica/src/components/Post/Post.test.js
  apps/charterafrica/src/components/Post/index.js
  apps/charterafrica/src/lib/data/common/index.js
  apps/charterafrica/src/lib/data/local/index.js
  apps/charterafrica/src/lib/data/rest/index.js
  apps/charterafrica/src/pages/[...slugs].page.js
Labels: enhancement

#366 bump version to 0.0.29
  apps/charterafrica/contrib/dokku/Dockerfile
  apps/charterafrica/package.json
Labels: chore

#367 charterafrica individual grants/fellowship pages
  apps/charterafrica/next.config.js
  apps/charterafrica/payload.config.ts
  apps/charterafrica/src/components/Ecosystem/Ecosystem.js
  apps/charterafrica/src/components/Ecosystem/Ecosystem.snap.js
  apps/charterafrica/src/components/FeaturedPostCard/FeaturedPostCard.js
  apps/charterafrica/src/components/Footer/Footer.js
  apps/charterafrica/src/components/Footer/Footer.snap.js
  apps/charterafrica/src/components/Layout/Layout.snap.js
  apps/charterafrica/src/components/Opportunity/Opportunity.js
  apps/charterafrica/src/components/Opportunity/Opportunity.snap.js
  apps/charterafrica/src/components/Opportunity/Opportunity.test.js
  apps/charterafrica/src/components/Opportunity/index.js
  apps/charterafrica/src/components/OpportunityCards/OpportunityCardGrid.js
  apps/charterafrica/src/components/OpportunityCards/OpportunityCardGrid.snap.js
  apps/charterafrica/src/components/OpportunityCards/OpportunityCardHeader.js
  apps/charterafrica/src/components/OpportunityCards/OpportunityCardHeader.snap.js
  apps/charterafrica/src/components/OpportunityCards/OpportunityCards.js
  apps/charterafrica/src/components/OpportunityCards/OpportunityCards.snap.js
  apps/charterafrica/src/components/OpportunityPage/OpportunityPage.js
  apps/charterafrica/src/components/OpportunityPage/OpportunityPage.snap.js
  apps/charterafrica/src/components/Post/Post.js
  apps/charterafrica/src/lib/data/common/index.js
  apps/charterafrica/src/middleware.page.js
  apps/charterafrica/src/pages/[...slugs].page.js
  apps/charterafrica/src/payload/blocks/Opportunities.js
  apps/charterafrica/src/payload/collections/Events.js
  apps/charterafrica/src/payload/collections/Pages.js
Labels: enhancement

#374 :Make show less/more btn underlined
  apps/charterafrica/src/components/OpportunityCards/OpportunityCardHeader.js
  apps/charterafrica/src/components/OpportunityCards/OpportunityCardHeader.snap.js
  apps/charterafrica/src/components/OpportunityCards/OpportunityCards.snap.js
Labels: bug

#377 Make Explainers title not required
  apps/charterafrica/src/payload/collections/Explainers.js
Labels: enhancement

#384 Include Cape Verde in Focal Contries Map
  apps/charterafrica/public/data/features.json
  apps/charterafrica/src/components/FocalCountries/FocalCountries.js
  apps/charterafrica/src/components/FocalCountries/FocalCountries.snap.js
  apps/charterafrica/src/components/FocalCountries/Map.js
Labels: enhancement

#385 Enable Explainers title show/hide toggle
  apps/charterafrica/src/components/Explainers/Explainer.js
  apps/charterafrica/src/components/Explainers/Explainers.snap.js
  apps/charterafrica/src/payload/collections/Explainers.js
Labels: enhancement

#387 Enhancements
  apps/charterafrica/src/components/Articles/Articles.js
  apps/charterafrica/src/components/Articles/useArticles.js
  apps/charterafrica/src/components/useFilterQuery/index.js
  apps/charterafrica/src/components/useFilterQuery/useFilterQuery.js
  apps/charterafrica/src/lib/data/common/index.js
  apps/charterafrica/src/lib/data/local/index.js
  apps/charterafrica/src/pages/[...slugs].page.js
  apps/charterafrica/src/payload/blocks/Hero.js
  apps/charterafrica/src/utils/queryString.js
Labels: enhancement

#389 Release 0.0.35
  apps/charterafrica/contrib/dokku/Dockerfile
  apps/charterafrica/package.json
  apps/charterafrica/src/components/CommunityPlatforms/CommunityPlatforms.snap.js
  apps/charterafrica/src/components/Error/Error.snap.js
  apps/charterafrica/src/components/ErrorPage/ErrorPage.snap.js
  apps/charterafrica/src/components/Explainers/Explainers.snap.js
  apps/charterafrica/src/components/FeaturedPostCard/FeaturedPostCard.snap.js
  apps/charterafrica/src/components/Opportunity/Opportunity.snap.js
  apps/charterafrica/src/components/OpportunityCard/OpportunityCard.snap.js
  apps/charterafrica/src/components/RichText/RichText.snap.js
  apps/charterafrica/src/components/ShareThisPage/ShareThisPage.snap.js
  apps/charterafrica/src/components/SocialMediaBar/SocialMediaBar.snap.js
  apps/charterafrica/src/components/YoutubeVideoPlayer/YoutubeVideoPlayer.snap.js
  apps/codeforafrica/package.json
  apps/codeforafrica/src/components/ArticleGrid/ArticleGrid.snap.js
  apps/codeforafrica/src/components/ArticleHeader/ArticleHeader.snap.js
  apps/codeforafrica/src/components/ArticlePage/ArticlePage.snap.js
  apps/codeforafrica/src/components/Articles/Articles.snap.js
  apps/codeforafrica/src/components/Author/Author.snap.js
  apps/codeforafrica/src/components/ConnectBar/ConnectBar.snap.js
  apps/codeforafrica/src/components/FeaturedArticle/FeaturedArticle.snap.js
  apps/codeforafrica/src/components/FilterBar/FilterBar.snap.js
  apps/codeforafrica/src/components/GetInTouch/GetInTouch.snap.js
  apps/codeforafrica/src/components/GetInvolved/GetInvolved.snap.js
  apps/codeforafrica/src/components/MeetOurTeam/MeetOurTeam.snap.js
  apps/codeforafrica/src/components/NavBarNavList/NavBarNavList.snap.js
  apps/codeforafrica/src/components/NewsletterSubscription/NewsletterSubscription.snap.js
  apps/codeforafrica/src/components/Opportunities/Opportunities.snap.js
  apps/codeforafrica/src/components/OpportunityCard/OpportunityCard.snap.js
  apps/codeforafrica/src/components/OpportunityCardList/OpportunityCardList.snap.js
  apps/codeforafrica/src/components/OurTeam/OurTeam.snap.js
  apps/codeforafrica/src/components/ProjectCard/ProjectCard.snap.js
  apps/codeforafrica/src/components/ProjectDetails/ProjectDescription.snap.js
  apps/codeforafrica/src/components/ProjectDetails/ProjectDescriptionButton.snap.js
  apps/codeforafrica/src/components/ProjectDetails/ProjectDetails.snap.js
  apps/codeforafrica/src/components/ProjectDetails/ProjectStakeholders.snap.js
  apps/codeforafrica/src/components/ProjectPageHeader/ProjectPageHeader.snap.js
  apps/codeforafrica/src/components/ProjectTile/ProjectTile.snap.js
  apps/codeforafrica/src/components/ProjectTileList/ProjectTileList.snap.js
  apps/codeforafrica/src/components/Projects/Projects.snap.js
  apps/codeforafrica/src/components/ShareThisPage/ShareThisPage.snap.js
  apps/codeforafrica/src/components/SocialMediaBar/SocialMediaBar.snap.js
  apps/codeforafrica/src/components/SocialMediaButton/SocialMediaButton.snap.js
  apps/codeforafrica/src/components/SocialMediaButtonGroup/SocialMediaButtonGroup.snap.js
  apps/codeforafrica/src/components/TeamMembers/TeamMembers.snap.js
  apps/codeforafrica/src/pages/about/[unit]/index.snap.js
  apps/codeforafrica/src/pages/projects/[slug]/index.snap.js
  apps/pesayetu/package.json
  apps/pesayetu/src/pages/index.snap.js
  apps/promisetracker/package.json
  package.json
  packages/commons-ui-core/package.json
  packages/commons-ui-next/package.json
  packages/commons-ui-next/src/Link/Link.snap.js
  packages/commons-ui-testing-library/package.json
  packages/eslint-config-commons-ui/package.json
  packages/jest-config-commons-ui/package.json
  packages/playwright-config-commons-ui/package.json
  packages/storybook-config-commons-ui/package.json
  pnpm-lock.yaml
Labels: chore

#392 @/charterafrica optional grantees
  apps/charterafrica/src/lib/data/common/index.js
  apps/charterafrica/src/pages/[...slugs].page.js
  apps/charterafrica/src/pages/index.page.js
  apps/charterafrica/src/payload/blocks/Grantees.js
  apps/charterafrica/src/payload/collections/Pages.js
  apps/charterafrica/src/payload/utils/formatPagePath.js
Labels: chore, enhancement

#393 Fix charterafrica search & seo
  .github/workflows/charterafrica-deploy-prod.yml
  .prettierignore
  Dockerfile.charterafrica
  apps/charterafrica/contrib/dokku/Dockerfile
  apps/charterafrica/jest.setup.js
  apps/charterafrica/package.json
  apps/charterafrica/src/components/Articles/Articles.js
  apps/charterafrica/src/components/Articles/Articles.snap.js
  apps/charterafrica/src/components/Articles/ArticlesFilterBar.js
  apps/charterafrica/src/lib/data/common/index.js
Labels: bug, chore, enhancement

#395 Fix charterafrica articles pagination
  apps/charterafrica/contrib/dokku/Dockerfile
  apps/charterafrica/package.json
  apps/charterafrica/src/lib/data/common/index.js
Labels: bug

#396 Remove file extension
  apps/charterafrica/payload.config.ts
  apps/charterafrica/src/payload/blocks/ConsultationsMultimedia.js
  apps/charterafrica/src/payload/fields/youtubeSelect/styles.scss
  apps/charterafrica/src/payload/fields/youtubeSelect/youtubeSelect.js
Labels: bug

#397 Fix/update charterafrica prod cd
  .github/workflows/charterafrica-deploy-prod.yml
  apps/charterafrica/contrib/dokku/Dockerfile
  apps/charterafrica/package.json
Labels: chore

#401 charterafrica consultation tool
  apps/charterafrica/contrib/dokku/Dockerfile
  apps/charterafrica/package.json
  apps/charterafrica/src/components/Consultations/ConsultationList.js
  apps/charterafrica/src/components/Consultations/Consultations.js
  apps/charterafrica/src/components/Consultations/Consultations.snap.js
  apps/charterafrica/src/components/Documents/Documents.js
  apps/charterafrica/src/components/Documents/Documents.snap.js
  apps/charterafrica/src/lib/data/common/index.js
  apps/charterafrica/src/lib/youtube.js
  apps/charterafrica/src/pages/[...slugs].page.js
  apps/charterafrica/src/pages/api/v1/opportunities/consultation/[media].page.js
  apps/charterafrica/src/payload/blocks/ConsultationsMultimedia.js
  apps/charterafrica/src/payload/blocks/EmbeddedDocuments.js
  apps/charterafrica/src/payload/blocks/EmbeddedPlaylist.js
  apps/charterafrica/src/payload/collections/Pages.js
  apps/charterafrica/src/payload/fields/youtubeSelect/youtubeSelect.js
  apps/charterafrica/src/payload/utils/embeddedPlaylist.js
  apps/charterafrica/src/payload/utils/mapPlaylistLinkToId.js
  apps/charterafrica/src/theme/index.js
Labels: bug, chore, enhancement

#402 Fix charterafrica news/research page switch
  apps/charterafrica/contrib/dokku/Dockerfile
  apps/charterafrica/package.json
  apps/charterafrica/src/lib/data/common/index.js
Labels: bug
