Repository CodeForAfrica/ui, pull requests merged in 2023-05, with the labels that each got.

#422 Upgrade pnpm & node
  Dockerfile
  Dockerfile.charterafrica
  apps/charterafrica/package.json
  apps/codeforafrica/package.json
  apps/commons-ui-docs/package.json
  apps/pesayetu/package.json
  apps/promisetracker/package.json
  package.json
  pnpm-lock.yaml
Labels: chore, dependencies

#423 Upgrade turbo
  apps/charterafrica/package.json
  apps/charterafrica/turbo.json
  apps/codeforafrica/package.json
  apps/commons-ui-docs/package.json
  apps/commons-ui-docs/turbo.json
  apps/pesayetu/package.json
  apps/promisetracker/package.json
  packages/commons-ui-core/package.json
  packages/commons-ui-next/package.json
  packages/commons-ui-testing-library/package.json
  packages/eslint-config-commons-ui/package.json
  packages/jest-config-commons-ui/package.json
  packages/playwright-config-commons-ui/package.json
  pnpm-lock.yaml
  turbo.json
Labels: chore, dependencies

#433 Embed infographic into homepage
  .prettierignore
  apps/charterafrica/.eslintignore
  apps/charterafrica/public/infographic/asset-manifest.json
  apps/charterafrica/public/infographic/data/countries.json
  apps/charterafrica/public/infographic/data/data.json
  apps/charterafrica/public/infographic/data/map-details.json
  apps/charterafrica/public/infographic/data/map-disputed-areas.json
  apps/charterafrica/public/infographic/data/zolabo-map.json
  apps/charterafrica/public/infographic/embed.html
  apps/charterafrica/public/infographic/example.html
  apps/charterafrica/public/infographic/favicon.ico
  apps/charterafrica/public/infographic/index.html
  apps/charterafrica/public/infographic/logo192.png
  apps/charterafrica/public/infographic/logo512.png
  apps/charterafrica/public/infographic/manifest.json
  apps/charterafrica/public/infographic/robots.txt
  apps/charterafrica/public/infographic/run_time_config.js
  apps/charterafrica/public/infographic/static/css/bundle.css
  apps/charterafrica/public/infographic/static/css/bundle.css.map
  apps/charterafrica/public/infographic/static/css/main.439b6d89.css
  apps/charterafrica/public/infographic/static/css/main.439b6d89.css.map
  apps/charterafrica/public/infographic/static/js/787.2c40637b.chunk.js
  apps/charterafrica/public/infographic/static/js/787.2c40637b.chunk.js.map
  apps/charterafrica/public/infographic/static/js/bundle.js
  apps/charterafrica/public/infographic/static/js/bundle.js.map
  apps/charterafrica/public/infographic/static/js/main.015988d7.js
  apps/charterafrica/public/infographic/static/js/main.015988d7.js.LICENSE.txt
  apps/charterafrica/public/infographic/static/js/main.015988d7.js.map
  apps/charterafrica/public/infographic/static/media/bullet.374a84f3f32cd4156188.svg
  apps/charterafrica/public/infographic/static/media/chevron-down.ac65454ef255ce99088d.svg
  apps/charterafrica/public/infographic/static/media/chevron-left-outline.f62bbd8622a4a7324878e5dfa47ee795.svg
  apps/charterafrica/public/infographic/static/media/chevron-right-outline.3cc26dd8f37de07f9f37.svg
  apps/charterafrica/public/infographic/static/media/chevron-right-outline.3cc26dd8f37de07f9f37df6efd2edee5.svg
  apps/charterafrica/public/infographic/static/media/close-outline.2f83c18665dd37251d56.svg
  apps/charterafrica/public/infographic/static/media/diamond-mobile-green.ff3e6351884e6661b036.svg
  apps/charterafrica/public/infographic/static/media/diamond-mobile.e06ecf666d0af9d9625b.svg
  apps/charterafrica/public/infographic/static/media/eu.a4c0423749e33dea5b7f.png
  apps/charterafrica/public/infographic/static/media/logo-cpa.632cb779c4c1ac75429e2cb41822c1fb.svg
  apps/charterafrica/src/components/Infographic/Infographic.js
  apps/charterafrica/src/components/Infographic/Infographic.snap.js
  apps/charterafrica/src/components/Infographic/Infographic.test.js
  apps/charterafrica/src/components/Infographic/index.js
  apps/charterafrica/src/lib/data/common/processPageIndex.js
  apps/charterafrica/src/pages/index.page.js
  apps/charterafrica/src/payload/blocks/AgaInfographic.js
  apps/charterafrica/src/payload/collections/Pages.js
  package.json
Labels: enhancement

#432 Fix sourceAFRICA group label
  apps/charterafrica/src/payload/blocks/EmbeddedDocuments.js
Labels: bug
