Repository CodeForAfrica/ui, pull requests merged in 2023-07, with the labels that each got.

#481 catch exception when globals not set
  apps/charterafrica/src/lib/ecosystem/index.js
  apps/charterafrica/src/payload/globals/Ecosystem.js
Labels: bug

#488 Fix charterafrica i18n seo
  apps/charterafrica/src/lib/data/common/index.js
  apps/charterafrica/src/lib/data/seo.js
  apps/charterafrica/src/pages/_document.page.js
Labels: bug

#487 update app.json
  apps/charterafrica/app.json
Labels: bug

#496 Upgrade UI to node 18
  .github/workflows/charterafrica-deploy-dev.yml
  .github/workflows/charterafrica-deploy-prod.yml
  .github/workflows/ci.yml
  .github/workflows/codeforafrica-deploy-prod.yml
  .github/workflows/release-prod.yml
  Dockerfile
  Dockerfile.charterafrica
  apps/charterafrica/package.json
  apps/codeforafrica/package.json
  apps/commons-ui-docs/package.json
  apps/pesayetu/package.json
  apps/promisetracker/package.json
  pnpm-lock.yaml
Labels: chore

#479 bump package json & dockerfile to v0.0.48
  apps/charterafrica/contrib/dokku/Dockerfile
  apps/charterafrica/package.json
Labels: chore

#482 Add Google Analytics
  apps/codeforafrica/.env
  apps/codeforafrica/src/pages/_app.page.js
  turbo.json
Labels: chore

#498 Another round of small fixes
  apps/charterafrica/src/components/DesktopNavBar/DesktopNavBar.js
  apps/charterafrica/src/components/DesktopNavBar/DesktopNavBar.snap.js
  apps/charterafrica/src/components/DesktopNavBar/DesktopNavBar.test.js
  apps/charterafrica/src/components/Documents/Documents.js
  apps/charterafrica/src/components/Documents/Documents.test.js
  apps/charterafrica/src/components/Footer/Footer.js
  apps/charterafrica/src/components/Infographic/Infographic.js
  apps/charterafrica/src/components/Layout/Layout.snap.js
  apps/charterafrica/src/components/Logo/Logo.js
  apps/charterafrica/src/components/Logo/Logo.test.js
  apps/charterafrica/src/components/MobileNavBar/MobileNavBar.js
  apps/charterafrica/src/components/MobileNavBar/MobileNavBar.snap.js
  apps/charterafrica/src/components/NavBar/NavBar.snap.js
  apps/charterafrica/src/components/NavBar/NavBar.test.js
  apps/charterafrica/src/components/NavBarNavList/NavBarNavList.js
  apps/charterafrica/src/components/NewsletterSubscription/NewsletterSubscription.js
  apps/charterafrica/src/components/OrganisationCard/OrganisationCard.snap.js
  apps/charterafrica/src/components/OrganisationCard/OrganisationCard.test.js
  apps/charterafrica/src/components/ToolCard/ToolCard.snap.js
  apps/charterafrica/src/components/ToolCard/ToolCard.test.js
  apps/charterafrica/src/lib/data/common/index.js
  apps/charterafrica/src/lib/data/common/processPageAbout.js
  apps/charterafrica/src/lib/data/seo.js
  apps/charterafrica/src/payload/globals/Navigation.js
Labels: bug, enhancement

#486 Rename collection to item
  .github/workflows/dependabot_lint_format.yml
  apps/charterafrica/migrate-mongo-config.js
  apps/charterafrica/migrations/20230717085545-update_blocks_rename_collection_to_item.js
  apps/charterafrica/package.json
  apps/charterafrica/src/lib/data/common/processPageOpportunities.js
  apps/charterafrica/src/payload/blocks/Opportunities.js
  pnpm-lock.yaml
Labels: bug

#504 Setup codefoafrica cms
  apps/codeforafrica/env.template
  apps/codeforafrica/next-env.d.ts
  apps/codeforafrica/package.json
  apps/codeforafrica/payload.config.ts
  apps/codeforafrica/server.ts
  apps/codeforafrica/src/payload/collections/Media.js
  apps/codeforafrica/src/payload/collections/Pages.js
  apps/codeforafrica/src/payload/fields/fullTitle/index.js
  apps/codeforafrica/src/payload/fields/fullTitle/populateFullTitle.js
  apps/codeforafrica/src/payload/fields/slug/formatSlug.js
  apps/codeforafrica/src/payload/fields/slug/index.js
  apps/codeforafrica/src/payload/utils/formatDraftUrl.js
  apps/codeforafrica/src/payload/utils/formatPagePath.js
  apps/codeforafrica/tsconfig.json
  apps/codeforafrica/tsconfig.server.json
  apps/codeforafrica/turbo.json
  pnpm-lock.yaml
Labels: chore

#529 @/charterafrica Allow multiple spotlight blocks in a page
  apps/charterafrica/src/lib/data/common/processPageIndex.js
Labels: enhancement
