Repository CodeForAfrica/ui, pull requests merged in 2023-02, with the labels that each got.

#314 Fix CI/CD Pipeline
  .github/workflows/charterafrica-deploy-dev.yml
  .github/workflows/charterafrica-deploy-prod.yml
  Dockerfile.charterafrica
  apps/charterafrica/contrib/dokku/Dockerfile
  apps/charterafrica/package.json
Labels: bug, chore

#315 Add missing MONGO_URL env var
  .github/workflows/charterafrica-deploy-dev.yml
  .github/workflows/charterafrica-deploy-prod.yml
  Dockerfile.charterafrica
  apps/charterafrica/contrib/dokku/Dockerfile
  apps/charterafrica/package.json
Labels: bug, chore

#316 Clean up and document Dockerfile
  Dockerfile.charterafrica
  apps/charterafrica/contrib/dokku/Dockerfile
  apps/charterafrica/package.json
Labels: chore

#325 add payload CORS config
  apps/charterafrica/.env.template
  apps/charterafrica/payload.config.js
  turbo.json
Labels: bug, chore

#324 @charterafrica SEO
  apps/charterafrica/.env
  apps/charterafrica/jest.setup.js
  apps/charterafrica/public/images/Rectangle 113.jpg
  apps/charterafrica/src/components/Articles/Articles.js
  apps/charterafrica/src/components/Articles/Articles.snap.js
  apps/charterafrica/src/components/Ecosystem/Ecosystem.snap.js
  apps/charterafrica/src/components/Explainers/Explainers.test.js
  apps/charterafrica/src/components/LineClampedRichTypography/LineClampedRichTypography.js
  apps/charterafrica/src/components/PostCard/PostCard.js
  apps/charterafrica/src/components/PostCard/PostCard.snap.js
  apps/charterafrica/src/components/PostCard/PostCard.test.js
  apps/charterafrica/src/components/PostCard/index.js
  apps/charterafrica/src/lib/README.md
  apps/charterafrica/src/lib/data/index.js
  apps/charterafrica/src/lib/data/seo.js
  apps/charterafrica/src/next-seo.config.js
  apps/charterafrica/src/pages/index.page.js
  apps/charterafrica/src/pages/knowledge/[slug].page.js
  apps/charterafrica/src/pages/opportunities/[slug].page.js
  apps/charterafrica/src/theme/index.js
  apps/charterafrica/src/utils/getGlobalProps.js
  apps/charterafrica/src/utils/site.js
  turbo.json
Labels: enhancement

#327 Admin Fixes
  apps/charterafrica/next.config.js
  apps/charterafrica/package.json
  apps/charterafrica/server.js
  apps/charterafrica/src/components/Hero/Hero.snap.js
  apps/charterafrica/src/components/Layout/Layout.snap.js
  apps/charterafrica/src/components/Mooc/Mooc.js
  apps/charterafrica/src/components/NavBar/NavBar.snap.js
  apps/charterafrica/src/components/Partners/PartnerGrid.js
  apps/charterafrica/src/components/Partners/Partners.js
  apps/charterafrica/src/components/Partners/Partnership.js
  apps/charterafrica/src/components/PostCard/PostCard.js
  apps/charterafrica/src/components/PostCard/PostCard.snap.js
  apps/charterafrica/src/components/PostCard/PostCard.test.js
  apps/charterafrica/src/components/Resources/Resources.js
  apps/charterafrica/src/components/Resources/Resources.snap.js
  apps/charterafrica/src/components/RichText/RichText.js
  apps/charterafrica/src/lib/gtag.js
  apps/charterafrica/src/pages/_app.page.js
  apps/charterafrica/src/pages/_document.page.js
  apps/charterafrica/src/payload/collections/Partners.js
  apps/charterafrica/src/payload/fields/richText.js
  apps/charterafrica/src/payload/globals/FocalCountries.js
  apps/charterafrica/src/payload/globals/Footer.js
  apps/charterafrica/src/payload/globals/Navigation.js
  apps/charterafrica/src/payload/utils/formatPagePath.js
  apps/charterafrica/src/theme/index.js
  apps/codeforafrica/package.json
  apps/pesayetu/package.json
  apps/promisetracker/package.json
  package.json
  packages/commons-ui-core/package.json
  packages/commons-ui-next/package.json
  packages/commons-ui-testing-library/package.json
  packages/eslint-config-commons-ui/package.json
  packages/jest-config-commons-ui/package.json
  packages/playwright-config-commons-ui/package.json
  packages/storybook-config-commons-ui/package.json
  pnpm-lock.yaml
  turbo.json
Labels: bug, chore, enhancement

#328 Add payload config transpilation
  .gitignore
  apps/charterafrica/.env.template
  apps/charterafrica/.eslintignore
  apps/charterafrica/next-env.d.ts
  apps/charterafrica/package.json
  apps/charterafrica/payload.config.ts
  apps/charterafrica/scripts/dev.js
  apps/charterafrica/server.js
  apps/charterafrica/server.ts
  apps/charterafrica/src/components/Explainers/Explainer.js
  apps/charterafrica/src/components/Hero/Slide.js
  apps/charterafrica/src/payload/utils/colors.js
  apps/charterafrica/tsconfig.json
  apps/charterafrica/tsconfig.server.json
  apps/codeforafrica/package.json
  apps/pesayetu/package.json
  apps/promisetracker/package.json
  package.json
  packages/commons-ui-core/package.json
  packages/commons-ui-next/package.json
  packages/commons-ui-testing-library/package.json
  packages/eslint-config-commons-ui/package.json
  packages/jest-config-commons-ui/package.json
  packages/playwright-config-commons-ui/package.json
  packages/storybook-config-commons-ui/package.json
  pnpm-lock.yaml
  turbo.json
Labels: bug, chore

#329 Fix charterafrica build
  .github/workflows/charterafrica-deploy-dev.yml
  Dockerfile.charterafrica
Labels: chore

#330 Address more feedback
  apps/charterafrica/src/components/Ecosystem/Chart.js
  apps/charterafrica/src/components/Ecosystem/Ecosystem.js
  apps/charterafrica/src/components/Ecosystem/Ecosystem.snap.js
  apps/charterafrica/src/components/Ecosystem/Key.js
  apps/charterafrica/src/components/FocalCountries/FocalCountries.js
  apps/charterafrica/src/components/FocalCountries/FocalCountries.snap.js
  apps/charterafrica/src/components/Hero/Hero.snap.js
  apps/charterafrica/src/components/Hero/Slide.js
  apps/charterafrica/src/payload/blocks/Ecosystem.js
  apps/charterafrica/src/payload/blocks/Spotlight.js
Labels: bug

#331 Fix admin feedback
  apps/charterafrica/src/components/Explainers/Explainer.js
  apps/charterafrica/src/components/Explainers/Explainers.js
  apps/charterafrica/src/components/Explainers/Explainers.snap.js
  apps/charterafrica/src/components/Hero/Hero.snap.js
  apps/charterafrica/src/components/Hero/Slide.js
  apps/charterafrica/src/lib/data/index.js
  apps/charterafrica/src/pages/index.page.js
Labels: bug

#333 @charterafrica about page
  apps/charterafrica/src/assets/icons/Type=arrow-right-circle, Size=24, Color=CurrentColor.svg
  apps/charterafrica/src/assets/icons/Type=plus, Size=24, Color=CurrentColor.svg
  apps/charterafrica/src/components/Accordion/Accordion.js
  apps/charterafrica/src/components/Accordion/Accordion.snap.js
  apps/charterafrica/src/components/Accordion/Accordion.test.js
  apps/charterafrica/src/components/Accordion/index.js
  apps/charterafrica/src/components/FAQ/FAQ.js
  apps/charterafrica/src/components/FAQ/FAQ.snap.js
  apps/charterafrica/src/components/FAQ/FAQ.test.js
  apps/charterafrica/src/components/FAQ/index.js
  apps/charterafrica/src/components/GuidingPrinciples/GuidingPrinciples.js
  apps/charterafrica/src/components/GuidingPrinciples/GuidingPrinciples.snap.js
  apps/charterafrica/src/components/GuidingPrinciples/GuidingPrinciples.test.js
  apps/charterafrica/src/components/GuidingPrinciples/index.js
  apps/charterafrica/src/components/Helpdesk/Helpdesk.js
  apps/charterafrica/src/components/PageDescription/PageDescription.js
  apps/charterafrica/src/components/PageDescription/PageDescription.snap.js
  apps/charterafrica/src/components/PageDescription/PageDescription.test.js
  apps/charterafrica/src/components/PageDescription/index.js
  apps/charterafrica/src/components/PageHeader/PageHeader.js
  apps/charterafrica/src/components/PageHeader/PageHeader.snap.js
  apps/charterafrica/src/components/PageHeader/PageHeader.test.js
  apps/charterafrica/src/components/PageHeader/index.js
  apps/charterafrica/src/components/RichText/RichText.js
  apps/charterafrica/src/lib/data/common/index.js
  apps/charterafrica/src/lib/data/local/index.js
  apps/charterafrica/src/lib/data/rest/index.js
  apps/charterafrica/src/middleware.page.js
  apps/charterafrica/src/pages/404.page.js
  apps/charterafrica/src/pages/500.page.js
  apps/charterafrica/src/pages/[...slugs].page.js
  apps/charterafrica/src/pages/[...slugs].snap.js
  apps/charterafrica/src/pages/[...slugs].spec.js
  apps/charterafrica/src/pages/[...slugs].test.js
  apps/charterafrica/src/pages/_error.page.js
  apps/charterafrica/src/pages/index.spec.js
  apps/charterafrica/src/payload/blocks/FAQ.js
  apps/charterafrica/src/payload/blocks/Global.js
  apps/charterafrica/src/payload/blocks/GuidingPrinciples.js
  apps/charterafrica/src/payload/blocks/Hero.js
  apps/charterafrica/src/payload/blocks/PageDescription.js
  apps/charterafrica/src/payload/blocks/PageHeader.js
  apps/charterafrica/src/payload/blocks/Partners.js
  apps/charterafrica/src/payload/blocks/Resources.js
  apps/charterafrica/src/payload/collections/Pages.js
  apps/charterafrica/src/payload/fields/accordion.js
  apps/charterafrica/src/payload/fields/link.js
  apps/charterafrica/src/payload/globals/Navigation.js
Labels: enhancement

#342 Fix @charterafrica middleware
  apps/charterafrica/.env.template
  apps/charterafrica/server.ts
  apps/charterafrica/src/middleware.page.js
  apps/charterafrica/src/utils/strings.js
  turbo.json
Labels: bug

#341 @charterafrica Community page
  apps/charterafrica/payload.config.ts
  apps/charterafrica/src/components/CommunityPlatforms/CommunityPlatform.js
  apps/charterafrica/src/components/CommunityPlatforms/CommunityPlatforms.js
  apps/charterafrica/src/components/CommunityPlatforms/CommunityPlatforms.snap.js
  apps/charterafrica/src/components/CommunityPlatforms/CommunityPlatforms.test.js
  apps/charterafrica/src/components/CommunityPlatforms/index.js
  apps/charterafrica/src/components/Helpdesk/Helpdesk.js
  apps/charterafrica/src/components/Helpdesk/Helpdesk.snap.js
  apps/charterafrica/src/lib/data/common/index.js
  apps/charterafrica/src/pages/[...slugs].page.js
  apps/charterafrica/src/payload/blocks/CommunityPlatforms.js
  apps/charterafrica/src/payload/collections/CommunityPlatforms.js
  apps/charterafrica/src/payload/collections/Pages.js
Labels: enhancement

#344 (Re) Enable @charterafrica Spotlight category
  apps/charterafrica/src/components/Ecosystem/Ecosystem.js
  apps/charterafrica/src/components/Spotlight/Spotlight.js
  apps/charterafrica/src/payload/blocks/Spotlight.js
Labels: enhancement

#349 (Temp) Fix charterafrica creating new CMS pages
  apps/charterafrica/contrib/dokku/Dockerfile
  apps/charterafrica/package.json
  apps/charterafrica/payload.config.ts
  apps/codeforafrica/package.json
  apps/pesayetu/package.json
  apps/promisetracker/package.json
  package.json
  packages/commons-ui-core/package.json
  packages/commons-ui-next/package.json
  packages/commons-ui-testing-library/package.json
  packages/eslint-config-commons-ui/package.json
  packages/jest-config-commons-ui/package.json
  packages/playwright-config-commons-ui/package.json
  packages/storybook-config-commons-ui/package.json
  pnpm-lock.yaml
Labels: bug

#350 Fix charterafrica build process
  Dockerfile.charterafrica
  apps/charterafrica/contrib/dokku/Dockerfile
  apps/charterafrica/package.json
  apps/charterafrica/payload.config.ts
  apps/charterafrica/server.ts
  apps/codeforafrica/package.json
  apps/pesayetu/package.json
  apps/promisetracker/package.json
  package.json
  packages/commons-ui-core/package.json
  packages/commons-ui-next/package.json
  packages/commons-ui-testing-library/package.json
  packages/eslint-config-commons-ui/package.json
  packages/jest-config-commons-ui/package.json
  packages/playwright-config-commons-ui/package.json
  packages/storybook-config-commons-ui/package.json
  pnpm-lock.yaml
  turbo.json
Labels: bug, chore

#351 bump version & update staging CD
  .github/workflows/charterafrica-deploy-prod.yml
  apps/charterafrica/contrib/dokku/Dockerfile
  apps/charterafrica/package.json
Labels: chore
