Repository CodeForAfrica/ui, pull requests merged in 2023-04, with the labels that each got.

#403 charterafrica articles/documents pagination ux
  apps/charterafrica/src/components/Articles/Articles.js
  apps/charterafrica/src/components/Articles/Articles.snap.js
  apps/charterafrica/src/components/Articles/useArticles.js
  apps/charterafrica/src/components/Documents/DocumentCard.js
  apps/charterafrica/src/components/Documents/Documents.js
  apps/charterafrica/src/components/Documents/Documents.snap.js
  apps/charterafrica/src/components/Documents/useDocuments.js
  apps/charterafrica/src/lib/data/common/index.js
  apps/charterafrica/src/lib/sourceAfrica.js
  apps/charterafrica/src/utils/articles/queryString.js
  apps/charterafrica/src/utils/documents/queryString.js
Labels: enhancement

#405 Refactor common/index
  apps/charterafrica/src/lib/data/common/index.js
  apps/charterafrica/src/lib/data/common/processPageAbout.js
  apps/charterafrica/src/lib/data/common/processPageArticles.js
  apps/charterafrica/src/lib/data/common/processPageConsultation.js
  apps/charterafrica/src/lib/data/common/processPageExplainers.js
  apps/charterafrica/src/lib/data/common/processPageIndex.js
  apps/charterafrica/src/lib/data/common/processPageOpportunities.js
  apps/charterafrica/src/lib/data/common/processPagePrivacyPolicy.js
  apps/charterafrica/src/lib/data/local/index.js
Labels: chore

#406 Fix Video description
  apps/charterafrica/src/lib/data/common/processPageConsultation.js
Labels: bug

#407 Fix charterafrica tests and release
  apps/charterafrica/contrib/dokku/Dockerfile
  apps/charterafrica/package.json
  apps/charterafrica/src/components/Articles/Articles.test.js
  apps/charterafrica/src/components/FocalCountries/FocalCountries.test.js
  apps/charterafrica/src/components/Grantees/Grantees.test.js
  apps/charterafrica/src/components/OpportunityPage/OpportunityPage.js
  apps/charterafrica/src/components/OpportunityPage/OpportunityPage.snap.js
  apps/charterafrica/src/components/OpportunityPage/OpportunityPage.test.js
  packages/commons-ui-testing-library/package.json
  pnpm-lock.yaml
Labels: bug, chore
