Repository CodeForAfrica/ui, pull requests merged in 2023-06, with the labels that each got.

#430 Add CMS for Github integration
  apps/charterafrica/payload.config.ts
  apps/charterafrica/src/lib/data/json/countries.js
  apps/charterafrica/src/lib/ecosystem/models.js
  apps/charterafrica/src/lib/openAfrica.js
  apps/charterafrica/src/payload/collections/Contributors.js
  apps/charterafrica/src/payload/collections/Organisations.js
  apps/charterafrica/src/payload/collections/Tools.js
  apps/charterafrica/src/payload/fields/dateField.js
  apps/charterafrica/src/payload/fields/slug/formatSlug.js
  apps/charterafrica/src/payload/fields/source.js
  apps/charterafrica/src/payload/fields/supporter.js
Labels: enhancement

#454 @charterafrica page preview
  apps/charterafrica/src/pages/api/v1/draft/index.page.js
  apps/charterafrica/src/payload/collections/Pages.js
  apps/charterafrica/src/payload/utils/formatDraftUrl.js
  apps/charterafrica/src/payload/utils/formatPagePath.js
Labels: enhancement

#460 @/charterafrica Move all documents API queries to /resources
  apps/charterafrica/src/components/Documents/useDocuments.js
  apps/charterafrica/src/lib/data/common/processPageConsultation.js
  apps/charterafrica/src/lib/data/common/processPageDatasets.js
  apps/charterafrica/src/lib/data/common/processPageDocuments.js
  apps/charterafrica/src/pages/api/v1/opportunities/consultation/[media].page.js
  apps/charterafrica/src/pages/api/v1/resources/[type].page.js
  apps/charterafrica/src/pages/api/v1/resources/datasets.page.js
Labels: chore

#461 @/charterafrica reuse page
  apps/charterafrica/src/lib/data/common/index.js
  apps/charterafrica/src/lib/data/common/processPageExplainers.js
  apps/charterafrica/src/pages/[...slugs].page.js
  apps/charterafrica/src/pages/index.page.js
Labels: chore

#465 Fetch documents by locale
  apps/charterafrica/src/lib/data/common/processPageConsultation.js
  apps/charterafrica/src/lib/data/common/processPageDocuments.js
Labels: enhancement

#472 @/charterafrica Reduce navigation data
  apps/charterafrica/src/components/NavBarDropdown/NavBarDropdown.js
  apps/charterafrica/src/lib/data/common/index.js
Labels: bug
