Repository CodeForAfrica/ui, pull requests merged in 2023-08, with the labels that each got.

#543 @/charterafrica v0.1.0
  apps/charterafrica/contrib/dokku/Dockerfile
  apps/charterafrica/package.json
  pnpm-lock.yaml
Labels: chore

#545 Redirect `/resources` to `/resources/datasets`
  apps/charterafrica/next.config.js
  apps/charterafrica/src/middleware.page.js
Labels: enhancement

#546 @/charterafrica Hide opportunities if empty
  apps/charterafrica/src/components/OpportunityPage/OpportunityPage.js
Labels: enhancement

#547 Bump payload to 1.11.8
  apps/charterafrica/package.json
  pnpm-lock.yaml
Labels: bug, dependencies

#549 Fix Charterafrica issues
  apps/charterafrica/src/components/Infographic/Infographic.js
  apps/charterafrica/src/components/Tool/Contributors.js
  apps/charterafrica/src/components/Tool/OrgThemeAndOperatingCountries.js
  apps/charterafrica/src/components/Tool/Tool.snap.js
  apps/charterafrica/src/lib/data/common/processPageIndex.js
  apps/charterafrica/src/lib/data/common/processPageTools.js
  apps/charterafrica/src/lib/ecosystem/airtable/processData.js
Labels: bug

#552 Fix Charter Africa issues
  apps/charterafrica/contrib/dokku/Dockerfile
  apps/charterafrica/package.json
  apps/charterafrica/src/lib/data/common/processPageContributors.js
  apps/charterafrica/src/lib/ecosystem/ecosystem/processData.js
  apps/charterafrica/src/lib/ecosystem/index.js
  apps/charterafrica/src/pages/api/v1/resources/ecosystem/[action].page.js
Labels: bug

#558 @charterafrica Datasets fix
  apps/charterafrica/src/components/Dataset/Dataset.js
  apps/charterafrica/src/components/Dataset/Dataset.snap.js
  apps/charterafrica/src/components/DatasetCard/DatasetCard.js
  apps/charterafrica/src/components/DatasetCard/DatasetCard.snap.js
Labels: bug

#555 Refactor page links to use field hooks
  apps/charterafrica/src/lib/data/common/getPageUrl.js
  apps/charterafrica/src/lib/data/common/processPageContributors.js
  apps/charterafrica/src/lib/data/common/processPageOrganisations.js
  apps/charterafrica/src/lib/data/common/processPageTools.js
  apps/charterafrica/src/payload/collections/Contributors.js
  apps/charterafrica/src/payload/collections/Organisations.js
  apps/charterafrica/src/payload/collections/Tools.js
  apps/charterafrica/src/payload/utils/findAndFormatPagePath.js
  apps/charterafrica/src/payload/utils/nestCollectionUnderPage.js
Labels: chore
