Repository CodeForAfrica/ui, pull requests merged in 2024-08, with the labels that each got.

#789 Introduce @hurumap/next/Map
  apps/charterafrica/package.json
  apps/climatemappedafrica/package.json
  apps/climatemappedafrica/src/components/ExplorePage/index.js
  apps/climatemappedafrica/src/components/ExplorePage/useStyles.js
  apps/climatemappedafrica/src/components/HURUmap/Map/index.stories.js
  apps/climatemappedafrica/src/lib/hurumap/index.js
  apps/codeforafrica/package.json
  apps/pesayetu/package.json
  apps/pesayetu/src/components/ExplorePage/index.js
  apps/pesayetu/src/components/ExplorePage/useStyles.js
  apps/pesayetu/src/components/HURUmap/Map/Layers.js
  apps/pesayetu/src/components/HURUmap/Map/index.js
  apps/pesayetu/src/components/HURUmap/Map/index.stories.js
  apps/pesayetu/src/lib/hurumap/index.js
  apps/promisetracker/package.json
  apps/promisetracker/src/components/Promises/index.js
  apps/roboshield/package.json
  apps/uibook/jsconfig.json
  apps/uibook/package.json
  apps/uibook/stories/hurumap/core/Action.stories.js
  apps/uibook/stories/hurumap/core/ChartTooltip.stories.js
  apps/uibook/stories/hurumap/core/Location.stories.js
  apps/uibook/stories/hurumap/core/LocationHighlight.stories.js
  apps/uibook/stories/hurumap/core/LocationTag.stories.js
  apps/uibook/stories/hurumap/core/Share.stories.js
  apps/uibook/stories/hurumap/core/ShareButton.stories.js
  apps/uibook/stories/hurumap/next/Map.stories.js
  apps/uibook/stories/hurumap/next/Source.stories.js
  apps/uibook/stories/hurumap/next/ke.json
  apps/vpnmanager/package.json
  package.json
  packages/commons-ui-core/package.json
  packages/commons-ui-next/package.json
  packages/commons-ui-testing-library/package.json
  packages/eslint-config-commons-ui/index.js
  packages/eslint-config-commons-ui/package.json
  packages/hurumap-core/README.md
  packages/hurumap-core/jest.setup.js
  packages/hurumap-core/package.json
  packages/hurumap-core/src/LocationHighlight/LocationHighlight.js
  packages/hurumap-core/src/Scope/BarChartScope.js
  packages/hurumap-core/src/index.js
  packages/hurumap-next/.eslintrc.js
  packages/hurumap-next/README.md
  packages/hurumap-next/jest.setup.js
  packages/hurumap-next/package.json
  packages/hurumap-next/src/Map/Layers.js
  packages/hurumap-next/src/Map/LazyMap.js
  packages/hurumap-next/src/Map/Map.js
  packages/hurumap-next/src/Map/geoStyles.js
  packages/hurumap-next/src/Map/index.js
  packages/hurumap-next/src/index.js
  packages/jest-config-commons-ui/package.json
  packages/playwright-config-commons-ui/package.json
  pnpm-lock.yaml
Labels: enhancement

#811 @/roboshield Fix PROD workflow
  .github/workflows/charterafrica-deploy-dev.yml
  .github/workflows/charterafrica-deploy-prod.yml
  .github/workflows/ci.yml
  .github/workflows/climatemappedafrica-deploy-dev.yml
  .github/workflows/codeforafrica-deploy-dev.yml
  .github/workflows/codeforafrica-deploy-prod.yml
  .github/workflows/codeforafrica-deploy-review-app.yml
  .github/workflows/dependabot_lint_format.yml
  .github/workflows/pesayetu-deploy-dev.yml
  .github/workflows/release-prod.yml
  .github/workflows/roboshield-deploy-dev.yml
  .github/workflows/roboshield-deploy-prod.yml
  .github/workflows/vpnmanager-deploy-dev.yml
  Dockerfile
  package.json
Labels: chore, dependencies, docker

#816 @/roboshield Google Analytics
  apps/roboshield/package.json
Labels: chore, dependencies

#817 @/roboshield Fix Dokku Deployment
  .github/workflows/roboshield-deploy-prod.yml
  apps/roboshield/package.json
Labels: chore

#820 @hurumap/TreemapChart
  apps/climatemappedafrica/src/components/HURUmap/Chart/TreemapChartScope.js
  apps/climatemappedafrica/src/components/HURUmap/Chart/configureScope.js
  apps/pesayetu/src/components/HURUmap/Chart/configureScope.js
  packages/hurumap-core/src/Scope/TreemapChartScope.js
  packages/hurumap-core/src/Scope/index.js
Labels: enhancement

#829 @/civicsignalblog MONGO_URL
  .github/workflows/civicsignalblog-deploy-prod.yml
  apps/civicsignalblog/contrib/dokku/Dockerfile
  apps/civicsignalblog/package.json
Labels: bug

#833 @/civicsignalblog normal preview
  apps/civicsignalblog/.env
  apps/civicsignalblog/contrib/dokku/Dockerfile
  apps/civicsignalblog/package.json
  apps/civicsignalblog/payload.config.ts
  apps/civicsignalblog/server.ts
  apps/civicsignalblog/src/lib/data/utils/posts.js
  apps/civicsignalblog/src/payload/collections/Posts.js
Labels: enhancement

#837 @/civicsignalblog longform link font
  apps/civicsignalblog/contrib/dokku/Dockerfile
  apps/civicsignalblog/package.json
  apps/civicsignalblog/src/components/CMSContent/CMSContent.snap.js
  apps/civicsignalblog/src/components/LongFormRichText/LongFormRichText.js
  apps/civicsignalblog/src/components/LongFormRichText/LongFormRichText.snap.js
  apps/civicsignalblog/src/components/RichText/RichText.js
  apps/civicsignalblog/src/components/RichText/RichText.snap.js
Labels: bug

#838 @/ui Move tags to the bottom of an article
  apps/civicsignalblog/contrib/dokku/Dockerfile
  apps/civicsignalblog/package.json
  apps/civicsignalblog/src/components/ArticleHeader/ArticleHeader.js
  apps/civicsignalblog/src/components/ArticlePage/ArticlePage.js
  apps/civicsignalblog/src/components/ArticlePage/ArticlePage.snap.js
  apps/codeforafrica/contrib/dokku/Dockerfile
  apps/codeforafrica/package.json
  apps/codeforafrica/src/components/ArticleHeader/ArticleHeader.js
  apps/codeforafrica/src/components/ArticlePage/ArticlePage.js
  apps/codeforafrica/src/components/ArticlePage/ArticlePage.snap.js
Labels: enhancement

#841 @/roboshild CMS Improvements
  Dockerfile
  apps/climatemappedafrica/.env.template
  apps/climatemappedafrica/src/lib/ga/index.js
  apps/climatemappedafrica/src/pages/_document.js
  apps/climatemappedafrica/turbo.json
  apps/pesayetu/.env.template
  apps/pesayetu/src/lib/ga/index.js
  apps/pesayetu/src/pages/_document.js
  apps/pesayetu/turbo.json
  apps/roboshield/package.json
  apps/roboshield/payload-types.ts
  apps/roboshield/payload.config.ts
  apps/roboshield/src/components/BlockRenderer/BlockRenderer.tsx
  apps/roboshield/src/components/Finish/Finish.tsx
  apps/roboshield/src/components/Page/Page.tsx
  apps/roboshield/src/lib/config.ts
  apps/roboshield/src/lib/data/common/index.ts
  apps/roboshield/src/lib/data/seo.ts
  apps/roboshield/src/lib/payload/index.ts
  apps/roboshield/src/lib/robots.ts
  apps/roboshield/src/next-seo.config.js
  apps/roboshield/src/pages/_app.tsx
  apps/roboshield/src/payload/globals/Site/EngagementTab.ts
  apps/roboshield/src/utils/site.ts
  packages/commons-ui-next/src/Link/Link.js
  pnpm-lock.yaml
  turbo.json
Labels: bug

#855 @/civicsignalblog SEO
  apps/civicsignalblog/.env
  apps/civicsignalblog/contrib/dokku/Dockerfile
  apps/civicsignalblog/package.json
  apps/civicsignalblog/payload.config.ts
  apps/civicsignalblog/public/android-chrome-192x192.png
  apps/civicsignalblog/public/android-chrome-512x512.png
  apps/civicsignalblog/public/apple-touch-icon.png
  apps/civicsignalblog/public/favicon-16x16.png
  apps/civicsignalblog/public/favicon-32x32.png
  apps/civicsignalblog/public/favicon.ico
  apps/civicsignalblog/public/image.jpg
  apps/civicsignalblog/public/mstile-150x150.png
  apps/civicsignalblog/public/robots.txt
  apps/civicsignalblog/public/safari-pinned-tab.svg
  apps/civicsignalblog/public/site.webmanifest
  apps/civicsignalblog/src/components/ArticleCard/ArticleCard.snap.js
  apps/civicsignalblog/src/components/ArticleGrid/ArticleGrid.snap.js
  apps/civicsignalblog/src/components/ArticlePage/ArticlePage.js
  apps/civicsignalblog/src/components/ArticlePage/ArticlePage.snap.js
  apps/civicsignalblog/src/components/Articles/Articles.snap.js
  apps/civicsignalblog/src/components/Author/Author.snap.js
  apps/civicsignalblog/src/components/ChoiceChip/ChoiceChip.snap.js
  apps/civicsignalblog/src/components/ChoiceChipGroup/ChoiceChipGroup.snap.js
  apps/civicsignalblog/src/components/FeaturedArticle/FeaturedArticle.js
  apps/civicsignalblog/src/components/FeaturedArticle/FeaturedArticle.snap.js
  apps/civicsignalblog/src/components/FilterBar/FilterBar.snap.js
  apps/civicsignalblog/src/components/MobileNavBar/MobileNavBar.js
  apps/civicsignalblog/src/components/NavBar/NavBar.js
  apps/civicsignalblog/src/components/NavBar/NavBar.snap.js
  apps/civicsignalblog/src/components/Page/Page.js
  apps/civicsignalblog/src/components/PageHeader/PageHeader.snap.js
  apps/civicsignalblog/src/components/RelatedStories/RelatedStories.snap.js
  apps/civicsignalblog/src/components/SearchInput/SearchInput.snap.js
  apps/civicsignalblog/src/components/TwoToneBackground/TwoToneBackground.snap.js
  apps/civicsignalblog/src/lib/data/common/index.js
  apps/civicsignalblog/src/lib/data/seo.js
  apps/civicsignalblog/src/lib/data/utils/posts.js
  apps/civicsignalblog/src/next-seo.config.js
  apps/civicsignalblog/src/pages/_app.page.js
  apps/civicsignalblog/src/payload/collections/Pages.js
  apps/civicsignalblog/src/payload/collections/Posts.js
  apps/civicsignalblog/src/payload/globals/Site/EngagementTab.js
  apps/civicsignalblog/src/theme/index.js
  apps/civicsignalblog/src/utils/site.js
  apps/codeforafrica/src/components/Articles/Articles.snap.js
  apps/codeforafrica/src/components/FeaturedArticle/FeaturedArticle.js
  apps/codeforafrica/src/components/FeaturedArticle/FeaturedArticle.snap.js
  apps/roboshield/package.json
  apps/roboshield/payload-types.ts
  apps/roboshield/payload.config.ts
  apps/roboshield/public/robots.txt
  apps/roboshield/src/lib/data/common/index.ts
  apps/roboshield/src/lib/data/seo.ts
  apps/roboshield/src/payload/collections/Pages.ts
  pnpm-lock.yaml
Labels: bug, enhancement

#856 [Hotfix] @/civisignalblog analytics
  apps/civicsignalblog/contrib/dokku/Dockerfile
  apps/civicsignalblog/package.json
  apps/civicsignalblog/src/lib/data/common/index.js
Labels: bug

#857 [Hotfix] SEO title template
  apps/civicsignalblog/contrib/dokku/Dockerfile
  apps/civicsignalblog/package.json
  apps/civicsignalblog/src/lib/data/seo.js
  apps/roboshield/package.json
  apps/roboshield/public/image.jpg
  apps/roboshield/src/lib/data/seo.ts
Labels: bug

#858 [Hotfix] @/roboshield Add missing favicons
  apps/civicsignalblog/src/pages/_document.page.js
  apps/roboshield/package.json
  apps/roboshield/public/android-chrome-192x192.png
  apps/roboshield/public/android-chrome-512x512.png
  apps/roboshield/public/apple-touch-icon.png
  apps/roboshield/public/browserconfig.xml
  apps/roboshield/public/favicon-16x16.png
  apps/roboshield/public/favicon-32x32.png
  apps/roboshield/public/mstile-150x150.png
  apps/roboshield/public/safari-pinned-tab.svg
  apps/roboshield/public/site.webmanifest
  apps/roboshield/src/pages/_document.tsx
Labels: bug

#864 @/climatemappedafrica - chore: remove defaultProps in functional components
  apps/climatemappedafrica/src/components/DropdownSearch/index.js
  apps/climatemappedafrica/src/components/ExplorePage/index.js
  apps/climatemappedafrica/src/components/HURUmap/CategoryHeader/index.js
  apps/climatemappedafrica/src/components/HURUmap/Chart/Filters.js
  apps/climatemappedafrica/src/components/HURUmap/ChartFilter/index.js
  apps/climatemappedafrica/src/components/HURUmap/KeyMetric/index.js
  apps/climatemappedafrica/src/components/HURUmap/LocationHeader/index.js
  apps/climatemappedafrica/src/components/HURUmap/Panel/DesktopPanel/PanelButtons.js
  apps/climatemappedafrica/src/components/HURUmap/Panel/DesktopPanel/PanelItem.js
  apps/climatemappedafrica/src/components/HURUmap/Panel/DesktopPanel/RichData.js
  apps/climatemappedafrica/src/components/HURUmap/Panel/DesktopPanel/index.js
  apps/climatemappedafrica/src/components/HURUmap/Panel/MobilePanel/RichData.js
  apps/climatemappedafrica/src/components/HURUmap/Panel/MobilePanel/SubcategoryList.js
  apps/climatemappedafrica/src/components/HURUmap/Panel/MobilePanel/index.js
  apps/climatemappedafrica/src/components/HURUmap/Panel/Profile.js
  apps/climatemappedafrica/src/components/HURUmap/Panel/ProfileItems.js
  apps/climatemappedafrica/src/components/HURUmap/PanelButtonGroup/index.js
  apps/climatemappedafrica/src/components/HURUmap/PinAndCompare/index.js
  apps/climatemappedafrica/src/components/HURUmap/SubcategoryHeader/index.js
  apps/climatemappedafrica/src/components/HURUmap/TreeView/index.js
  apps/climatemappedafrica/src/components/HURUmap/Tutorial/TutorialStep/index.js
  apps/climatemappedafrica/src/components/HURUmap/Tutorial/index.js
  apps/climatemappedafrica/src/components/Image/index.js
  apps/climatemappedafrica/src/components/Link/index.js
  apps/climatemappedafrica/src/components/Menu/index.js
  apps/climatemappedafrica/src/components/Navigation/DesktopNavigation/index.js
  apps/climatemappedafrica/src/components/Navigation/ExploreNavigation/index.js
  apps/climatemappedafrica/src/components/Navigation/index.js
  apps/climatemappedafrica/src/components/Page/Base.js
  apps/climatemappedafrica/src/components/Page/index.js
  apps/climatemappedafrica/src/components/Section/index.js
  apps/climatemappedafrica/src/components/Select/index.js
  apps/climatemappedafrica/src/components/SocialMediaIcons/index.js
  apps/climatemappedafrica/src/components/Tabs/TabPanel.js
  apps/climatemappedafrica/src/components/Tabs/index.js
  apps/climatemappedafrica/src/pages/explore/[[...slug]].js
Labels: chore
