Repository CodeForAfrica/ui, pull requests merged in 2024-10, with the labels that each got.

#903 @/techlabblog mdxjs
  apps/charterafrica/src/components/Articles/Articles.snap.js
  apps/civicsignalblog/package.json
  apps/codeforafrica/package.json
  apps/techlabblog/app/[slug]/page.tsx
  apps/techlabblog/app/layout.tsx
  apps/techlabblog/app/page.tsx
  apps/techlabblog/components/Article/Article.tsx
  apps/techlabblog/components/Article/ArticleHeader.tsx
  apps/techlabblog/components/Article/ArticleSxProps.tsx
  apps/techlabblog/components/Article/index.ts
  apps/techlabblog/components/ArticleList/ArticleList.tsx
  apps/techlabblog/components/ArticleList/index.ts
  apps/techlabblog/components/Markdown/CopyCodeButton.tsx
  apps/techlabblog/components/Markdown/Markdown.tsx
  apps/techlabblog/components/Markdown/index.ts
  apps/techlabblog/components/Post/PostProps.tsx
  apps/techlabblog/components/Post/index.ts
  apps/techlabblog/components/PostHeader/PostHeader.tsx
  apps/techlabblog/components/PostHeader/index.ts
  apps/techlabblog/components/PostList/PostCard.tsx
  apps/techlabblog/components/PostList/PostList.tsx
  apps/techlabblog/components/PostList/index.ts
  apps/techlabblog/content/publication/authors/davidtheprogrammer.mdx
  apps/techlabblog/content/publication/authors/kelvinkipruto.mdx
  apps/techlabblog/content/publication/authors/kilemensi.mdx
  apps/techlabblog/content/publication/posts/exploring-next-js.mdx
  apps/techlabblog/content/publication/posts/javascript-generators.mdx
  apps/techlabblog/content/publication/posts/mastering-docker.mdx
  apps/techlabblog/lib/data/index.ts
  apps/techlabblog/mdx-components.tsx
  apps/techlabblog/mdx.config.mjs
  apps/techlabblog/next.config.mjs
  apps/techlabblog/package.json
  apps/techlabblog/public/blog/javascript-generators.jpg
  apps/techlabblog/theme/index.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: chore

#902 @/CivicSignalBlog - Use aliases in Payload CMS
  apps/civicsignalblog/.eslintrc.js
  apps/civicsignalblog/eslint.webpack.config.js
  apps/civicsignalblog/package.json
  apps/civicsignalblog/payload.config.ts
  apps/civicsignalblog/src/payload/access/applications/main.js
  apps/civicsignalblog/src/payload/access/applications/research.js
  apps/civicsignalblog/src/payload/admin/scss/custom.scss
  apps/civicsignalblog/src/payload/blocks/CustomPageHeader.js
  apps/civicsignalblog/src/payload/blocks/Error.js
  apps/civicsignalblog/src/payload/blocks/ExternalEmbed.js
  apps/civicsignalblog/src/payload/blocks/FeaturedStories.js
  apps/civicsignalblog/src/payload/blocks/LongForm.js
  apps/civicsignalblog/src/payload/blocks/MediaBlock.js
  apps/civicsignalblog/src/payload/blocks/RichText.js
  apps/civicsignalblog/src/payload/collections/Main/Pages.js
  apps/civicsignalblog/src/payload/collections/Research/Authors.js
  apps/civicsignalblog/src/payload/collections/Research/Pages.js
  apps/civicsignalblog/src/payload/collections/Research/Posts.js
  apps/civicsignalblog/src/payload/collections/Research/Tags.js
  apps/civicsignalblog/src/payload/collections/Users.js
  apps/civicsignalblog/src/payload/components/actions/index.tsx
  apps/civicsignalblog/src/payload/fields/content.js
  apps/civicsignalblog/src/payload/fields/links/link.js
  apps/civicsignalblog/src/payload/fields/richText.js
  apps/civicsignalblog/src/payload/globals/Publication/index.js
  apps/civicsignalblog/src/payload/globals/Site/Components/EngagementTab.js
  apps/civicsignalblog/src/payload/globals/Site/Components/GeneralTab.js
  apps/civicsignalblog/src/payload/globals/Site/Components/NavigationTab.js
  apps/civicsignalblog/src/payload/globals/Site/main.js
  apps/civicsignalblog/src/payload/globals/Site/research.js
  apps/civicsignalblog/src/payload/utils/createPagesCollection.js
  apps/civicsignalblog/tsconfig.json
  apps/civicsignalblog/tsconfig.server.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: chore

#911 @/ui Docker build secrets
  .github/workflows/charterafrica-deploy-dev.yml
  .github/workflows/charterafrica-deploy-prod.yml
  .github/workflows/civicsignalblog-deploy-prod.yml
  .github/workflows/codeforafrica-deploy-dev.yml
  .github/workflows/codeforafrica-deploy-prod.yml
  .github/workflows/pesayetu-deploy-dev.yml
  .github/workflows/roboshield-deploy-dev.yml
  .github/workflows/roboshield-deploy-prod.yml
  .github/workflows/techlabblog-deploy-dev.yml
  .github/workflows/vpnmanager-deploy-dev.yml
  Dockerfile
  apps/charterafrica/next.config.js
  apps/civicsignalblog/next.config.js
  apps/codeforafrica/next.config.js
  apps/roboshield/next.config.js
  apps/vpnmanager/next.config.mjs
  docker-compose.yml
Labels: chore

#943 @/civicsignalblog
  Dockerfile
Labels: chore

#948 @/climatemappedafrica About Page
  apps/climatemappedafrica/.eslintrc.js
  apps/climatemappedafrica/eslint.webpack.config.js
  apps/climatemappedafrica/next.config.js
  apps/climatemappedafrica/package.json
  apps/climatemappedafrica/payload.config.ts
  apps/climatemappedafrica/src/components/AboutTeam/AboutTeam.js
  apps/climatemappedafrica/src/components/AboutTeam/AboutTeam.snap.js
  apps/climatemappedafrica/src/components/AboutTeam/AboutTeam.test.js
  apps/climatemappedafrica/src/components/AboutTeam/index.js
  apps/climatemappedafrica/src/components/AboutTeam/useStyles.js
  apps/climatemappedafrica/src/components/Card/ActionArea.js
  apps/climatemappedafrica/src/components/Card/Card.js
  apps/climatemappedafrica/src/components/Card/Card.snap.js
  apps/climatemappedafrica/src/components/Card/Card.test.js
  apps/climatemappedafrica/src/components/Card/Content.js
  apps/climatemappedafrica/src/components/Card/Media.js
  apps/climatemappedafrica/src/components/Card/index.js
  apps/climatemappedafrica/src/components/Card/useStyles.js
  apps/climatemappedafrica/src/components/Carousel/Carousel.js
  apps/climatemappedafrica/src/components/Carousel/Carousel.snap.js
  apps/climatemappedafrica/src/components/Carousel/Carousel.test.js
  apps/climatemappedafrica/src/components/Carousel/index.js
  apps/climatemappedafrica/src/components/Carousel/useStyles.js
  apps/climatemappedafrica/src/components/Header/Header.js
  apps/climatemappedafrica/src/components/Header/Header.snap.js
  apps/climatemappedafrica/src/components/Header/Header.test.js
  apps/climatemappedafrica/src/components/Header/index.js
  apps/climatemappedafrica/src/components/Image/Image.js
  apps/climatemappedafrica/src/components/Image/Image.snap.js
  apps/climatemappedafrica/src/components/Image/Image.test.js
  apps/climatemappedafrica/src/components/Image/index.js
  apps/climatemappedafrica/src/components/Summary/Summary.js
  apps/climatemappedafrica/src/components/Summary/Summary.snap.js
  apps/climatemappedafrica/src/components/Summary/Summary.test.js
  apps/climatemappedafrica/src/components/Summary/index.js
  apps/climatemappedafrica/src/components/Summary/useStyles.js
  apps/climatemappedafrica/src/lib/data/blockify/index.js
  apps/climatemappedafrica/src/lib/data/blockify/team.js
  apps/climatemappedafrica/src/lib/data/common/index.js
  apps/climatemappedafrica/src/lib/data/countries.js
  apps/climatemappedafrica/src/lib/data/utils/getMembers.js
  apps/climatemappedafrica/src/lib/data/utils/index.js
  apps/climatemappedafrica/src/pages/[[...slug]].js
  apps/climatemappedafrica/src/payload/blocks/Summary.js
  apps/climatemappedafrica/src/payload/blocks/Team.js
  apps/climatemappedafrica/src/payload/collections/Members.js
  apps/climatemappedafrica/src/payload/collections/Pages.js
  apps/climatemappedafrica/src/payload/fields/socialLinks.js
  apps/climatemappedafrica/src/utils/equalsIgnoreCase.js
  apps/climatemappedafrica/src/utils/index.js
Labels: enhancement

#947 @/civicsignalblog - fix: Implement payload migrations to rename existing pages to research-pages collections
  apps/civicsignalblog/migrations/20241011_104214_migration.ts
  apps/civicsignalblog/package.json
  apps/civicsignalblog/payload.config.ts
  apps/civicsignalblog/src/payload/lib/data/common/applications.js
Labels: bug

#952 @/climatemappedafrica Page Hero
  apps/climatemappedafrica/public/images/payload/blocks/page-hero.jpg
  apps/climatemappedafrica/public/images/payload/blocks/summary.jpg
  apps/climatemappedafrica/public/images/payload/blocks/team.jpg
  apps/climatemappedafrica/src/components/AboutTeam/AboutTeam.js
  apps/climatemappedafrica/src/components/Card/ActionArea.js
  apps/climatemappedafrica/src/components/PageHero/PageHero.js
  apps/climatemappedafrica/src/components/PageHero/PageHero.snap.js
  apps/climatemappedafrica/src/components/PageHero/PageHero.test.js
  apps/climatemappedafrica/src/components/PageHero/index.js
  apps/climatemappedafrica/src/components/PageHero/useStyles.js
  apps/climatemappedafrica/src/components/RichHeader/RichHeader.js
  apps/climatemappedafrica/src/components/RichHeader/RichHeader.snap.js
  apps/climatemappedafrica/src/components/RichHeader/RichHeader.test.js
  apps/climatemappedafrica/src/components/RichHeader/index.js
  apps/climatemappedafrica/src/lib/data/blockify/index.js
  apps/climatemappedafrica/src/lib/data/blockify/page-hero.js
  apps/climatemappedafrica/src/lib/data/utils/get-members.js
  apps/climatemappedafrica/src/lib/data/utils/index.js
  apps/climatemappedafrica/src/pages/[[...slug]].js
  apps/climatemappedafrica/src/payload/blocks/PageHero.js
  apps/climatemappedafrica/src/payload/blocks/Summary.js
  apps/climatemappedafrica/src/payload/blocks/Team.js
  apps/climatemappedafrica/src/payload/collections/Pages.js
Labels: enhancement

#964 @/climatemappedafrica `TreeView`
  apps/climatemappedafrica/package.json
  apps/climatemappedafrica/src/components/HURUmap/Panel/DesktopPanel/RichData.js
  apps/climatemappedafrica/src/components/HURUmap/Panel/DesktopPanel/useStyles.js
  apps/climatemappedafrica/src/components/HURUmap/TreeView/TreeView.js
  apps/climatemappedafrica/src/components/HURUmap/TreeView/TreeView.snap.js
  apps/climatemappedafrica/src/components/HURUmap/TreeView/TreeView.test.js
  apps/climatemappedafrica/src/components/HURUmap/TreeView/index.js
  apps/climatemappedafrica/src/components/HURUmap/TreeView/index.stories.js
  apps/climatemappedafrica/src/components/HURUmap/TreeView/useStyles.js
  pnpm-lock.yaml
Labels: bug, enhancement

#967 Improve @/climatemappedafrica `HURUmap/Panel`
  apps/climatemappedafrica/src/components/ExplorePage/index.js
  apps/climatemappedafrica/src/components/HURUmap/Panel/DesktopPanel/DesktopPanel.js
  apps/climatemappedafrica/src/components/HURUmap/Panel/DesktopPanel/PanelButtons.js
  apps/climatemappedafrica/src/components/HURUmap/Panel/DesktopPanel/RichData.js
  apps/climatemappedafrica/src/components/HURUmap/Panel/DesktopPanel/index.js
  apps/climatemappedafrica/src/components/HURUmap/Panel/DesktopPanel/useStyles.js
  apps/climatemappedafrica/src/components/HURUmap/Panel/MobilePanel/MobilePanel.js
  apps/climatemappedafrica/src/components/HURUmap/Panel/MobilePanel/RichData.js
  apps/climatemappedafrica/src/components/HURUmap/Panel/MobilePanel/SubcategoryList.js
  apps/climatemappedafrica/src/components/HURUmap/Panel/MobilePanel/index.js
  apps/climatemappedafrica/src/components/HURUmap/Panel/MobilePanel/useStyles.js
  apps/climatemappedafrica/src/components/HURUmap/Panel/Panel.js
  apps/climatemappedafrica/src/components/HURUmap/Panel/Panel.snap.js
  apps/climatemappedafrica/src/components/HURUmap/Panel/Panel.test.js
  apps/climatemappedafrica/src/components/HURUmap/Panel/Profile.js
  apps/climatemappedafrica/src/components/HURUmap/Panel/ProfileItems.js
  apps/climatemappedafrica/src/components/HURUmap/Panel/index.js
  apps/climatemappedafrica/src/components/HURUmap/Panel/index.stories.js
  apps/climatemappedafrica/src/components/HURUmap/PanelButtonGroup/PanelButtonGroup.js
  apps/climatemappedafrica/src/components/HURUmap/PanelButtonGroup/PanelButtonGroup.snap.js
  apps/climatemappedafrica/src/components/HURUmap/PanelButtonGroup/PanelButtonGroup.test.js
  apps/climatemappedafrica/src/components/HURUmap/PanelButtonGroup/index.js
  apps/climatemappedafrica/src/components/HURUmap/PanelButtonGroup/index.stories.js
  apps/climatemappedafrica/src/components/HURUmap/PanelButtonGroup/useStyles.js
  packages/hurumap-core/src/Location/Location.js
  packages/hurumap-core/src/Location/Location.snap.js
  packages/hurumap-core/src/LocationTag/LocationTag.js
  packages/hurumap-core/src/LocationTag/LocationTag.snap.js
  packages/hurumap-next/src/Map/Legend.js
Labels: bug, enhancement

#969 Enhance `@commons-ui/payload/RichText`
  apps/climatemappedafrica/eslint.webpack.config.js
  apps/climatemappedafrica/jest.config.js
  apps/climatemappedafrica/jsconfig.json
  apps/climatemappedafrica/next.config.js
  apps/climatemappedafrica/src/components/Footer/index.js
  apps/climatemappedafrica/src/components/Hero/Hero.snap.js
  apps/climatemappedafrica/src/components/RichHeader/RichHeader.js
  apps/climatemappedafrica/src/components/Summary/Summary.js
  apps/climatemappedafrica/src/components/Summary/Summary.snap.js
  apps/climatemappedafrica/src/components/Summary/useStyles.js
  apps/climatemappedafrica/src/lib/data/common/index.js
  apps/climatemappedafrica/src/payload/blocks/Summary.js
  apps/climatemappedafrica/src/theme/index.js
  apps/climatemappedafrica/tsconfig.json
  packages/commons-ui-payload/src/RichText/Media.js
  packages/commons-ui-payload/src/RichText/RichText.js
  packages/commons-ui-payload/src/index.js
  packages/commons-ui-payload/src/utils/image-from-media.js
  packages/commons-ui-payload/src/utils/index.js
Labels: enhancement

#931 @/CivicSignalBlog - Add Ability to Manage MediaData Page
  apps/civicsignalblog/.eslintrc.js
  apps/civicsignalblog/jsconfig.json
  apps/civicsignalblog/next.config.js
  apps/civicsignalblog/package.json
  apps/civicsignalblog/payload.config.ts
  apps/civicsignalblog/public/images/cms/blocks/web_tools_page_header.png
  apps/civicsignalblog/server.ts
  apps/civicsignalblog/src/components/CMSContent/CMSContent.snap.js
  apps/civicsignalblog/src/components/Footer/FooterDescription.js
  apps/civicsignalblog/src/components/LongFormRichText/LongFormRichText.js
  apps/civicsignalblog/src/components/LongFormRichText/LongFormRichText.snap.js
  apps/civicsignalblog/src/components/PageHeader/PageHeader.js
  apps/civicsignalblog/src/components/PageHeader/PageHeader.snap.js
  apps/civicsignalblog/src/components/PageHeader/PageHeader.test.js
  apps/civicsignalblog/src/components/RichText/RichText.js
  apps/civicsignalblog/src/components/RichText/RichText.snap.js
  apps/civicsignalblog/src/components/RichText/RichText.test.js
  apps/civicsignalblog/src/components/RichText/index.js
  apps/civicsignalblog/src/payload/access/applications/main.js
  apps/civicsignalblog/src/payload/access/applications/research.js
  apps/civicsignalblog/src/payload/access/canAccessApplication.js
  apps/civicsignalblog/src/payload/access/isAdminOrEditor.js
  apps/civicsignalblog/src/payload/access/roles.js
  apps/civicsignalblog/src/payload/blocks/PageHeader.js
  apps/civicsignalblog/src/payload/collections/Main/MediaData.js
  apps/civicsignalblog/src/payload/collections/Main/Pages.js
  apps/civicsignalblog/src/payload/collections/Research/Authors.js
  apps/civicsignalblog/src/payload/collections/Research/Media.js
  apps/civicsignalblog/src/payload/collections/Research/Pages.js
  apps/civicsignalblog/src/payload/collections/Research/Posts.js
  apps/civicsignalblog/src/payload/collections/Research/Tags.js
  apps/civicsignalblog/src/payload/collections/Users.js
  apps/civicsignalblog/src/payload/components/actions/index.tsx
  apps/civicsignalblog/src/payload/components/allowedAppSelect/index.tsx
  apps/civicsignalblog/src/payload/fields/customSelect/currentApp.js
  apps/civicsignalblog/src/payload/fields/customSelect/defaultApp.js
  apps/civicsignalblog/src/payload/fields/document.js
  apps/civicsignalblog/src/payload/globals/Site/main.js
  apps/civicsignalblog/src/payload/lib/data/common/applications.js
  apps/civicsignalblog/tsconfig.json
  pnpm-lock.yaml
Labels: enhancement

#973 @/CivicSignalBlog - fix eslint failure due to custom Payload components
  apps/civicsignalblog/.eslintrc.js
  apps/civicsignalblog/jest.config.js
  apps/civicsignalblog/src/components/PageHeader/PageHeader.snap.js
Labels: bug

#977 Fix @/climatemappedafrica images on Dev
  .dockerignore
  .gitignore
  apps/climatemappedafrica/.env.template
  apps/climatemappedafrica/next.config.js
  apps/climatemappedafrica/payload.config.ts
  apps/climatemappedafrica/payload.image.loader.js
  apps/climatemappedafrica/src/components/HURUmap/LocationHeader/useStyles.js
  apps/climatemappedafrica/src/components/HURUmap/Panel/DesktopPanel/PanelButtons.js
  apps/climatemappedafrica/src/components/HURUmap/Panel/MobilePanel/MobilePanel.js
  apps/climatemappedafrica/src/components/HURUmap/Panel/Profile.js
  apps/climatemappedafrica/src/pages/[[...slugs]].js
  apps/climatemappedafrica/src/payload/blocks/Hero.js
Labels: bug
