Repository CodeForAfrica/ui, pull requests merged in 2024-06, with the labels that each got.

#728 fix: Resolve failing build issue due to case mismatch on TimePicker component
  apps/roboshield/src/components/TimePicker/TimePicker.tsx
  apps/roboshield/src/components/TimePicker/index.ts
Labels: bug

#725 Single Multi-Stage Dockerfile for the repo
  .dockerignore
  .github/workflows/charterafrica-deploy-dev.yml
  .github/workflows/charterafrica-deploy-prod.yml
  .github/workflows/codeforafrica-deploy-dev-app.yml
  .github/workflows/codeforafrica-deploy-prod.yml
  .github/workflows/codeforafrica-deploy-review-app.yml
  .github/workflows/pesayetu-deploy-dev.yml
  .github/workflows/roboshield-deploy-dev.yml
  .github/workflows/vpnmanager-deploy-dev.yml
  Dockerfile
  Dockerfile.pesayetu
  Dockerfile.vpnmanager
  Makefile
  apps/charterafrica/src/components/ComboBox/ComboBox.snap.js
  apps/charterafrica/src/components/Datasets/DatasetFilterBar.snap.js
  apps/charterafrica/src/components/Datasets/Datasets.snap.js
  apps/charterafrica/src/components/Documents/DocumentFilterBar.snap.js
  apps/charterafrica/src/components/Documents/Documents.snap.js
  apps/pesayetu/.eslintrc.js
  apps/pesayetu/eslint.webpack.config.js
  apps/pesayetu/package.json
  apps/pesayetu/src/components/HURUmap/IndicatorTitle/Download.js
  apps/roboshield/src/components/Timepicker/TimePicker.tsx
  apps/roboshield/src/components/Timepicker/index.ts
  apps/vpnmanager/.eslintignore
  apps/vpnmanager/.eslintrc.js
  apps/vpnmanager/.lintstagedrc.js
  apps/vpnmanager/next.config.mjs
  apps/vpnmanager/package.json
  apps/vpnmanager/src/components/DesktopNavBar/DesktopNavBar.tsx
  apps/vpnmanager/src/components/MobileNavBar/MobileNavBar.tsx
  apps/vpnmanager/src/lib/data/spreadsheet.ts
  apps/vpnmanager/src/lib/email/templates.ts
  apps/vpnmanager/src/pages/_app.tsx
  apps/vpnmanager/src/pages/_document.tsx
  apps/vpnmanager/src/theme/index.ts
  apps/vpnmanager/src/utils/fetchJson.ts
  apps/vpnmanager/src/utils/index.ts
  apps/vpnmanager/src/utils/wordToCamelCase.ts
  apps/vpnmanager/tsconfig.json
  apps/vpnmanager/tsconfig.server.json
  charterafrica.Dockerfile
  codeforafrica.Dockerfile
  docker-compose.yml
  pnpm-lock.yaml
  roboshield.Dockerfile
Labels: chore, dependencies, docker

#730 Add Sentry to RoboShield
  .github/workflows/codeforafrica-deploy-dev-app.yml
  .github/workflows/codeforafrica-deploy-prod.yml
  .github/workflows/pesayetu-deploy-dev.yml
  .github/workflows/roboshield-deploy-dev.yml
  .gitignore
  apps/roboshield/.env
  apps/roboshield/.env.template
  apps/roboshield/instrumentation.ts
  apps/roboshield/next.config.mjs
  apps/roboshield/package.json
  apps/roboshield/sentry.client.config.ts
  apps/roboshield/sentry.edge.config.ts
  apps/roboshield/sentry.server.config.ts
  apps/roboshield/src/components/Timepicker/TimePicker.tsx
  apps/roboshield/src/pages/_error.jsx
  pnpm-lock.yaml
  roboshield.Dockerfile
Labels: chore, dependencies, docker

#731 Improve RoboShield Hero & Footer
  apps/roboshield/public/icons/smarttoy-24-white.svg
  apps/roboshield/src/assets/icons/Type=facebook, Size=24, Color=CurrentColor.svg
  apps/roboshield/src/assets/icons/Type=instagram, Size=24, Color=CurrentColor.svg
  apps/roboshield/src/assets/icons/Type=linkedin, Size=24, Color=CurrentColor.svg
  apps/roboshield/src/assets/icons/Type=slack, Size=24, Color=CurrentColor.svg
  apps/roboshield/src/assets/icons/Type=twitter, Size=24, Color=CurrentColor.svg
  apps/roboshield/src/components/Footer/Footer.tsx
  apps/roboshield/src/components/Footer/FooterDescription.tsx
  apps/roboshield/src/components/Hero/Hero.tsx
  apps/roboshield/src/components/NewsletterSubscription/NewsletterSubscription.tsx
  apps/roboshield/src/components/NewsletterSubscription/index.ts
  apps/roboshield/src/components/StayInTouch/StayInTouch.tsx
  apps/roboshield/src/components/StayInTouch/index.ts
  apps/roboshield/src/components/TimePicker/TimePicker.tsx
  apps/roboshield/src/components/TimePicker/index.ts
  apps/roboshield/src/pages/index.tsx
  apps/roboshield/src/theme/index.ts
Labels: bug, enhancement

#732 SENTRY_ENVIRONMENT
  .github/workflows/charterafrica-deploy-dev.yml
  .github/workflows/charterafrica-deploy-prod.yml
  .github/workflows/codeforafrica-deploy-dev-app.yml
  .github/workflows/codeforafrica-deploy-prod.yml
  .github/workflows/pesayetu-deploy-dev.yml
  .github/workflows/roboshield-deploy-dev.yml
  .github/workflows/vpnmanager-deploy-dev.yml
  Dockerfile
  apps/charterafrica/.env
  apps/charterafrica/.env.template
  apps/codeforafrica/.env
  apps/codeforafrica/env.template
  apps/pesayetu/.env
  apps/roboshield/.env
  apps/roboshield/.env.template
  apps/roboshield/package.json
  apps/roboshield/src/components/Finish/Finish.tsx
  apps/roboshield/src/components/Footer/Footer.tsx
  apps/roboshield/src/components/Footer/index.ts
  apps/roboshield/src/components/Page/Page.tsx
  apps/roboshield/src/components/Sitemaps/Sitemaps.tsx
  apps/roboshield/src/context/GlobalContext.tsx
  apps/roboshield/src/pages/index.tsx
  apps/vpnmanager/sentry.client.config.ts
  apps/vpnmanager/sentry.edge.config.ts
  apps/vpnmanager/sentry.server.config.ts
  charterafrica.Dockerfile
  codeforafrica.Dockerfile
  docker-compose.yml
  roboshield.Dockerfile
Labels: chore

#737 @/charterafrica `Dockerfile` migration
  .github/workflows/charterafrica-deploy-dev.yml
  .github/workflows/charterafrica-deploy-prod.yml
  Dockerfile
  Makefile
  apps/charterafrica/next.config.js
  apps/charterafrica/package.json
  apps/charterafrica/turbo.json
  apps/codeforafrica/package.json
  apps/codeforafrica/turbo.json
  apps/commons-ui-docs/package.json
  apps/commons-ui-docs/turbo.json
  apps/pesayetu/package.json
  apps/pesayetu/turbo.json
  apps/promisetracker/package.json
  apps/roboshield/package.json
  apps/vpnmanager/package.json
  charterafrica.Dockerfile
  docker-compose.yml
  package.json
  packages/commons-ui-core/package.json
  packages/commons-ui-next/package.json
  packages/commons-ui-testing-library/package.json
  packages/eslint-config-commons-ui/package.json
  packages/jest-config-commons-ui/package.json
  packages/playwright-config-commons-ui/package.json
  pnpm-lock.yaml
  roboshield.Dockerfile
  turbo.json
Labels: chore, dependencies, docker

#742 Fix @/roboshield RichText types
  apps/charterafrica/package.json
  apps/codeforafrica/package.json
  apps/commons-ui-docs/package.json
  apps/pesayetu/package.json
  apps/roboshield/src/components/Footer/Footer.tsx
  apps/roboshield/src/components/Footer/FooterDescription.tsx
  apps/roboshield/src/components/RichText/RichText.tsx
  apps/roboshield/src/components/RichText/index.ts
  pnpm-lock.yaml
Labels: bug, dependencies

#745 Fix @/roboshield social links
  apps/roboshield/src/components/DesktopNavBar/DesktopNavBar.tsx
  apps/roboshield/src/components/Footer/Footer.tsx
  apps/roboshield/src/components/MobileNavBar/MobileNavBar.tsx
  apps/roboshield/src/components/NavBar/NavBar.tsx
  apps/roboshield/src/components/NavBarNavList/NavBarNavList.tsx
  apps/roboshield/src/components/Page/Page.tsx
  apps/roboshield/src/components/SocialMediaLinkIcon/LinkIcon.tsx
  apps/roboshield/src/components/SocialMediaLinkIcon/SocialMediaLinkIcon.tsx
  apps/roboshield/src/components/SocialMediaLinkIcon/index.ts
  apps/roboshield/src/components/StayInTouch/StayInTouch.tsx
Labels: bug
