Repository CodeForAfrica/ui, pull requests merged in 2024-11, with the labels that each got.

#989 Fix @/climatemappedafrica HURUmap data handling
  apps/climatemappedafrica/src/lib/data/blockify/explore-page.js
  apps/climatemappedafrica/src/lib/data/blockify/hero.js
  apps/climatemappedafrica/src/lib/data/blockify/index.js
  apps/climatemappedafrica/src/lib/data/blockify/page-hero.js
  apps/climatemappedafrica/src/lib/data/blockify/team.js
  apps/climatemappedafrica/src/lib/data/blockify/tutorial.js
  apps/climatemappedafrica/src/lib/data/common/index.js
  apps/climatemappedafrica/src/payload/globals/HURUMap/DataPanels.js
  apps/climatemappedafrica/src/payload/globals/HURUMap/Profile.js
  apps/climatemappedafrica/src/payload/globals/HURUMap/RootGeography.js
  apps/climatemappedafrica/src/payload/globals/HURUMap/Tutorial.js
  apps/climatemappedafrica/src/payload/globals/HURUMap/index.js
Labels: bug, chore

#1002 Charter Africa: Update SMTP configuration
  apps/charterafrica/package.json
  apps/charterafrica/server.ts
  pnpm-lock.yaml
Labels: enhancement

#983 @/CivicSignal: Fix previews on research blog content
  apps/civicsignalblog/src/components/ArticleGrid/ArticleGrid.js
  apps/civicsignalblog/src/components/ArticleGrid/ArticleGrid.snap.js
  apps/civicsignalblog/src/components/Articles/Articles.snap.js
  apps/civicsignalblog/src/components/Footer/FooterDescription.js
  apps/civicsignalblog/src/components/LongFormMedia/LongFormMedia.js
  apps/civicsignalblog/src/components/NavBar/NavBar.js
  apps/civicsignalblog/src/components/Page/Page.js
  apps/civicsignalblog/src/components/PageHeader/PageHeader.js
  apps/civicsignalblog/src/components/PageHeader/PageHeader.snap.js
  apps/civicsignalblog/src/lib/data/common/index.js
  apps/civicsignalblog/src/lib/data/pagify/post.js
  apps/civicsignalblog/src/lib/data/utils/posts.js
  apps/civicsignalblog/src/payload/access/canAccessApplication.js
  apps/civicsignalblog/src/payload/components/allowedAppSelect/index.tsx
  packages/commons-ui-payload/src/RichText/RichText.js
Labels: bug, enhancement

#1003 Fix @/climatemappedafrica Feedback Fixes
  .github/workflows/climatemappedafrica-deploy-dev.yml
  Dockerfile
  apps/climatemappedafrica/.env.template
  apps/climatemappedafrica/public/android-chrome-192x192.png
  apps/climatemappedafrica/public/android-chrome-512x512.png
  apps/climatemappedafrica/public/apple-touch-icon.png
  apps/climatemappedafrica/public/browserconfig.xml
  apps/climatemappedafrica/public/favicon-16x16.png
  apps/climatemappedafrica/public/favicon-32x32.png
  apps/climatemappedafrica/public/favicon-96x96.png
  apps/climatemappedafrica/public/favicon.ico
  apps/climatemappedafrica/public/favicon.svg
  apps/climatemappedafrica/public/image.jpg
  apps/climatemappedafrica/public/image.png
  apps/climatemappedafrica/public/mstile-150x150.png
  apps/climatemappedafrica/public/safari-pinned-tab.svg
  apps/climatemappedafrica/public/site.webmanifest
  apps/climatemappedafrica/public/sitemap.xml
  apps/climatemappedafrica/public/web-app-manifest-192x192.png
  apps/climatemappedafrica/public/web-app-manifest-512x512.png
  apps/climatemappedafrica/src/assets/icons/caret.svg
  apps/climatemappedafrica/src/assets/menu_close.svg
  apps/climatemappedafrica/src/components/AboutTeam/AboutTeam.snap.js
  apps/climatemappedafrica/src/components/DropdownSearch/DownloadSearch.js
  apps/climatemappedafrica/src/components/DropdownSearch/DropdownSearch.snap.js
  apps/climatemappedafrica/src/components/ExplorePage/index.js
  apps/climatemappedafrica/src/components/ExplorePage/useStyles.js
  apps/climatemappedafrica/src/components/Footer/index.js
  apps/climatemappedafrica/src/components/HURUmap/Chart/index.js
  apps/climatemappedafrica/src/components/HURUmap/Chart/index.stories.js
  apps/climatemappedafrica/src/components/HURUmap/Panel/DesktopPanel/DesktopPanel.js
  apps/climatemappedafrica/src/components/HURUmap/Panel/DesktopPanel/PanelButtons.js
  apps/climatemappedafrica/src/components/HURUmap/Panel/DesktopPanel/RichData.js
  apps/climatemappedafrica/src/components/HURUmap/Panel/MobilePanel/MobilePanel.js
  apps/climatemappedafrica/src/components/HURUmap/Panel/MobilePanel/SubcategoryList.js
  apps/climatemappedafrica/src/components/HURUmap/Panel/MobilePanel/useStyles.js
  apps/climatemappedafrica/src/components/HURUmap/Panel/Panel.snap.js
  apps/climatemappedafrica/src/components/HURUmap/Panel/Profile.js
  apps/climatemappedafrica/src/components/HURUmap/PinAndCompare/index.js
  apps/climatemappedafrica/src/components/Hero/Hero.js
  apps/climatemappedafrica/src/components/Hero/Hero.snap.js
  apps/climatemappedafrica/src/components/Hero/Hero.test.js
  apps/climatemappedafrica/src/components/Menu/index.js
  apps/climatemappedafrica/src/components/Navigation/DesktopNavigation/index.js
  apps/climatemappedafrica/src/components/Navigation/ExploreNavigation/index.js
  apps/climatemappedafrica/src/components/Navigation/MobileNavigation/index.js
  apps/climatemappedafrica/src/components/Navigation/index.js
  apps/climatemappedafrica/src/components/NextImageButton/index.js
  apps/climatemappedafrica/src/components/PageHero/PageHero.snap.js
  apps/climatemappedafrica/src/components/Summary/Summary.snap.js
  apps/climatemappedafrica/src/components/Summary/Summary.test.js
  apps/climatemappedafrica/src/components/Tabs/index.js
  apps/climatemappedafrica/src/lib/data/common/index.js
  apps/climatemappedafrica/src/pages/_document.js
  apps/climatemappedafrica/src/theme/index.js
  apps/climatemappedafrica/turbo.json
  docker-compose.yml
Labels: bug, chore

#1004 Fix `@/climatemappedafrica` `auth.pass`
  apps/climatemappedafrica/server.ts
Labels: bug

#1005 @/CivicSignalBlog: Fix failing build due to import of allowedAppSelect.tsx component in Payload users collection
  apps/civicsignalblog/src/payload/components/allowedAppSelect/index.tsx
Labels: bug

#1006 @/CivicSignalBlog: Misc fixes on CivicSignal blog
  apps/civicsignalblog/migrations/20241122_054517_migration.ts
  apps/civicsignalblog/src/components/ArticleGrid/ArticleGrid.js
  apps/civicsignalblog/src/components/ArticleGrid/ArticleGrid.snap.js
  apps/civicsignalblog/src/components/Articles/Articles.snap.js
  apps/civicsignalblog/src/lib/data/utils/posts.js
  apps/codeforafrica/src/components/ArticleGrid/ArticleGrid.js
  apps/codeforafrica/src/components/ArticleGrid/ArticleGrid.snap.js
Labels: bug
