Repository CodeForAfrica/ui, pull requests merged in 2024-07, with the labels that each got.

#746 @/Roboshield Move Form to payloadcms
  apps/roboshield/payload-types.ts
  apps/roboshield/src/components/BlockRenderer/BlockRenderer.tsx
  apps/roboshield/src/components/Code/Code.tsx
  apps/roboshield/src/components/CommonBots/CommonBots.tsx
  apps/roboshield/src/components/CommonSettings/CommonSettings.tsx
  apps/roboshield/src/components/Delays/Delays.tsx
  apps/roboshield/src/components/ExistingRobots/ExistingRobots.tsx
  apps/roboshield/src/components/Finish/Finish.tsx
  apps/roboshield/src/components/PageHeader/PageHeader.tsx
  apps/roboshield/src/components/RoboForm/RoboForm.tsx
  apps/roboshield/src/components/RoboForm/index.ts
  apps/roboshield/src/components/Sitemaps/Sitemaps.tsx
  apps/roboshield/src/components/SkipToLastStep/SkipToLastStep.tsx
  apps/roboshield/src/components/StepHint/StepHint.tsx
  apps/roboshield/src/components/StepperNav/StepperNav.tsx
  apps/roboshield/src/lib/data/blockify/index.ts
  apps/roboshield/src/lib/data/blockify/processBlockRoboForm.ts
  apps/roboshield/src/lib/data/common/index.ts
  apps/roboshield/src/payload/Blocks/RoboForm.ts
  apps/roboshield/src/payload/collections/Pages.ts
  apps/roboshield/src/types/stepComponent.ts
Labels: enhancement

#751 @/Roboshield fix FOUC bug
  apps/roboshield/package.json
  apps/roboshield/src/pages/_app.tsx
  apps/roboshield/src/pages/_document.tsx
  apps/roboshield/src/utils/createEmotionCache.ts
  pnpm-lock.yaml
Labels: bug

#754 @/Roboshield fix mobile UI bugs
  apps/roboshield/src/components/Hero/Hero.tsx
  apps/roboshield/src/components/MobileNavBar/MobileNavBar.tsx
Labels: bug

#757 @/Roboshield fix failing build
  apps/roboshield/src/assets/icons/Type=menu, Size=32, Color=CurrentColor.svg
  apps/roboshield/src/components/MobileNavBar/MobileNavBar.tsx
Labels: bug

#763 @/Roboshield Robots Generator form
  apps/roboshield/payload-types.ts
  apps/roboshield/src/components/BlockRenderer/BlockRenderer.tsx
  apps/roboshield/src/components/CommonBots/CommonBots.tsx
  apps/roboshield/src/components/CommonSettings/CommonSettings.tsx
  apps/roboshield/src/components/Delays/Delays.tsx
  apps/roboshield/src/components/ExistingRobots/index.ts
  apps/roboshield/src/components/ExistingRobotsTxt/ExistingRobotsTxt.tsx
  apps/roboshield/src/components/ExistingRobotsTxt/index.ts
  apps/roboshield/src/components/Finish/Finish.tsx
  apps/roboshield/src/components/Hero/Hero.tsx
  apps/roboshield/src/components/RoboForm/index.ts
  apps/roboshield/src/components/RobotsTxtGenerator/RobotsTxtGenerator.tsx
  apps/roboshield/src/components/RobotsTxtGenerator/index.ts
  apps/roboshield/src/components/Sitemaps/Sitemaps.tsx
  apps/roboshield/src/components/SkipToLastStep/SkipToLastStep.tsx
  apps/roboshield/src/lib/data/blockify/index.ts
  apps/roboshield/src/lib/data/blockify/processBlockRoboForm.ts
  apps/roboshield/src/pages/[[...slug]].tsx
  apps/roboshield/src/payload/blocks/RobotsTxtGenerator.ts
  apps/roboshield/src/payload/collections/Pages.ts
  apps/roboshield/src/types/stepComponent.ts
Labels: enhancement

#768 Bugfix/761 roboshield stylings
  apps/roboshield/src/assets/icons/Type=back, Size=24, Color=CurrentColor.svg
  apps/roboshield/src/assets/icons/Type=copy, Size=24, Color=CurrentColor.svg
  apps/roboshield/src/assets/icons/Type=reset, Size=24, Color=CurrentColor.svg
  apps/roboshield/src/assets/icons/Type=save, Size=24, Color=CurrentColor.svg
  apps/roboshield/src/components/Code/Code.tsx
  apps/roboshield/src/components/Statistics/Statistics.tsx
Labels: enhancement

#779 @/RoboShield Add Payload Live Previews
  apps/roboshield/package.json
  apps/roboshield/payload-types.ts
  apps/roboshield/payload.config.ts
  apps/roboshield/src/components/Hero/Hero.tsx
  apps/roboshield/src/pages/[[...slug]].tsx
  apps/roboshield/src/payload/blocks/SiteHero.ts
  apps/roboshield/src/payload/collections/Pages.ts
  pnpm-lock.yaml
Labels: enhancement

#778 @/Roboshield deploy to prod
  .github/workflows/roboshield-deploy-prod.yml
  apps/roboshield/package.json
Labels: chore

#784 @/RoboShield fix misc issues
  apps/roboshield/package.json
  apps/roboshield/payload.config.ts
  apps/roboshield/src/components/Footer/Footer.tsx
  apps/roboshield/src/components/TwoToneBackground/TwoToneBackground.tsx
  apps/roboshield/src/lib/payload/index.ts
Labels: bug

#787 Fix/RoboShield failed build
  apps/roboshield/package.json
  apps/roboshield/payload-types.ts
  apps/roboshield/payload.config.ts
Labels: bug
