Repository CodeForAfrica/ui, pull requests merged in 2024-12, with the labels that each got.

#1008 Remove useStyles from HURUMap
  apps/climatemappedafrica/src/assets/icons/x-logo.svg
  apps/climatemappedafrica/src/components/HURUmap/CategoryHeader/index.js
  apps/climatemappedafrica/src/components/HURUmap/CategoryHeader/useStyles.js
  apps/climatemappedafrica/src/components/HURUmap/Chart/Filters.js
  apps/climatemappedafrica/src/components/HURUmap/Chart/index.js
  apps/climatemappedafrica/src/components/HURUmap/ChartFilter/index.js
  apps/climatemappedafrica/src/components/HURUmap/ChartFilter/useStyles.js
  apps/climatemappedafrica/src/components/HURUmap/KeyMetric/index.js
  apps/climatemappedafrica/src/components/HURUmap/KeyMetric/useStyles.js
  apps/climatemappedafrica/src/components/HURUmap/LocationHeader/index.js
  apps/climatemappedafrica/src/components/HURUmap/LocationHeader/useStyles.js
  apps/climatemappedafrica/src/components/HURUmap/Panel/MobilePanel/MobilePanel.js
  apps/climatemappedafrica/src/components/HURUmap/Panel/MobilePanel/useStyles.js
  apps/climatemappedafrica/src/components/HURUmap/Panel/ProfileItems.js
  apps/climatemappedafrica/src/components/HURUmap/PinAndCompare/index.js
  apps/climatemappedafrica/src/components/HURUmap/PinAndCompare/useStyles.js
  apps/climatemappedafrica/src/components/HURUmap/SubcategoryHeader/index.js
  apps/climatemappedafrica/src/components/HURUmap/Tutorial/Line.js
  apps/climatemappedafrica/src/components/HURUmap/Tutorial/TutorialStep/index.js
  apps/climatemappedafrica/src/components/HURUmap/Tutorial/TutorialStep/useStyles.js
  apps/climatemappedafrica/src/components/HURUmap/Tutorial/index.js
  apps/climatemappedafrica/src/components/HURUmap/Tutorial/useStyles.js
  apps/climatemappedafrica/src/components/Select/index.js
  apps/climatemappedafrica/src/components/Select/useStyles.js
  apps/climatemappedafrica/src/components/Tabs/TabPanel.js
  apps/climatemappedafrica/src/components/Tabs/index.js
  packages/hurumap-core/src/Share/ShareButton.js
Labels: chore

#1009 @/CivicSignalBlog: Add Web Tools authentication form configuration
  apps/civicsignalblog/payload.config.ts
  apps/civicsignalblog/src/payload/fields/formInputFieldGroup.js
  apps/civicsignalblog/src/payload/globals/Forms/login/LoginTab.js
  apps/civicsignalblog/src/payload/globals/Forms/login/index.js
  apps/civicsignalblog/src/payload/globals/Forms/registration/RegistrationTab.js
  apps/civicsignalblog/src/payload/globals/Forms/registration/index.js
  apps/civicsignalblog/src/payload/globals/Forms/resetPassword/ResetPasswordTab.js
  apps/civicsignalblog/src/payload/globals/Forms/resetPassword/index.js
  pnpm-lock.yaml
Labels: enhancement

#1017 @/CivicSignalBlog - Fix: Add loginSucceeded Field to Payload CMS
  apps/civicsignalblog/src/payload/globals/Forms/login/LoginTab.js
Labels: bug
