Repository CodeForAfrica/ui, pull requests merged in 2024-09, with the labels that each got.

#865 @/engineeringblog App Navbar
  apps/engineeringblog/app/StyledRoot.tsx
  apps/engineeringblog/app/apple-touch.png
  apps/engineeringblog/app/favicon.ico
  apps/engineeringblog/app/icon.png
  apps/engineeringblog/app/layout.tsx
  apps/engineeringblog/app/openGraphImage.jpg
  apps/engineeringblog/app/page.tsx
  apps/engineeringblog/app/robots.txt
  apps/engineeringblog/assets/icons/Type=chevron-left, Size=24, Color=CurrentColor.svg
  apps/engineeringblog/assets/icons/Type=menu, Size=24, Color=CurrentColor.svg
  apps/engineeringblog/assets/icons/Type=x, Size=24, Color=CurrentColor.svg
  apps/engineeringblog/assets/images/logo-dark-mode.png
  apps/engineeringblog/assets/images/logo-dark.png
  apps/engineeringblog/assets/images/logo-light-mode.png
  apps/engineeringblog/assets/images/logo-light.png
  apps/engineeringblog/components/Logo/Logo.tsx
  apps/engineeringblog/components/Logo/index.ts
  apps/engineeringblog/components/NavBar/DesktopNavBar/DesktopNavBar.tsx
  apps/engineeringblog/components/NavBar/DesktopNavBar/index.ts
  apps/engineeringblog/components/NavBar/MobileNavBar/MobileNavBar.tsx
  apps/engineeringblog/components/NavBar/MobileNavBar/index.ts
  apps/engineeringblog/components/NavBar/NavBar.tsx
  apps/engineeringblog/components/NavBar/NavBarProps.tsx
  apps/engineeringblog/components/NavBar/index.ts
  apps/engineeringblog/components/Navbar.tsx
  apps/engineeringblog/next.config.mjs
  apps/engineeringblog/package.json
  apps/engineeringblog/theme/index.ts
  apps/engineeringblog/tsconfig.json
  apps/engineeringblog/types.d.ts
  pnpm-lock.yaml
Labels: enhancement

#869 @/PesaYetu Fix TreeView Component
  apps/pesayetu/package.json
  apps/pesayetu/src/components/HURUmap/TreeView/index.js
  apps/pesayetu/src/components/HURUmap/TreeView/useStyles.js
  packages/hurumap-next/src/Map/LazyMap.js
  pnpm-lock.yaml
Labels: bug

#862 @/ui Switch to dependencies catalogs
  Dockerfile
  apps/charterafrica/package.json
  apps/civicsignalblog/package.json
  apps/climatemappedafrica/package.json
  apps/codeforafrica/package.json
  apps/engineeringblog/package.json
  apps/pesayetu/package.json
  apps/promisetracker/package.json
  apps/roboshield/package.json
  apps/uibook/package.json
  apps/vpnmanager/package.json
  package.json
  packages/commons-ui-core/package.json
  packages/commons-ui-next/package.json
  packages/commons-ui-testing-library/package.json
  packages/eslint-config-commons-ui/package.json
  packages/hurumap-core/package.json
  packages/hurumap-next/package.json
  packages/jest-config-commons-ui/__mocks__/empty.js
  packages/jest-config-commons-ui/__mocks__/nextFontMock.js
  packages/jest-config-commons-ui/index.js
  packages/jest-config-commons-ui/next.js
  packages/jest-config-commons-ui/package.json
  packages/playwright-config-commons-ui/package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: chore

#874 @/ui Fix build issues
  apps/roboshield/package.json
  apps/roboshield/src/components/RobotsTxtGenerator/RobotsTxtGenerator.tsx
  apps/uibook/package.json
  apps/vpnmanager/package.json
  apps/vpnmanager/src/components/MobileNavBar/MobileNavBar.tsx
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: bug

#880 Mark @/commons-ui/core components as client only for now
  apps/engineeringblog/app/[slug]/page.tsx
  apps/engineeringblog/app/layout.tsx
  apps/engineeringblog/app/page.tsx
  apps/engineeringblog/components/Article/Article.tsx
  apps/engineeringblog/components/Article/ArticleContent.tsx
  apps/engineeringblog/components/Article/ArticleHeader.tsx
  apps/engineeringblog/components/Article/ArticleSxProps.tsx
  apps/engineeringblog/components/Article/index.ts
  apps/engineeringblog/components/ArticleList/ArticleCard.tsx
  apps/engineeringblog/components/ArticleList/ArticleList.tsx
  apps/engineeringblog/components/ArticleList/index.ts
  apps/engineeringblog/content/exploring-next-js.mdx
  apps/engineeringblog/content/javascript-generators.mdx
  apps/engineeringblog/content/mastering-docker.mdx
  apps/engineeringblog/utils/index.ts
  packages/commons-ui-core/src/ImageButton/ImageButton.js
  packages/commons-ui-core/src/NavBar/NavBar.js
  packages/commons-ui-core/src/NavList/NavList.js
  packages/commons-ui-core/src/RichTypography/RichTypography.js
  packages/commons-ui-core/src/Section/Section.js
Labels: chore

#881 Fix ClimateMappedAfrica Search
  apps/climatemappedafrica/src/components/DropdownSearch/index.js
Labels: bug

#882 @/commons-ui/core Social Media Links
  apps/civicsignalblog/next-env.d.ts
  apps/civicsignalblog/src/components/Footer/Footer.js
  apps/civicsignalblog/src/components/NavBarNavList/NavBarNavList.js
  apps/civicsignalblog/src/components/NavBarNavList/NavBarNavList.snap.js
  apps/civicsignalblog/src/components/StayInTouch/StayInTouch.js
  apps/civicsignalblog/src/components/StayInTouch/StayInTouch.snap.js
  apps/codeforafrica/next-env.d.ts
  apps/codeforafrica/src/components/Footer/Footer.js
  apps/codeforafrica/src/components/NavBarNavList/NavBarNavList.js
  apps/codeforafrica/src/components/NavBarNavList/NavBarNavList.snap.js
  apps/codeforafrica/src/components/StayInTouch/StayInTouch.js
  apps/codeforafrica/src/components/StayInTouch/StayInTouch.snap.js
  apps/codeforafrica/src/components/StayInTouch/StayInTouch.test.js
  apps/codeforafrica/src/components/StayInTouch/index.js
  apps/roboshield/next-env.d.ts
  apps/roboshield/src/components/DesktopNavBar/DesktopNavBar.tsx
  apps/roboshield/src/components/Footer/Footer.tsx
  apps/roboshield/src/components/Footer/FooterDescription.tsx
  apps/roboshield/src/components/MobileNavBar/MobileNavBar.tsx
  apps/roboshield/src/components/NavBar/NavBar.tsx
  apps/roboshield/src/components/NavBar/index.ts
  apps/roboshield/src/components/NavBarNavList/NavBarNavList.tsx
  apps/roboshield/src/components/NavBarNavList/index.ts
  apps/roboshield/src/components/NavListItem/NavListItem.tsx
  apps/roboshield/src/components/Page/Page.tsx
  apps/roboshield/src/components/SocialMediaLinkIcon/LinkIcon.tsx
  apps/roboshield/src/components/SocialMediaLinkIcon/SocialMediaLinkIcon.tsx
  apps/roboshield/src/components/SocialMediaLinkIcon/index.ts
  apps/roboshield/src/components/StayInTouch/StayInTouch.tsx
  apps/roboshield/src/components/StayInTouch/index.ts
  apps/vpnmanager/next-env.d.ts
  apps/vpnmanager/src/components/DesktopNavBar/DesktopNavBar.tsx
  apps/vpnmanager/src/components/MobileNavBar/MobileNavBar.tsx
  apps/vpnmanager/src/components/NavBar/NavBar.tsx
  apps/vpnmanager/src/components/NavBar/index.ts
  apps/vpnmanager/src/components/NavBarNavList/NavBarNavList.tsx
  apps/vpnmanager/src/components/NavBarNavList/index.ts
  apps/vpnmanager/src/components/NavListItem/NavListItem.tsx
  apps/vpnmanager/src/components/Page/Page.tsx
  packages/commons-ui-core/src/SocialMediaIconLink/IconLink.js
  packages/commons-ui-core/src/SocialMediaIconLink/SocialMediaIconLink.js
  packages/commons-ui-core/src/SocialMediaIconLink/SocialMediaIconLink.snap.js
  packages/commons-ui-core/src/SocialMediaIconLink/SocialMediaIconLink.test.js
  packages/commons-ui-core/src/SocialMediaIconLink/index.js
  packages/commons-ui-core/src/StayInTouch/StayInTouch.js
  packages/commons-ui-core/src/StayInTouch/StayInTouch.snap.js
  packages/commons-ui-core/src/StayInTouch/StayInTouch.test.js
  packages/commons-ui-core/src/StayInTouch/index.js
  packages/commons-ui-core/src/assets/icons/Type=facebook, Size=24, Color=CurrentColor.svg
  packages/commons-ui-core/src/assets/icons/Type=github, Size=24, Color=CurrentColor.svg
  packages/commons-ui-core/src/assets/icons/Type=instagram, Size=24, Color=CurrentColor.svg
  packages/commons-ui-core/src/assets/icons/Type=linkedin, Size=24, Color=CurrentColor.svg
  packages/commons-ui-core/src/assets/icons/Type=slack, Size=24, Color=CurrentColor.svg
  packages/commons-ui-core/src/assets/icons/Type=twitter, Size=24, Color=CurrentColor.svg
  packages/commons-ui-core/src/index.js
  packages/commons-ui-next/jest.config.js
  packages/commons-ui-next/src/RichTypography/RichTypography.snap.js
  packages/commons-ui-next/src/RichTypography/RichTypography.test.js
  packages/hurumap-core/jest.config.js
  packages/hurumap-next/jest.config.js
Labels: chore

#883 Fix charterafrica issues
  apps/charterafrica/contrib/dokku/Dockerfile
  apps/charterafrica/next-env.d.ts
  apps/charterafrica/package.json
  apps/charterafrica/src/payload/globals/FocalCountries.js
  apps/charterafrica/src/payload/globals/Footer.js
  apps/charterafrica/src/payload/globals/Settings.js
Labels: bug

#888 @/codeforafrica - fix: Partners form not rendering
  apps/codeforafrica/package.json
  apps/codeforafrica/src/payload/collections/Partners.js
Labels: bug

#890 @/engineeringblog Footer
  apps/civicsignalblog/src/components/NavBarNavList/NavBarNavList.snap.js
  apps/codeforafrica/src/components/NavBarNavList/NavBarNavList.snap.js
  apps/engineeringblog/app/layout.tsx
  apps/engineeringblog/components/Footer/Footer.tsx
  apps/engineeringblog/components/Footer/index.ts
  apps/engineeringblog/components/Logo/Logo.tsx
  apps/engineeringblog/components/NavBar/NavBarProps.tsx
  apps/engineeringblog/components/NavBarNavList/NavBarNavList.tsx
  apps/engineeringblog/content/site/settings.mdx
  apps/engineeringblog/lib/data/index.ts
  apps/engineeringblog/theme/index.ts
  packages/commons-ui-core/src/SocialMediaIconLink/SocialMediaIconLink.js
  packages/commons-ui-core/src/SocialMediaIconLink/SocialMediaIconLink.snap.js
Labels: enhancement

#892 @/engineeringblog GA analytics
  apps/engineeringblog/app/layout.tsx
  apps/engineeringblog/content/site/settings.mdx
  apps/engineeringblog/lib/data/index.ts
  apps/engineeringblog/package.json
  pnpm-lock.yaml
Labels: enhancement

#895 @charteafrica Fix SEO failing on production
  Dockerfile
  apps/charterafrica/contrib/dokku/Dockerfile
  apps/charterafrica/package.json
Labels: bug

#889 @vpnamanager UI outline vpn user stats
  apps/vpnmanager/package.json
  apps/vpnmanager/src/components/Statistics/Statistics.tsx
  apps/vpnmanager/src/components/Statistics/index.ts
  apps/vpnmanager/src/lib/data/database.ts
  apps/vpnmanager/src/lib/statistics.ts
  apps/vpnmanager/src/middleware.ts
  apps/vpnmanager/src/pages/index.tsx
  apps/vpnmanager/src/utils/index.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: enhancement

#901 @/CivicSignalBlog - Add ability to manage CivicSignal content
  apps/civicsignalblog/payload.config.ts
  apps/civicsignalblog/src/lib/data/json/countries.js
  apps/civicsignalblog/src/lib/payload/index.js
  apps/civicsignalblog/src/payload/access/applications/main.js
  apps/civicsignalblog/src/payload/access/applications/research.js
  apps/civicsignalblog/src/payload/access/canAccessApplication.js
  apps/civicsignalblog/src/payload/collections/Main/Pages.js
  apps/civicsignalblog/src/payload/collections/Pages.js
  apps/civicsignalblog/src/payload/collections/Research/Authors.js
  apps/civicsignalblog/src/payload/collections/Research/Media.js
  apps/civicsignalblog/src/payload/collections/Research/Pages.js
  apps/civicsignalblog/src/payload/collections/Research/Posts.js
  apps/civicsignalblog/src/payload/collections/Research/Tags.js
  apps/civicsignalblog/src/payload/collections/Users.js
  apps/civicsignalblog/src/payload/components/actions/index.tsx
  apps/civicsignalblog/src/payload/fields/links/link.js
  apps/civicsignalblog/src/payload/globals/Publication/index.js
  apps/civicsignalblog/src/payload/globals/Site/Components/EngagementTab.js
  apps/civicsignalblog/src/payload/globals/Site/Components/GeneralTab.js
  apps/civicsignalblog/src/payload/globals/Site/Components/NavigationTab.js
  apps/civicsignalblog/src/payload/globals/Site/index.js
  apps/civicsignalblog/src/payload/globals/Site/main.js
  apps/civicsignalblog/src/payload/globals/Site/research.js
  apps/civicsignalblog/src/payload/lib/data/common/applications.js
  apps/civicsignalblog/src/payload/utils/createGlobalSettings.js
  apps/civicsignalblog/src/payload/utils/createPagesCollection.js
Labels: enhancement

#899 Techlab Blog Deploy
  .github/workflows/build-docker-image.yml
  .github/workflows/push-to-dokku.yml
  .github/workflows/techlabblog-deploy-dev.yml
  Dockerfile
  Makefile
  apps/techlabblog/next.config.mjs
  apps/techlabblog/package.json
  docker-compose.yml
  pnpm-lock.yaml
Labels: chore
