Repository CodeForAfrica/ui, pull requests merged in 2024-05, with the labels that each got.

#696 Add Africa to list of countries.
  apps/charterafrica/contrib/dokku/Dockerfile
  apps/charterafrica/package.json
  apps/charterafrica/src/lib/data/common/processPageContributors.js
  apps/charterafrica/src/lib/data/common/processPageOrganisations.js
  apps/charterafrica/src/lib/data/common/processPageTools.js
  apps/charterafrica/src/lib/data/json/locations.js
  apps/charterafrica/src/lib/openAfrica.js
  apps/charterafrica/src/payload/collections/Tools.js
Labels: enhancement

#698 Fix @codeforafrica socialLinks
  apps/codeforafrica/contrib/dokku/Dockerfile
  apps/codeforafrica/package.json
  apps/codeforafrica/payload.config.ts
  apps/codeforafrica/src/payload/fields/socialLinks.js
Labels: bug

#700 Fix @charterafrica validate of select in an array field
  apps/charterafrica/contrib/dokku/Dockerfile
  apps/charterafrica/package.json
  apps/charterafrica/src/payload/blocks/Datasets.js
  apps/charterafrica/src/payload/fields/documentCloudFilterBar.js
  apps/charterafrica/src/payload/utils/validateUniqueArrayFieldSelect.js
Labels: bug

#701 @/pesayetu/ reduce the number stories pages built to just main ones
  apps/pesayetu/src/pages/stories/[[...slug]].js
Labels: chore

#673 Create Pesayetu dockerfile
  .github/workflows/pesayetu-deploy-dev.yml
  Dockerfile.pesayetu
  Makefile
  apps/pesayetu/src/components/HURUmap/Map/Layers.js
  apps/pesayetu/src/pages/stories/[[...slug]].js
  docker-compose.yml
Labels: chore
